### DISCUSSION TITLE
_user: sub conflited between two different lowdefy apps.

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1021] [Questions and Help] [answered]
I have a lowdefy app named AppManage,which is intergrated by keycloak as an open-id provider. In one of its requests, the user id is sent to the axioshttp api as the following code`    data:
      user_id:
        _log:
          _user: sub` 
It works.But when the browser (either with new browser tab or with new browser window) open another lowdefy app which is hosted the same ip and the different port with AppManage, then reload AppManage page , error occurs, the user_id is null!
![image](https://user-images.githubusercontent.com/56707831/145188656-1f20a0f9-a422-4fb9-a9f0-d172978e1754.png)
![image](https://user-images.githubusercontent.com/56707831/145188777-2bb1a622-691b-4a6b-8067-eb51573afa80.png)
![image](https://user-images.githubusercontent.com/56707831/145188902-5fca8490-1c20-448a-9719-68f4c317f934.png)

**Comment by SamTolmay** [comment, marked as answer]
Hi @13316090972 

The user isn't logged in in the new tab or window.

Is the AppManage page a protected page? 
To do this set `config.auth.pages.protected` to true, and don't list it as a public page. See [here](https://docs.lowdefy.com/protected-pages).

Then, the user won't be able to see that page if they are not logged in, and they will be redirected to the `404` page. You can create a custom 404 page to redirect them to login. Here is an example:

```yaml
# lowdefy.yaml
lowdefy: 3.23.2
config:
  homePageId: login
  auth:
    pages:
      protected: true
      public:
        - login
        - '404'

pages:
  - _ref: login.yaml
  - _ref: 404.yaml
  - _ref: AppManage.yaml
```

```yaml
# 404.yaml
id: '404'
type: Context
style:
  minHeight: 100vh
events:
  onEnter:
    - id: not_logged_in_redirect
      type: Link
      skip:
        _ne:
          - _user: sub
          - null
      params:
        home: true
blocks:
  - id: 404_result
    type: Result
    properties:
      status: 404
      title: '404'
      subTitle: Sorry, the page you are visiting does not exist.
    areas:
      extra:
        blocks:
          - id: home
            type: Button
            properties:
              title: Go to home page
              type: Link
              icon: HomeOutlined
            events:
              onClick:
                - id: home
                  type: Link
                  params:
                    home: true
```

```yaml
# login.yaml
id: login
type: Context
events:
  onEnter:
    - id: logged_in_redirect
      type: Link
      skip:
        _eq:
          - _user: sub
          - null
      params:
        pageId: AppManage
    - id: login
      type: Login
      skip:
        _ne:
          - _user: sub
          - null
      params:
        pageId: AppManage
```
