### DISCUSSION TITLE
a new problem,Configuration Error: Request xxx does not exist, with #1021 _user: sub conflited between two different lowdefy apps.

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1023] [Questions and Help]
After I visit another lowdefy app which has the same host and another port with AppManage with another browser new tab,I return back to AppManage and evoke one of its requests by clicking a button in it, then error comes as bellow:Configuration Error: Request xxx does not exist.
![image](https://user-images.githubusercontent.com/56707831/145502952-56716635-e400-4a3c-bd6a-a27b55aa2b58.png)
lowdefy.yaml
```
name: DiCLAP
lowdefy: 3.22.0
config:
  homePageId: loginPage
  auth:
    openId:
      _ref: openid.yaml
    pages:
      protected: true
      public:
        - loginPage
        - '404'
```
404.yaml
```
id: '404'
type: Context
style:
  minHeight: 100vh
events:
  onEnter:
    - id: not_logged_in_redirect
      type: Link
      skip:
        _ne:
          - _user: sub
          - null
      params:
        home: true
blocks:
  - id: 404_result
    type: Result
    properties:
      status: 404
      title: '404'
      subTitle: 迷路迷路，云深不知处。
    areas:
      extra:
        blocks:
          - id: home
            type: Button
            properties:
              title: Go to home page
              type: Link
              icon: HomeOutlined
            events:
              onClick:
                - id: home
                  type: Link
                  params:
                    home: true
```
login.yaml
```
# 登录页
id: loginPage
type: Context
events:
  onEnter:
    - id: logged_in_redirect
      type: Link
      skip:
        _eq:
          - _log: 
              _user: sub
          - null
      params: AppManage
    - id: login
      type: Login
      skip:
        _ne:
          - _user: sub
          - null
      params:
        # Redirect to "page1" after login is complete.
        pageId: AppManage
```
