### DISCUSSION TITLE
How to show value on Lable, Statistic operator

### DISCUSSION THREAD

**Discussion by mirzaehtishamdanish** [lowdefy/lowdefy#1027] [Questions and Help]
This is my Json response data as you see below

```yaml
- count: '0'
  oneMinRate: '20:27:18'
- count: '1'
  oneMinRate: '20:27:48'
- count: '2'
  oneMinRate: '20:28:18'
- count: '3'
  oneMinRate: '20:28:48'
- count: '4'
  oneMinRate: '20:29:18'
- count: '5'
  oneMinRate: '20:32:06'
- count: '6'
  oneMinRate: '20:32:10'
- count: '7'
  oneMinRate: '20:32:11'
- count: '8'
  oneMinRate: '20:32:11'
- count: '9'
  oneMinRate: '20:32:13'
- count: '10'
  oneMinRate: '20:32:13'
- count: '11'
  oneMinRate: '20:32:14'
- count: '12'
  oneMinRate: '20:32:14'
- count: '13'
  oneMinRate: '20:32:16'
- count: '14'
  oneMinRate: '20:32:17'
- count: '15'
  oneMinRate: '20:32:18'
- count: '16'
  oneMinRate: '20:32:18'
```
In above data I want to show Max Count Value into Lable, Statistic, or any card, but I can do this as you can see my code
```yaml
id: new-bar-chart
type: PageHeaderMenu
properties:
  title: Dashboard # The title in the browser tab.
layout:
  contentJustify: center # Center the contents of the page.

requests:
  - id: my_request
    type: AxiosHttp
    connectionId: my_api
    properties:
      url: /fruits/messages
      method: get
      headers:
        content-type: application/json

events:
  onEnter:
    - id: init_data
      type: Request
      params: my_request
    - id: start_refresh
      type: JsAction
      params:
        name: pollRequest
        args:
          - my_request
blocks:
  - id: content_card
    type: Card
    layout:
      size: 1200 # Set the size of the card so it does not fill the full screen.
      contentGutter: 16 # Make a 16px gap between all blocks in this card.
    blocks:
      - id: page_heading
        type: Title
        properties:
          content: ATM Thread Messaging Details # Change the title on the page.
          level: 3 # Make the title a little smaller (an html `<h3>`).  


      - id: basic_example
        type: Statistic
        properties:          
          prefixIcon: AlertTwoTone
          _request: my_request.data.0.day

      - id: rest_data
        type: Markdown
        properties:
          content:
            _string.concat:
              - |
                ```yaml
              - _yaml.stringify:
                  - _log:
                      _request: my_request.data
              - |
                ```
      - id: block_id
        type: Title
        properties:
          content:
            _log:
              _request: my_request.data
      
      - id: block_id
        type: EChart
        layout:
          span: 12 # Two thirds of the area
        properties:          
          option:
            dataset:
              source:
                # Use request operator to read request response
                # This request should probably be fetched in the page onEnterAsync event.
                _request: my_request.data

            xAxis:
              type: category
              # properties:
              #   title: Input title
            yAxis:
              type: value
            series:
              - type: line
                name: My Series
                encode:
                  x: oneMinRate
                  y: count

      - id: block_id
        type: EChart
        layout:
          span: 12 # Two thirds of the area
        properties:
          option:
            dataset:
              source:
                # Use request operator to read request response
                # This request should probably be fetched in the page onEnterAsync event.
                _request: my_request.data

            xAxis:
              type: category
              # properties:
              #   title: Input title
            yAxis:
              type: value
            series:
              - type: bar
                name: My Series
                encode:
                  x: oneMinRate
                  y: count
```
