### DISCUSSION TITLE
TextInput verification messages

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1030] [Questions and Help] [answered]
Hi, I want to use textinput for form verification. Can I not display the message of form validation error, but only the error message

**Comment by Gervwyk** [comment, marked as answer]
Hi @xiaoxiji1234 

Please provide a little more detail? Perhaps your current setup for the block or a screenshot of what you'd like the output to be.

**Reply by xiaoxiji1234** [reply]
Hi, @Gervwyk  
![image](https://user-images.githubusercontent.com/72787010/146894308-57186574-1902-4ecb-b9d8-4a9ba190a2d3.png)
Can this message be edited or not displayed?
![image](https://user-images.githubusercontent.com/72787010/146894477-f4a10a6e-5437-4d23-b2a2-4314ba9055fd.png)
Can the error content of text box verification be edited?

**Reply by SamTolmay** [reply]
Hi @xiaoxiji1234 

To change the "Your input has 1 validation error." message, you can add a custom error message to the `Validate` action. So you would do:
```yaml
id: submit
type: Button
events:
  onClick:
    - id: validate
      type: Validate
      messages:
        error: Custom validation message.
```
You can read more on action messages here: https://docs.lowdefy.com/events-and-actions

To change the validation text on the text input, you need to add a validation rule with the custom message, like this:
```yaml
id: text_input
type: TextInput
validate:
  - message: Custom required message.
    status: error
    pass:
      _not:
        _type: none
```
You can read more on block validation messages here: https://docs.lowdefy.com/blocks

**Reply by xiaoxiji1234** [reply]
Ok, Thank you very much

**Reply by xiaoxiji1234** [reply]
Hi, @SamTolmay  
I tried custom verification and found that the required prompt information could not be modified. Can this required prompt be modified?
![image](https://user-images.githubusercontent.com/72787010/153349665-db3273c7-2f21-44e0-bf4c-4ab776f4d945.png)

**Reply by SamTolmay** [reply]
Hi @xiaoxiji1234 

I see that the `required` validation is evaluated before the validation rules in the validate array, so the required message is shown instead of the custom message. I have opened an issue for this: #1101 

One thing you can do is remove the `required: true` property, but then you won't have the red required asterisk symbol. 
You can also maybe try something like this html block, and set `properties.label.disabled: true` on the textinput, but this isn't a great solution:
```yaml
      - id: required_label
        type: Html
        layout:
          span: 10
          align: right
        properties:
          html: <div style="text-align:right"><p><span style="color:red;">*</span> <span style="color:black;">Label title:</span></p></div>
```
