### DISCUSSION TITLE
Graphql requests

### DISCUSSION THREAD

**Discussion by cverdes** [lowdefy/lowdefy#1037] [Questions and Help] [answered]
Hello community,

I just discovered lowdefy yesterday morning and I'm digging into it. It's great and designed over a very smart idea! 
I think that it has a great potential and It's very well documented, thank you very much.

Is it possible to make a GraphQL request with some of the current connectors? If it is not, is a plan to develop a connector to make GraphQL requests easily. I think that lowdefy could be a very good [Hasura](https://github.com/hasura/graphql-engine) backend companion.

Thanks in advance.

**Comment by SamTolmay** [comment, marked as answer]
Hi @cverdes 

Hasura does look like a good fit for Lowdefy, I will have a look at their project.

You can make GraphQL queries over HTTP, using the `AxiosHttp` connection.

As an example, your connection might look like:
```yaml
id: gql_server
type: AxiosHttp
properties:
  url: https://server.example.com/graphql
  method: post
  headers:
    x-api-key:
      _secret: GQL_API_KEY
```

And your request might be:
```yaml
id: gql_query
type: AxiosHttp
connectionId: gql_server
properties:
  data:
    query: |
      query HeroName($episode: Episode) {
        hero(episode: $episode) {
          name
        }
      }
    variables:
      episode: JEDI
```

We do have an open issue for a GraphQL connection(#298). The plan for this connection is to be a wrapper around the axios HTTP library which adds some syntactic sugar, making it simpler to make requests.
