### DISCUSSION TITLE
how to use events.onClick demo in Context block?

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1040] [Questions and Help]
There is a piece of  sample code in packages\blocks\blocksBasic\demo\examples\Context.yaml,How to use it?

```
- id: events.onClick
  type: Context
  areas:
    content:
      blocks:
        - id: testArea
          type: Test
  events:
    onClick:
      - id: testAction
        type: Text
```
