### DISCUSSION TITLE
Debugging

### DISCUSSION THREAD

**Discussion by ghost** [lowdefy/lowdefy#1044] [Questions and Help]
Hi
Is there any way for actual debugging things? The information from dev server "Schema Error should NOT have additional properties" are not useful.

**Comment by cverdes** [comment]
I share the need to improve the intelligence and expressiveness of lowdefy's compile-time error detection.
I understand that a Language Server for VSCode could help a lot in this situation, but maybe there are possibilities for simpler improvements and in less time.
They will undoubtedly be very grateful to the community.
Thanks in advance.

**Comment by SamTolmay** [comment]
Hi @mcflyonthecloud 

We did release #636 in v3.23 to make the path to the block with the schema error easier to read, so the warning now reads:
```
should NOT have additional properties
- pages
 - [0:home:Context].blocks
  - [1:add_one:Button].events.onClick
   - [0:add_one:SetState]
```
instead of
```
message: should NOT have additional properties
path: /pages/0/blocks/1/events/onClick/0
```

Which should hopefully make it easier to find the block with the error. So if you aren't using v3.23 upgrading will help with this. Maybe we could also add the  file path to the issue, or by make the error messages returned from schema validation more useful.

We will be woring on making the development experience easier, so please let us know where you are having issues, or with ideas and suggestions where we can improve.

**Reply by ghost** [reply]
Hi
yes, I'm using still most of those errors that don't make sense like "should NOT have additional properties" when I try to use events. A good example here is PageHeaderMenu which is showing an error when I try to use events
```yaml
onEnter:
    - id: Example1
      type: Request
      params:
        - do_something
    - id: Example2
      type: SetState
      params:
        X:
          _request: get_something
    - id: Example3
      type: Request
      params:
        - get_something
    - id: Example4
      type: Link
      _if:
        test:
          _eq:
            - "false"
            - _request: get_somthing.value
        then:
          params: diffrent_page
```
and the error
```
should NOT have additional properties
- pages
 - [11:x:PageHeaderMenu].events.onEnter
  - [3:Example4:Link]
Schema Error
should be object
```
and then at the same time in the documentation I see "Actions Types":
CallMethod - Call a method defined by another block.
JsAction - Call a custom JavaScript function as an action.
Link - Link to another page.
Message - Show a message to the user.
Notification - Show a notification to the user.
Request - Call a request.
Reset - Reset the page validation and state.
ScrollTo - Scroll to a point on the page.
SetGlobal - Set a value to the global variable object.
SetState - Set a value to the page state.
Validate - Validate the inputs on the page.
