### DISCUSSION TITLE
Realize the hover effect in CSS

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1056] [Questions and Help] [answered]
Hi, I want to realize the hover background color change effect of CSS in block. How should I realize it?

**Comment by Gervwyk** [comment, marked as answer]
Hi @xiaoxiji1234 

Lowdefy implements styles on blocks using [Emotion CSS](https://emotion.sh/docs/introduction). Thus you can do this:
```yaml
lowdefy: 3.23.2
name: Lowdefy
pages:
  - id: page
    type: Context
    blocks:
      - id: bg
        type: Box
        style:
          '&:hover':
            background: '#f00'
        blocks:
          - id: content
            type: Paragraph
            properties:
              content: Hover to see color change.
```

> Note the quotes around the color value, this is added to escape the `#` which is used to indicate comments in yaml and thus the property could be ignored if not placed between quotation marks.
