### DISCUSSION TITLE
_var question

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1060] [Questions and Help]
Hi, I use the vars operator to pass an object processed by the operator, but I can't get the value of this object in the referenced file. Why?
```
_ref: 
  path: templates/component/{{ formType }}.yaml.njk
  vars: 
    field:
      _array.find:
            on: 
              _global: formData
            callback:
              _function:
                __eq:
                  - __args: 0.block.formType
                  - {{ formType }}
```
```
id: sss
type: Button
events:
    onClick:
      - id: ssssss
        type: SetState
        params:
          aa:
            _log:               
              _var: field.block      // value is null
```

**Comment by Gervwyk** [comment]
HI @xiaoxiji1234 
Thinking that it is related to your logic for `field` in your template. Can you just try passing a constant value to confirm that?

**Reply by xiaoxiji1234** [reply]
Hi, @Gervwyk  
I try to pass a constant that can be obtained. But if I get the `field `directly, I can get the object, but get the field The value of block is null.
```
id: sss
type: Button
events:
    onClick:
      - id: ssssss
        type: SetState
        params:
          aa:
            _log:               
              _var: field      // value:   { block: aaa }
          bb:
             _var: field.block        // value:  null

```

**Reply by Gervwyk** [reply]
Aah.. We haven't implemented get subfield for `_var` yet. It is something we want to add. For now you can user `_get`:
```yaml
id: sss
type: Button
events:
    onClick:
      - id: ssssss
        type: SetState
        params:
          aa:
            _log:               
              _var: field      // value:   { block: aaa }
          bb:
            _get:
               key: block
               from:
                  _var: field  
```
