### DISCUSSION TITLE
Questions about DateTimeSelector Block

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1133] [Questions and Help]
Hi, I'm in `Test.yaml.njk` file uses the `DateTimeSelector Block`, but once the time is selected, the block cannot be changed directly, and the value cannot be updated directly. You can only empty it and reselect the timebut once the time is selected, the block cannot be changed directly, and the value cannot be updated directly. I can only empty it and reselect the time.
![image](https://user-images.githubusercontent.com/72787010/155938008-15b812c3-ea8f-4143-9dc4-9e33b2734efa.png)
`Test.yaml.njk:`
```yaml
id: record.value.DatePicker10
type: DateTimeSelector
properties:
  disabledDates:
    dates: []
    ranges: []
```
