### DISCUSSION TITLE
How to select action block through judgment

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1135] [Questions and Help] [answered]
Hi, I have an `onClick` event. I want to select the `type` in the `Action Block` by judgment. For example, type: state when a = = 1, type: link when a = = 2

**Comment by Gervwyk** [comment, marked as answer]
Hi @xiaoxiji1234 
At the moment, block types are not evaluated after initialization, thus you can not modify a block type on logic. We might change this in the future, for now, you can use the `visible` field on blocks to render one block or the other:
```yaml
- id: toggle_btn
  type: Button
  events:
    onClick:
      - id: toggle
         type: SetState
         params:
           flag: 
             _not: 
               _state: flag
- id: input
  type: TextInput
  visible:
    _state: flag
- id: input
  type: Selector
  visible:
    _not:
      _state: flag
```
