### DISCUSSION TITLE
how to use jsonSet in KnexBuilder?

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1143] [Questions and Help]
if i want to execute a sql like this `UPDATE t_mytable SET value = JSON_SET(value,'$.TextInput1', 'aaa') WHERE id = 42`,how can i write the request by using KnexBuilder ?
I guess it as below:
```
id: knexBuilder
type: KnexBuilder
connectionId: knex
  properties:
    tableName: t_form_value
    query:
      - update:
        - value:
            jsonSet:
              - value
              -  TextInput1
              - aaa
      - Where:
          - id
          - 42
```
but lowdefy report error:
Request Error: update `t_form_value` set `value` = {"jsonSet":["value","TextInput1","aaa"]} where `id` = 42 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''TextInput1', 'aaa' where `id` = 42' at line 1

**Comment by SamTolmay** [comment]
Hi @13316090972 

Maybe you could try:
```yaml
id: knexBuilder
type: KnexBuilder
connectionId: knex
properties:
  tableName: t_form_value
  query:
    - jsonSet:
        - value
        - TextInput1
        - aaa
    - where:
        - id
        - 42
```
