### DISCUSSION TITLE
AgGrid paging example or snippet

### DISCUSSION THREAD

**Discussion by 7studios** [lowdefy/lowdefy#1152] [Questions and Help] [answered]
How would we go about adding paging to AgGrid block? I have pagination set to true, do we need to handle state or paging size?

- id: gl_table
        type: AgGridAlpine
        properties:
          theme: basic
          rowData:
            _request: fetch_customer_gl
          defaultColDef: # Define default column definitions that apply to all the defined columns
            sortable: true # Enables sorting on the columns when the header is clicked
            resizable: true # Enables resizing of column widths
            filter: true # Enables filtering of the columns using agGrid's default filter
            editable: true
            pagination: true
          columnDefs: # Define all the columns...

**Comment by Gervwyk** [comment, marked as answer]
Hi @7studios 
I've recently added pagination to an app, however, I used the [`Pagination`](https://docs.lowdefy.com/Pagination) block as input for query parameters to enable pagination. Here is an example of a MongoDB implementation:
```yaml
# request
id: get_data
type: MongoDBAggregation
connectionId: foo_data
properties:
  pipeline:
    # ... ag stages
    - $sort:
        timestamp: -1
    - $skip:
        _state: page.tabel.skip
    - $limit:
        _state: page.tabel.pageSize

# data table
         - id: data_tabel
            type: AgGridBalham
            properties:
              rowData:
                _request: get_data
              columnDefs:
                # ... columns
          - id: space_right
            type: Box
            layout:
              flex: 1 0 auto
          - id:  page.tabel
            type: Pagination
            layout:
              flex: 0 1 auto
            properties:
              disabled:
                _state: page.tabel.loading
              total:
                _request: get_data.length
              pageSizeOptions:
                - 100
                - 500
                - 1000
            events:
              onChange:
                - id: set_loader
                  type: SetState
                  params:
                    page.tabel.loading: true
                - id: fetch_data
                  type: Request
                  params: get_data
                - id: set_loader
                  type: SetState
                  params:
                    page.tabel.loading: false
```
See the [`Pagination`](https://docs.lowdefy.com/Pagination) block for more details.

**Reply by chriseudy** [reply]
How would you do this same thing with AxiosHttp? Wondering how this would look on different pages that render different tables. Can this go with the events?

Format:
```json
[
	{
		"id": 1,
		"formatName": "McDonaldsBigMac",
		"format": "",
		"functionCall": "sp_getMcDonaldsData",
		"createdAt": "2022-03-31T22:57:13.20497+00:00",
		"updatedAt": null
	},
	{
		"id": 2,
		"formatName": "McDonaldsBurrito",
		"format": "",
		"functionCall": "sp_getMcDonaldsData",
		"createdAt": "2022-03-31T22:57:13.20497+00:00",
		"updatedAt": null
	},
	{
		"id": 3,
		"formatName": "McDonaldsDoubleCheese",
		"format": "",
		"functionCall": "sp_getMcDonaldsData",
		"createdAt": "2022-03-31T22:57:13.20497+00:00",
		"updatedAt": null
	},
	{
		"id": 4,
		"formatName": "McDonaldsChicken",
		"format": "",
		"functionCall": "sp_getMcDonaldsData",
		"createdAt": "2022-03-31T22:57:13.20497+00:00",
		"updatedAt": null
	},
	{
		"id": 5,
		"formatName": "McDonaldsQuarterPounder",
		"format": "",
		"functionCall": "sp_getMcDonaldsData",
		"createdAt": "2022-03-31T22:57:13.20497+00:00",
		"updatedAt": null
	},
	{
		"id": 7,
		"formatName": "asdfasd",
		"format": "asdf",
		"functionCall": null,
		"createdAt": "2022-04-07T18:34:31.483115+00:00",
		"updatedAt": null
	}
]
```

My labels yaml that I want to turn into a table:
```yaml
id: current-labels
type: PageSiderMenu
properties:
  title: List of Labels # The title in the browser tab.
requests: 
  - id: get_labels
    type: AxiosHttp
    connectionId: postgrest
    properties:
      url: /labels
events: 
  onEnter: 
    - id: fetch_labels
      type: Request
      params: get_labels
    - id: set_labels
      type: SetState
      params: 
        labels_list:
          _request: get_labels.data
blocks:
  - id: labels_list
    type: List
    blocks: 
      - id: labels_list.$.container
        type: Box
        style:
          background: '#fff' # Give the box a white background and some spacing.
          margin: 10
          padding: 10
        blocks:
          - id: labels_list.$.formatName # Show the item name as a title in the list.
            type: Title
            properties:
              content:
                _state: labels_list.$.formatName
              level: 3
          - id: labels_list.$.createdAt # Show the item description as a paragraph in the list.
            type: Paragraph
            properties:
              content:
                _state: labels_list.$.createdAt
          - id: labels_list.$.updatedAt # Show the item description as a paragraph in the list.
            type: Paragraph
            properties:
              content:
                _state: labels_list.$.updatedAt
```
