### DISCUSSION TITLE
AxiosHttp

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1157] [Questions and Help]
Hi, I use `AxiosHttpto` set the `HTTP` request. This request is a `post` request. The parameter required by the body is an array. If I write the array directly in the data, an error will be reported. Is there any method?
data:
```json
[
    {
        "id": "90e673d7-ee94-4bcd-84ae-9d50ce43ade2",
        "name" : "appAdmin"
     }
]
```
Error:
![image](https://user-images.githubusercontent.com/72787010/161885546-f0341088-0ae1-45ee-b98b-27092b9d77bf.png)
Request
```yaml
id: postUserRole
type: AxiosHttp
connectionId: keycloakURL
properties:
  url:
    _string.concat:
      - /admin/realms/
      - _global: realm
      - /users/34164188-3197-434a-b7ad-99218ea26ccc/role-mappings/realm
  method: post
  data:
    - name: appAdmin
      id: 90e673d7-ee94-4bcd-84ae-9d50ce43ade2
```
