### DISCUSSION TITLE
Make a change, get 404

### DISCUSSION THREAD

**Discussion by chriseudy** [lowdefy/lowdefy#1167] [Questions and Help] [answered]
I'm new to Lowdefy and still trying to understand quite a bit. While developing on Windows, with VS Code, node.js, and using "npx lowdefy@latest dev" to start the server (localhost) and learn Lowdefy I'm constantly getting a redirect to 404 after making a change that Lowdefy doesn't like. I get no errors in the console or any that I can see in development mode of Firefox or Chrome. No matter what I do (even reverting to known good yaml) it still won't recover and redirects to 404. The only way I can resolve this is to delete the .lowdefy folder. 

_EDIT: I simply change a title from "Labels" to "Label" in my lowdefy.yaml and reproduce this issue. I also tried running the "lowdefy dev clean-cache" and this doesn't resolve the issue. I have to delete the .lowdefy folder and start the application again with "lowdefy dev" or the npx command._

So a few questions:
1.  Is there a switch to clear the cache using npx?
2.  Am I using best practice command by using npx?
3.  Why 404?
4.  Is there a best practice for catching some sort of log for the redirect to 404?

Thank you.

**Comment by SamTolmay** [comment]
Hi @chriseudy 

Regarding Q1 and 2:
npx can be used to run a CLI command from npm without downloading that package as a global or project dependency. This has a couple of advantages, namely:
- You can run multiple versions of the command easily. So you can do `npx lowdefy@3.23.2 dev` for one project, and `npx lowdefy@3.14.0` for an older outdated project.
- You can make sure you are always running the latest version by running `npx lowdefy@latest dev`. If you installed the package you would need to update it.
- This is a good option for users starting with Lowdefy, since it doesn't install something permanent on their system.

The main disadvantage I find with `npx` is that it can be a little slow to start each time, so I personally install lowdefy globally using `npm install lowdefy -g`, and running `npm update -g lowdefy` when a new version of Lowdefy is released.

You can run any cli command using npx, so to run `clean-cache` you would do `npx lowdefy@latest clean-cache`

Regarding the 404 error:
I don't think cleaning the cache will resolve this issue. 

You would can redirected to the 404 if that page does not exist, if the page is protected by authentication (maybe a role is on the page that your user does not have) or by a `Link` action. All of these don't seem to be the case.

I would look at any possible `Link` actions, and I would also look if a `_ref` operator is maybe not picking up the page correctly. If you have any warnings in the CLI I would also try resolve those. Also, if you are changing the pageId instead of a title that would result in a 404.

Maybe if you could share some config with us we could help find the issue

**Reply by SamTolmay** [reply]
@Gervwyk Do you have any idea what this might be?

**Reply by Gervwyk** [reply]
Also if you have a`homePageId` defined with a page id that does not exist, this can cause a 404 redirect. @chriseudy Is there any way you can share parts of your config? Perhaps the `config`, `menu` and page ids. Even page `onEnter` or `onInit` events can cause this like @SamTolmay mentioned.

**Reply by chriseudy** [reply]
Thanks for the help guys. Here's my lowdefy.yaml:
```yaml

lowdefy: 3.23.2
name: Lowdefy starter
connections:
  - id: postgrest
    type: AxiosHttp
    properties:
      baseURL: http://somedns.local:5433
types:
  AgGridAlpine:
    url: https://blocks-cdn.lowdefy.com/v3.12.3/blocks-aggrid/meta/AgGridAlpine.json
menus:
  - id: default
    links:
      - id: current-labels
        type: MenuLink
        properties:
          icon: AlertOutlined 
          title: Labels
        pageId: current-labels
      - id: current-printers
        type: MenuLink
        properties:
          icon: AlertOutlined
          title: Printers
        pageId: current-printers
      - id: current-locations
        type: MenuLink
        properties:
          icon: AlertOutlined
          title: Locations
        pageId: current-locations
      - id: current-containertype
        type: MenuLink
        properties:
          icon: AlertOutlined
          title: Container Types
        pageId: current-containertype
      - id: current-printxref
        type: MenuLink
        properties:
          icon: AlertOutlined
          title: Print Xref
        pageId: current-printxref
      - id: current-printqueue
        type: MenuLink
        properties:
          icon: AlertOutlined
          title: Print Queue
        pageId: current-printqueue
      - id: next-number
        type: MenuLink
        properties:
          icon: AlertOutlined
          title: Next Numbers
        pageId: next-number
pages:
  - _ref: current-labels.yaml
  - _ref: current-printers.yaml
  - _ref: current-locations.yaml
  - _ref: current-containertype.yaml
  - _ref: current-printxref.yaml
  - _ref: current-printqueue.yaml
  - _ref: next-number.yaml
```

and here's one of the pages:
```yaml
id: current-printers
type: PageSiderMenu
properties:
  title: List of printers # The title in the browser tab.
requests: 
  - id: get_printers
    type: AxiosHttp
    connectionId: postgrest
    properties:
      url: /labelPrinters
events: 
  onEnter: 
    - id: fetch_printers
      type: Request
      params: get_printers
    - id: set_printers
      type: SetState
      params: 
        printers_list:
          _request: get_printers.data   
blocks:
  - id: printers_list
    type: List
    blocks: 
      - id: printers_list.$.container
        type: Box
        style:
          background: '#fff' # Give the box a white background and some spacing.
          margin: 10
          padding: 10
        blocks:
          - id: printers_list.$.printerName # Show the item name as a title in the list.
            type: Title
            properties:
              content:
                _state: printers_list.$.printerName
              level: 3
          - id: printers_list.$.ipAddress # Show the item description as a paragraph in the list.
            type: Paragraph
            properties:
              content:
                _state: printers_list.$.ipAddress
          - id: printers_list.$.locationId # Show the item description as a paragraph in the list.
            type: Paragraph
            properties:
              content:
                _state: printers_list.$.locationId
          - id: printers_list.$.createdAt # Show the item description as a paragraph in the list.
            type: Paragraph
            properties:
              content:
                _state: printers_list.$.createdAt
          - id: printers_list.$.updatedAt # Show the item description as a paragraph in the list.
            type: Paragraph
            properties:
              content:
                _state: printers_list.$.updatedAt


```
