### DISCUSSION TITLE
Error: Block type "AgGridAlpine" is not defined. Specify type url in types array.

### DISCUSSION THREAD

**Discussion by chriseudy** [lowdefy/lowdefy#1168] [Questions and Help] [answered]
I see all of these examples in the forums about using AgGrid, but when I use it I get the above titled error.

Here's my yaml:
```yaml
id: current-labels
type: PageSiderMenu
properties:
  title: List of Labels # The title in the browser tab.
requests: 
  - id: get_labels
    type: AxiosHttp
    connectionId: postgrest
    properties:
      url: /labels
events: 
  onEnter: 
    - id: fetch_labels
      type: Request
      params: get_labels
    - id: set_labels
      type: SetState
      params: 
        table:
          _request: get_labels.data
blocks:
  - id: table_card
    type: Card
    blocks:
      - id: table
        type: AgGridAlpine
        properties:
          rowData:
            - _get:
              key: data
              from:
                _request: get_labels
          defaultColDef:  
            sortable: true
            resizable: true
            filter: true  


```

**Comment by SamTolmay** [comment, marked as answer]
Hi @chriseudy 

AgGrid is a custom block and not part of the default blocks shipped with Lowdefy. 

To use it, you need to add the following to your `lowdefy.yaml` file:
```yaml
types:
  AgGridAlpine:
    url: https://blocks-cdn.lowdefy.com/v3.12.3/blocks-aggrid/meta/AgGridAlpine.json
```

You can read more about it here:
https://github.com/lowdefy/blocks-aggrid
https://docs.lowdefy.com/custom-blocks
