### DISCUSSION TITLE
AgGrid example with AxiosHttp

### DISCUSSION THREAD

**Discussion by chriseudy** [lowdefy/lowdefy#1169] [Questions and Help] [answered]
Hey guys,

I'm looking for an example of using AxiosHttp with AgGrid. I'm trying the below and not getting anything in my table. I know the request works because it was rendering data in a simple paragraph format before trying the table.

```yaml
id: current-labels
type: PageSiderMenu
properties:
  title: List of Labels # The title in the browser tab.
requests: 
  - id: get_labels
    type: AxiosHttp
    connectionId: postgrest
    properties:
      url: /labels
events: 
  onEnter: 
    - id: fetch_labels
      type: Request
      params: get_labels
    - id: set_labels
      type: SetState
      params: 
        table:
          _request: get_labels.data
blocks:
  - id: table_card
    type: Card
    blocks:
      - id: table
        type: AgGridAlpine
        properties:
          rowData:
            _log:
              - _get:
                key: data
                from:
                  _request: get_labels
          defaultColDef:  
            sortable: true
            resizable: true
            filter: true  
          items:
            - label: Label Name
              value:
                - _get:
                    key: data.formatName
                    from:
                      _request: get_labels
            - label: Format
              value:
                - _get:
                    key: data.format
                    from:
                      _request: get_labels
```
Here's example data from my endpoint:
```json
[
	{
		"id": 1,
		"formatName": "McDonaldsBigMac",
		"format": "",
		"functionCall": "sp_getMcDonaldsData",
		"createdAt": "2022-03-31T22:57:13.20497+00:00",
		"updatedAt": null
	},
	{
		"id": 2,
		"formatName": "McDonaldsBurrito",
		"format": "",
		"functionCall": "sp_getMcDonaldsData",
		"createdAt": "2022-03-31T22:57:13.20497+00:00",
		"updatedAt": null
	},
	{
		"id": 3,
		"formatName": "McDonaldsDoubleCheese",
		"format": "",
		"functionCall": "sp_getMcDonaldsData",
		"createdAt": "2022-03-31T22:57:13.20497+00:00",
		"updatedAt": null
	}
]
```

All I get is:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/88747953/163021035-62a6430c-73a4-407b-885e-26df523b0100.png">

Here's data from another page and another dataset:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/88747953/163022295-c83feb3b-a1ee-4bf5-9dd6-9f527fb66e18.png">

What am I doing wrong? (and I don't know where that "_log" is supposed to be going.)

**Comment by chriseudy** [comment, marked as answer]
This worked:
```yaml
id: current-labels
type: PageSiderMenu
properties:
  title: List of Labels # The title in the browser tab.
requests: 
  - id: get_labels
    type: AxiosHttp
    connectionId: postgrest
    properties:
      url: /labels
events: 
  onInit: 
    - id: fetch_labels
      type: Request
      params: 
        - get_labels
blocks:
  - id: table_card
    type: Card
    blocks:
      - id: table
        type: AgGridAlpine
        properties:
          rowData:
            _get:
             key: data
             from:
               _request: get_labels 
          autoSize:
            - skipHeader: true
          defaultColDef:  
            sortable: true
            resizable: true
            filter: true  
          # You have to define the columns for the data to be mapped to.
          columnDefs:
            - headerName: ID
              field: id
            - headerName: Label Name
              field: formatName
              filter: agTextColumnFilter
              #width: 350
            - headerName: Format
              field: format
            - headerName: Function Call
              field: functionCall
              #width: 350
            - headerName: Created At
              field: createdAt
              width: 350
            - headerName: Updated At
              field: updatedAt
```

**Reply by Gervwyk** [reply]
Hi @chriseudy 

Glad you got it working 👏 Was just busy typing out an answer for you.

With regards to the console log:
If you left-click anywhere on the page and click inspect, you'll open your browser's console. [`_log`](https://github.com/lowdefy/lowdefy/blob/main/packages/plugins/operators/operators-js/src/operators/shared/log.js) will post data to the browser console window since it is simply calling the browser's [`console.log()`](https://developer.chrome.com/docs/devtools/console/log/).

**Reply by chriseudy** [reply]
Thanks. I'm sorting that out now that I've been troubleshooting how this all works. I have another question about filtering the AgGrid, but I'll post a new discussion for it.

**Reply by Gervwyk** [reply]
btw the `autoSize` method is an action which exposed by the block so it can be called by other blocks. 
like so:
```yaml
- id: table_card
    type: Card
    blocks:
      - id: auto_size_it
        type: Button
        events:
           onClick:
             - id: auto
                type: CallMethod
                params:
                  blockId: table
                  method: autoSize
                  args:
                    - skipHeader: true
      - id: table
        type: AgGridAlpine
        properties:
          rowData:
            _request: get_labels.data 
          defaultColDef:  
            sortable: true
            resizable: true
            filter: true  
          # You have to define the columns for the data to be mapped to.
          columnDefs:
            - headerName: ID
              field: id
            - headerName: Label Name
              field: formatName
              filter: agTextColumnFilter
              #width: 350
            - headerName: Format
              field: format
            - headerName: Function Call
              field: functionCall
              #width: 350
            - headerName: Created At
              field: createdAt
              width: 350
            - headerName: Updated At
              field: updatedAt
```
