### DISCUSSION TITLE
AgGrid filtering

### DISCUSSION THREAD

**Discussion by chriseudy** [lowdefy/lowdefy#1172] [Questions and Help] [answered]
I'm trying to add filtering similar to:
![image](https://user-images.githubusercontent.com/88747953/163255240-708dd560-e7ba-4ecc-98c3-4b9291265104.png)

I thought it would be as easy as adding the "filter":
```yaml
 columnDefs:
            - headerName: ID
              field: id
            - headerName: Label Name
              field: formatName
              editable: false
              filter: agTextColumnFilter
```
However, that doesn't seem to work.

**Comment by Gervwyk** [comment, marked as answer]
Hi @chriseudy 

We have a similar table with config:
```yaml
             defaultColDef:
                filter: true
                resizable: true
                selectable: true
                sortable: true
                width: 200
                floatingFilter: true
                filterParams:
                  buttons:
                    - reset
                    - apply
              columnDefs:
                - field: name
                  lockPosition: true
                  headerName: NAME
                  width: 250
                - field: cost
                  headerName: COST
                  width: 150
                  type: 'rightAligned'
                - field: created.timestamp
                  headerName: CREATED
                  width: 140
                  filter: 'agDateColumnFilter'
                  cellRenderer:
                    _function:
                      __nunjucks:
                        template: |
                          {{ timestamp | date('D MMM YYYY') }}
                        on:
                          timestamp:
                            __args: 0.data.created.timestamp
```

**Reply by chriseudy** [reply]
Yup, I was missing a few defaultColDefs:
```yaml
          defaultColDef:  
            sortable: true
            resizable: true
            filter: true 
            floatingFilter: true
            filterParams:
              buttons:
                - reset
                - apply 
          # You have to define the columns for the data to be mapped to.
          columnDefs:
            - headerName: ID
              field: id
            - headerName: Label Name
              field: formatName
              editable: false
              filter: agTextColumnFilter
```

Thanks!
