### DISCUSSION TITLE
How to convert  timestamp to a date string

### DISCUSSION THREAD

**Discussion by monica0529** [lowdefy/lowdefy#1179] [Questions and Help]
How to convert  timestamp to a date string  by lowdefy.  I tried several methods(e.g._format.momentFormat) provided by _format  and _date, but failed.
____________________
 _format.intlDateTimeFormat
 _format.intlListFormat
 _format.intlNumberFormat
 _format.intlRelativeTimeFormat
 _format.momentFormat
 _format.momentHumanizeDuration

**Comment by Gervwyk** [comment]
Hi @monica0529

Two ways we often use:
1) Using the _nunjucks oprator:
```
_nunjucks:
  template: "{{ a_date | date('dd-mm-yyyy') }}"
  on: 
   a_date:
     _date: now
```

2) Using the _format operator:
```
_format.momentFormat:
  on:
    _date: 2019-06-04
  params:
    format: 'd MMM YYYY'
```
