### DISCUSSION TITLE
is there any tutorial for MySQL connection and fetching data using lowdefy?

### DISCUSSION THREAD

**Discussion by awsomedesigner** [lowdefy/lowdefy#1181] [Questions and Help] [answered]
I want to connect my MySQL database with lowdefy. 

Is there any tutorial for the same or can you please help me on that as I am new to lowdefy and want to explore more about this.

I also want to explore auth0 connection with app.
There is one demo but didn't get more info from that demo app.

Thank you

**Comment by muzivusa** [comment]
same as well with me would an example on mysql , I have managed to connect , using the conection tutorial but i'm not able to display my data

**Reply by awsomedesigner** [reply]
I can help you with that as I did that. Let me know your issue with the same. Where will you need help?

**Comment by muzivusa** [comment]
Hey , 
I,m trying to learn dashboards , currently practising with the pie chart  ,I'm getting a blank page , but when inspecting on the network the data is coming through but the console is empty 
see below my code 

I defined my connection on the .env file

on the lowdefy.yaml 
```yaml
lowdefy: 3.23.3
name: Lowdefy starter
types:
  AmChartsXY:
    url: https://blocks-cdn.lowdefy.com/v3.10.1/blocks-amcharts/meta/AmChartsXY.json
  AmChartsPie:
    url: https://blocks-cdn.lowdefy.com/v3.10.1/blocks-amcharts/meta/AmChartsPie.json
  AgGridAlpine:
    url: https://blocks-cdn.lowdefy.com/v3.10.1/blocks-aggrid/meta/AgGridAlpine.json

connections:
  - id: local_mysql
    type: Knex
       connection:
        host:
          _secret: MYSQL_HOST
        user:
          _secret: MYSQL_USER
        database:
          _secret: MYSQL_DB
        password:
          _secret: MYSQL_PASSWORD

pages:
  - _ref: piechart.yaml
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    areas:
      content:
        justify: center
        blocks:
          - id: content_card
            type: Card
            style:
              maxWidth: 
            blocks:
              - id: content
                type: Result
                properties:
                  title: Welcome to your Lowdefy app
                  subTitle: We are excited to see what you are going to build
                  icon:
                    name: HeartTwoTone
                    color: '#f00'
                areas:
                  extra:
                    blocks:
                      - id: docs_button
                        type: Button
                        properties:
                          size: large
                          title: Let's build something
                          color: '#1890ff'
                        events:
                          onClick:
                            - id: link_to_docs
                              type: Link
                              params:
                                url: https://docs.lowdefy.com
                                newTab: true
      footer:
        blocks:
          - id: footer
            type: Paragraph
            properties:
              type: secondary
              content: |
                Made by a Lowdefy 🤖
```
and the piechart.yaml:
```yaml
id: pie-chart
type: PageHeaderMenu
requests:
  - id: get_pie_chart_data
    type: KnexRaw
    connectionId: local_mysql
    properties:
     query: select master_label,value from master_table;
     # query:
        # - select:
        #   - '*'
        #   - raw:
        #     - (select employee_group.description as employee_group, count(employee.employee_group_id) as count from employee left join employee_group on employee_group.id = employee.employee_group_id group by employee_group.description) f
        # - from:
        #   - f
     # - select:
      #  - master_label,     
      #  - value
     # - from:
     #   - master_table
        # - raw:
        #   - select employee_group.description as employee_group, count(employee.employee_group_id) as count from employee left join employee_group on employee_group.id = employee.employee_group_id group by employee_group.description;
events:
  onInitAsync:
    - id: fetch_pie_chart_data
      type: Request
      params:
        - get_pie_chart_data
properties:
  title: Pie Chart
layout:
  contentJustify: center
blocks:
  - id: content_card
    type: Card
    layout:
      size: 800
      contentGutter: 16
    blocks:
      - id: page_heading
        type: Title
        properties:
          content: Department Performances
          level: 3
      - id: my_chart
        type: AmChartsPie
        properties:
          height: 400 # The default height is 500px.
          data: # This will usually be data from a request, so use the  _request operator.
            _request: get_pie_chart_data
          series:
            - type: PieSeries
              dataFields:
                category: master_label
                value: value
```

**Reply by awsomedesigner** [reply]
@muzivusa I would like to suggest one thing.

Try with just a single page and try to get all database table values on the page then play with custom blocks.

**Reply by ghost** [reply]
PUT THIS BS INSIDE A CODE BLOCK PLEASE.
I can not understand anything, does anybody do understand? We can not edit it either .... GOD

**Reply by Gervwyk** [reply]
Thanks @amhoba, I've edited the comment for you so should now be more readable.

**Reply by Gervwyk** [reply]
Hi @muzivusa 

Please remember to add three backticks before and after you paste code to create a code block, which makes it all readable.

Just looking at you issue here, try:
```yaml
     - id: my_chart
        type: AmChartsPie
        properties:
          height: 400 # The default height is 500px.
          data: # This will usually be data from a request, so use the  _request operator.
            _log:
              _request: get_pie_chart_data
          series:
            - type: PieSeries
              dataFields:
                category: master_label
                value: value
```
and inspect the browser console to see the output for `_request: get_pie_chart_data`. I guessing your response data will be inside od the `data` key for this knex response. Try changing that line to:  `_request: get_pie_chart_data.data` to pass the data array to the chart data property.

Also, side note, you probably copied from an example here, but the ECharts bocks is much easier to work with than AmCharts, so unless you want AmCharts it's best to switch to ECharts. See: https://docs.lowdefy.com/EChart

**Reply by muzivusa** [reply]
hey thanks , I'm sorted now , its working

**Comment by 13316090972** [comment]
Here are two KnexBuilder examples below:
```
- id: getData
  type: KnexBuilder
  connectionId: mysql
  properties:
#raw: select * from t_my_table where good_id = xxx
    tableName: t_my_table
    query:
      - select:
          - "*"
      - where:
          - goods_id
          - _state: goods.id
```
          
```
- id: updateData
  type: KnexBuilder
  connectionId: mysql
#raw: update t_form_value set value = xxx where id = yyy and app_id = zzz
  properties:
    tableName: t_form_value
    query:
      - update:
          - value:
              _state: value
      - where:
          - id
          - _state: goods.id
      - andWhere:
          - app_id
          - _global: app_id
```

**Comment by vicam001** [comment, marked as answer]
Hi @awsomedesigner , I hope this hint on how I work with a PostgreSQL connection might help you. I am quite new into Lowdefy so still in the process of learning a lot from the forum and the existing documentation, I look forward to having a growing community here :) .

1) In the ```lowdefy.yaml``` file, add the connection :

```
lowdefy: 3.23.3
...
connections:
  - id: aws_rds_postgres
    type: Knex
    properties:
      client: postgres
      connection:
        _secret: PG_CONNECTION_STRING
      version: '7.2'
      searchPath: 'public'

```

* I had to add ```public```  (the schema of the database I'm using) in the ```searchPath``` for it to work.

2) Make sure you add the secret in the ```.env``` file:

```
LOWDEFY_SECRET_PG_CONNECTION_STRING = postgresql://<user_name>:<password<@<host>:<port>/<db_name>
```

* Replace <user_name>, <password> ... with your own values

3) Within your Lowdefy project folder, create a subfolder ```requests``` (this is just a way to organize the SQL queries in a way that can be easily re-used)


4) Add there a new file (e.g. ```get_contact.yaml```)

```
id: get_contact
type: KnexRaw
connectionId: aws_rds_postgres
properties:
  query: 
    SELECT * FROM public.contacts WHERE C.id= :contact_id
  parameters:
    contact_id:
        _if_none:
          - _input: contact_id
          - _url_query: id

```
* In this case I am trying to retrieve just one Contact, by its id, which I take from either the _input or the _url_query

5) On a given page (e.g. ```get_contact.yaml```) I declare the request as follows an I call the query through the ```onEnter``` event:

```
id: edit-contact
type: PageHeaderMenu

...

requests:
  # Requests and actions are written in the requests/actions directories and referenced to make the files easier to read.

  - _ref: requests/get_contact.yaml


...

events:
  onEnter:
    # Redirect back to the page with the list of records if no record is selected (either as input or as url query)
    - id: redirect
      type: Link
      skip:
        _or:
          - _not:
              _eq:
                - _input: contact_id
                - null
          - _not:
              _eq:
                - _url_query: id
                - null
      params: contacts
    # Fetch the record
    - id: get_contact
      type: Request
      skip:
        _and:
          - _eq:
            - _input: contact_id
            - null
          - _eq:
            - _url_query: id
            - null
      params: get_contact
    # Set the contact data to state to populate the input block values.
    - id: set_contact
      type: SetState
      skip:
        _and:
          - _eq:
            - _input: contact_id
            - null
          - _eq:
            - _url_query: id
            - null
      params:
        _request: get_contact.rows.0

```

* Note that in order to actually get the row of data  (or rows if it where a query such as get_contacts, for example) I need to add the ```.rows``` and then ```.0``` to get the one value within the array.

* By following this, in case you have text inputs whose id is the same as the columns fetched in the query, they will be filled in.
