### DISCUSSION TITLE
How to join the strings on aggrid cell?

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1183] [Questions and Help]
```
                - headerName: product
                  field: product
                  cellStyle: { textDecoration: underline, color: blue }
                  valueFormatter:
                    _function:
                      __nunjucks:

                        template: |
                          {{ cellValue| join(',')}}
                        on:
                          __log:
                            cellValue:
                              __args: 0.value
```
error reports:
![image](https://user-images.githubusercontent.com/56707831/165671678-93c9b0cc-a2a6-4d6a-8c58-496c3da1d09f.png)

**Comment by Gervwyk** [comment]
I think it might be because of the missing white space in your nunjucks template, not sure. Try:
```
template: "{{ cellValue | join(',') }}"
```

**Reply by Gervwyk** [reply]
I also think that if you give a list of values to an ag-grid column field it automatically prints the comma separated values. Just check.

**Comment by 13316090972** [comment]
The error remains even after i add white space.
```
                - headerName: product
                  field: product
                  cellStyle: { textDecoration: underline, color: blue }
                  valueFormatter:
                    _function:
                      __nunjucks:
                        template: "{{ cellValue | join(',') }}"
                        on:
                          __log:
                            cellValue:
                              __args: 0.value
```
![image](https://user-images.githubusercontent.com/56707831/165704350-6620b094-e918-4e80-9368-4109453eb203.png)

**Reply by Gervwyk** [reply]
For this data structure, try: 
```yaml
- headerName: product
  field: product
  cellStyle: { textDecoration: underline, color: blue }
  valueFormatter:
    _function:
      __array.map:
        on: 
          __args: 0.value
        callback:
          __function:
            ___args: 0.name
``` 

Edit: Sorry the nunjucks example I gave was incorrect, nunjucks `join` will throw if you do not pass it an array. You can also do this using nunjucks but be sure to pass an array of strings to the `join` method.

**Comment by 13316090972** [comment]
Sorry, I don't get [your idea ](https://github.com/lowdefy/lowdefy/discussions/1183#discussioncomment-2651867)exactly.Do you mean just define the aggrid column field and give a string array ['shoe','box','pen'] and the aggrid will automatically print 'shoe,box,pen'?
I try it:
```
# set state
            table:
              - order:
                  id: B0001
                  count: 150
                  date: "2022-01-01"
                  delivery: "2022-01-01"
                customer:
                  name: 张总
                  id: C0001
                product:
                  -  name: shoe
                  -  name: box
                  -  name: pen
                  ......
# aggrid column field definination
                - headerName: product name
                  field: product.name
```
And the display of aggrid column is empty:
![image](https://user-images.githubusercontent.com/56707831/165706620-6174da7a-0b82-486d-ba23-81cdd6d0afeb.png)

**Reply by Gervwyk** [reply]
More like:
```
# set state
            table:
              - order:
                  id: B0001
                  count: 150
                  date: "2022-01-01"
                  delivery: "2022-01-01"
                customer:
                  name: 张总
                  id: C0001
                product:
                  - shoe
                  - box
                  - pen
                  ......
# aggrid column field definination
                - headerName: product name
                  field: product
```

**Reply by 13316090972** [reply]
Yes, it works when the product is a array of string in my example above.But in my actually business case ,  the product will be a array of object:
```
              product:
                  - name: shoe
                    count: 20
                  - name: box
                    count: 10
                  - name: pen
                    count: 30
          ......
             - headerName: products
               field: product                          #aggrid column display [object Object, object Object, object Object]
               #field: product.name                aggrid column display empty
```
Can you give some advice in this case?
