### DISCUSSION TITLE
About _date operator

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1194] [Questions and Help]
Hi, I want to display the date in lowdefy. If the date value is `null`, it will not be displayed. I used `_ date`  and  `_ if_ none`operator, `_ if_ none` determines whether the value is null. If true, it will not be displayed. If false, it will display the date. But it is also executed when the value is null `_date` operator does not report an error. How can I solve it?
code:
```yaml
  - id: init
    type: SetState
    date: null
  - id: setRecord
    type: SetState
    params:
      date: 
          _if_none:
            - _date:
                _state: date
            - null
```
error:
![image](https://user-images.githubusercontent.com/72787010/168018920-603c7d74-5388-4cb1-a395-f2e9d1c51a2c.png)

**Comment by HFolkertH** [comment]
I think the “ - _date:   “ should not be there

**Reply by Gervwyk** [reply]
Agree, you need to have: 
```yaml
  - id: init
    type: SetState
    # date: null # this is not valid.. why is this here? then you can just remove this `SetState` also
  - id: setRecord
    type: SetState
    params:
      date: 
          _if_none:
            - _state: date
            - null
 ```
