### DISCUSSION TITLE
Show database value in selector

### DISCUSSION THREAD

**Discussion by awsomedesigner** [lowdefy/lowdefy#1195] [Questions and Help] [answered]
Hi All

I am working on one app which have MySQL database.
I want to show database value in selector dropdown.

my request file code 
```
id: chainmaster_selector_db 
type: KnexBuilder  
connectionId: userlist  
properties:  
    query:  
      - select:  
        - '*'  
      - from:  
        - chainmaster  
 ```
        
 My events code
 
 ```
events:
  onEnterAsync:
    - id: chainmaster-selector-request # Fetch the request data before the page renders in order to populate Chain master dropdown
      type: Request
      params: chainmaster_selector_db
  onEnter:
    - id: chainmaster-selector-request # Fetch the request data before the page renders in order to populate Chain master dropdown
      type: Request
      params: chainmaster_selector_db
    - id: set_chain
      type: SetState
      params:
        _log:
          chain_list:
              _request: chainmaster_selector_db
```
              
My Selector code

```
- id: chain_selector 
 type: Selector
              visible: # Test if block should be visible to the user
                _eq: # Equals operator
                  - _state: CheckToken # Get the ticket_type value from state.
                  - true
              properties: 
                title: Select Chain
                placeholder: Select Chain
                options:
                  _log:
                    - _request: chainmaster_selector_db
```
                    
When I log my request data in the console then it shows below output

```
{
    "chain_list": [
        {
            "id": 1,
            "chain_name": "BTC",
            "created_at": "2022-05-11T04:57:33.000Z"
        },
        {
            "id": 2,
            "chain_name": "Blockchain",
            "created_at": "2022-05-11T05:30:43.000Z"
        }
    ]
}
```

I want to show chain name as label and id as the value of the label

I tried _map but it's not working for me.

Can you please help me out from this?
