### DISCUSSION TITLE
How to use dark theme in EChart and amchart?

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1218] [Questions and Help]
How to use dark theme in EChart and amchart?
![image](https://user-images.githubusercontent.com/72787010/171083499-5227bc58-28c6-4dce-8a23-3dccabf0a0d4.png)

**Comment by SamTolmay** [comment]
Hi @xiaoxiji1234 

You can use the `theme` property.

A easy way to do this is to use the EChart theme builder, and to export a JSON file - https://echarts.apache.org/en/theme-builder.html

You can then use a `_ref` operator to reference the  theme file, like this:
```yaml
id: chart
type: EChart
properties:
  theme:
    _ref: echart_theme.json
  option:
    xAxis:
      type: category
      data:
        - A
        - B
        - C
    yAxis:
      type: value
    series:
      - type: bar
        data:
          - 150
          - 230
          - 224
```

The theme file will look something like:
```json5
{
  "color": [
      "#9b8bba",
      "#e098c7",
      "#8fd3e8",
      "#71669e",
      "#cc70af",
      "#7cb4cc"
  ],
  "backgroundColor": "rgba(91,92,110,1)",
  // ...
}
```
