### DISCUSSION TITLE
question about mixed object including _ref and normal property

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1226] [Questions and Help] [answered]
I want a fixed object
- some properties comes from _ref another file 
- some properties I write them down directly

But the second part of properties are missing.

```
#lowdefy.yaml
lowdefy: 3.23.3
name: Lowdefy starter

pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    areas:
      content:
        justify: center
        blocks:
          - id: content_card
            type: Card
            style:
              maxWidth: 800
            blocks:
              - id: content
                type: Result
                properties:
                  title: Welcome to your Lowdefy app
                  subTitle: We are excited to see what you are going to build
                  icon:
                    name: HeartTwoTone
                    color: '#f00'
                areas:
                  extra:
                    blocks:
                      - _ref:
                          path: button.yaml
                          vars:
                            _ref: pro.yaml
                            title: Let's build something
```

```
#button.yaml
id: docs_button
type: Button
properties:
  size: 
    _var: size
  color: 
    _var: color
  title:
    _var: title
```

```
#prop.yaml
size: large
color: '#1890ff'
```
![image](https://user-images.githubusercontent.com/56707831/172142906-d657514f-4f0e-44fa-a704-5c32499fef16.png)

**Comment by 13316090972** [comment]
```
#.lowdefy/build/pages/welcome.json 
"areas": {
                    "extra": {
                      "blocks": [
                        {
                          "id": "block:welcome:docs_button",
                          "type": "Button",
                          "properties": {
                            "size": "large",
                            "color": "#1890ff",
                            "title": null
                          },
```

**Comment by SamTolmay** [comment]
Hi @13316090972 

You can use the `_object.assign` operator to merge two objects. Something like this might work:
```yaml
_ref:
  path: button.yaml
  vars:
    _ref:
      path: prop.yaml
      vars:
        extra_props:
          title: Let's build something
```

```yaml
#prop.yaml
_object.assign:
  - size: large
    color: '#1890ff'
  - _var:
      name: extra_props
      default: {}
```

**Reply by 13316090972** [reply]
Can _object operator work at build time? The [operators doc](https://docs.lowdefy.com/operators) says only _ref and _var can work at build time. The build result is:
```
# .lowdefy/build/pages/welcome.json
"areas": {
                    "extra": {
                      "blocks": [
                        {
                          "id": "block:welcome:docs_button",
                          "type": "Button",
                          "properties": {
                            "size": null,
                            "color": null,
                            "title": null
                          },
```

**Reply by SamTolmay** [reply]
Sorry, the answer I provided was incorrect.

One solution that works is:
```yaml
_ref:
  path: button.yaml
  vars:
    properties:
      _ref:
        path: prop.yaml
        vars:
          extra_props:
            title: Let's build something
```

```yaml
# button.yaml
id: docs_button
type: Button
properties:
  _var: properties
```

```yaml
# prop.yaml
_object.assign:
  - size: large
    color: '#1890ff'
  - _var:
      name: extra_props
      default: {}
```

However, you can't add extra properties in `button.yaml`, since you are passing a whole properties object as a var, so this won't work for other similar use cases.

The `_object.assign` will only be evaluated at runtime. We introduced build time operators in version 4 to fix that issue. You would just convert the `_object.assign` to `_build.object.assign`, and then the operator will be evaluated at build time.

**Comment by 13316090972** [comment]
Thanks sam for your patience, It works in this simple case. 
But delaying from build time to runtime ,it's somewhat troublesome in some cases,for example, if I want to change the button's id or even block type according to extra_props.
In version 3,the other solution maybe transformers/addVars.js,which add extra_props to the _ref vars.

**Comment by 13316090972** [comment, marked as answer]
transformers/addVars.js can't work also. Do you please to give me some advices besides waiting for version 4?
```YAML
_ref:
  path: button.yaml.njk
  transformer: transformers/addVars.js
  vars:
    _ref: prop.yaml
```
```YAML
# prop.yaml
size: large
color: '#1890ff'
```
```YAML
# button.yaml.njk
id: {{id| default ('NOT_NULL')}}
type: Button
properties:
  size: 
    _var: size
  color: 
    _var: color
```
```JavaScript
// transformers/addVars.js
function addVars(page, vars) {
  console.log(vars);
  const extra_props = {
    id: "my_id",
  };
  const extra_vars = Object.assign(extra_props, vars);
  console.log(extra_vars);
  // return (page, extra_vars); //wrong as "Block type is not defined at my_id on page welcome"
  // return extra_vars; //wrong as "Block type is not defined at my_id on page welcome"
  return page;                      //the only right way,but i can't add the extra_props
}
module.exports = addVars;
```
