### DISCUSSION TITLE
Error when deploying with Node.js or docker and with OpenID connection

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1228] [Questions and Help] [answered]
I wrote a lowdefy starter app with openid connetion as below,and complete the configuration for my app in Keycloak.
```YAML
lowdefy: 3.23.3
name: Lowdefy starter
config:
  homePageId: loginPage
  auth:
    openId:
      logoutRedirectUri: |
        http://xxx.xxx.xxx.xxx:9080/auth/realms/diclap/protocol/openid-connect/logout?redirect_uri=http://xxx.xxx.xxx.xxx:3000/loginPage
    pages:
      protected: true
      public:
        - loginPage
        - "404"
pages:
  - _ref: login.yaml
  - id: welcome
 # blocks in welcome page
```
### Run on dev command

1. `npx lowdefy@latest dev`
2. visit port 3000
3. browser jump to keycloak login page
![image](https://user-images.githubusercontent.com/56707831/172786749-9f822c2f-b111-419c-b2ad-c9527f47e266.png)

4. user enter username and password then return to port 3000 
5. the welcome page can be visited.
![image](https://user-images.githubusercontent.com/56707831/172786961-1fe04d66-cf87-4e93-b94b-396578885cf2.png)
### Deploy with Node.js

1. follow the steps in https://docs.lowdefy.com/node-server
![image](https://user-images.githubusercontent.com/56707831/172787866-791762b2-12e2-4047-b68c-60d55458e367.png)

2. visit port 3000
3. browser return Error
![image](https://user-images.githubusercontent.com/56707831/172788247-35d875b2-05ec-4c48-8936-8e6786ea7a27.png)
### Deploy with docker
1. follow the steps in https://github.com/lowdefy/lowdefy-example-docker/tree/main/config-in-volume and https://github.com/panva/node-openid-client/discussions/440
```shell
docker run -d \
  -p 3000:3000 \
  --name lowdefy \
  --mount type=volume,source=lowdefy-build,destination=/home/node/lowdefy/build \
  --env-file ./.env \
  lowdefy/lowdefy:latest
  
docker cp ./.lowdefy/build lowdefy:/home/node/lowdefy
```
![image](https://user-images.githubusercontent.com/56707831/172789691-ca87cd9c-2605-41c6-806d-d35bec6c0450.png)

2. visit port 3000
3. browser return Error
![image](https://user-images.githubusercontent.com/56707831/172790068-3e29b268-3d6b-4279-a46d-b228dda76386.png)
