### DISCUSSION TITLE
Setting default selection for a Selector block

### DISCUSSION THREAD

**Discussion by iron3oxide** [lowdefy/lowdefy#1229] [Questions and Help] [answered]
I want to automatically select the first (or any other) of the given options in different Selector/MultipleSelector blocks. Unfortunately I can't find an obvious way to do this in the docs. Am I overlooking something?

**Comment by Gervwyk** [comment, marked as answer]
Hi @iron3oxide 

You need to set the value to state and the selector will change, for example:
```yaml
...
events:
  onMount:
    - id: set_selector
      type: SetState
      params:
        foo_selector: value-one
...
```
The above action will set the value to `foo_selector` in state, so a selector with id of `foo_seletor` will have its selection updated. For a multiple select, this value will be an array.
