### DISCUSSION TITLE
Reusing blocks without them sharing their state

### DISCUSSION THREAD

**Discussion by iron3oxide** [lowdefy/lowdefy#1230] [Questions and Help] [answered]
I want to reuse a card in a modal which I previously used in a tab. To achieve that, I "outsourced" the card into its own yaml file and referenced it in both the tab and the modal. Unfortunately when using the resulting app, the two cards seem to share their state, meaning everything I enter in the modal card is also displayed in the tab card. 

Also, almost all the selectors in the modal card don't show their options when clicked, but some do. This may be related to the shared state or a separate issue, just wanted to mention it.

What can I do to make the two cards merely copies of each other?

**Comment by Gervwyk** [comment, marked as answer]
Hi @iron3oxide 

They are designed to share state on the same page, so if there is an issue related to their options it is most likely something else, if you share parts of the config I can have a look.. 

In terms of reusing page element using `_ref` we often do that, and having one state object simplifies everything a lot. You can always use dot notation to create sub-objects in state. Together with the `.yaml.njk` file format you can easily use vars to create unique ids for each field. For example:
```yaml
# my_card.yaml.njk
...
- id: {{ foo }}.fieldname
...

# page.yaml
... 
- _ref:
    path: my_card.yaml.njk
    vars:
      foo: team
- _ref:
    path: my_card.yaml.njk
    vars:
      foo: profile
``` 

Hope this example makes sense?

**Reply by iron3oxide** [reply]
Thanks again for the quick reply. Your example does make sense, but I wonder how I could design a card template that doesn't require me to pass a parameter for each of its blocks. I tried making the card.yaml file a .yaml.njk file and passing it a single "parent" parameter from which the block ids are deducted, but failed miserably. The error message ( "TypeError: Cannot read properties of null (reading 'id')" ) wasn't particularly helpful either. Is there any way to do this? The card contains about 10 blocks, so passing a parameter for each feels cumbersome.

Regarding the options problem: I'd like to wait for the results of the templating adventure first, maybe that'll resolve it.

**Reply by Gervwyk** [reply]
The example above can be used for this. Let me write it out more:
```yaml

# my_card.yaml.njk
id: {{ obj }}.card
type: Card
blocks:
  - id: {{ obj }}.name
    type: TextInput
  - id: {{ obj }}.favorites
    type: MultipleSelector
    properties:
      options:
        - A
        - B
...

# page.yaml
... 
id: page
type: PageHeaderMenu
blocks:
  - _ref:
      path: my_card.yaml.njk
      vars:
        obj: team
  - _ref:
      path: my_card.yaml.njk
      vars:
        obj: profile

```
The error you are seeing is because on of your blocks is undefined. Share that part of your config and I can take a look?
