### DISCUSSION TITLE
Calling pushItem on a ControlledList onMount fails

### DISCUSSION THREAD

**Discussion by iron3oxide** [lowdefy/lowdefy#1231] [Questions and Help]
I want to build an expandable filter box list for a CRUD app, where one can add as many filter boxes (consisting of search column, search operator and search input) to a ControlledList as one likes. The filter boxes are created using a template, the config is as follows:
```
...
- id: filter_list
  type: ControlledList
  blocks:
    - _ref:
        path: components/templates/filter_box.yaml.njk
        vars:
          parent: filter_list.$
...
```

To improve UX, I want to add the first filter box when the card the whole thing is confined in is mounted. I also want to set the search column and the search operator to default values (I learned how to do this in #1229, it worked) and autosize the table columns. This is the config:
```
...
events:
  onMountAsync:
    - id: add_first_filter_box
      type: CallMethod
      params:
        blockId: filter_list
        method: pushItem

    - id: set_selectors
      type: SetState
      params:
        filter_list.$.column_selector: Nachname
        filter_list.$.operator_selector: enthält

    - id: auto_size
      type: CallMethod
      params:
        blockId: table
        method: sizeColumnsToFit
```
Unfortunately I am greeted with the following error message when visiting the successfully built app:
```
Failed to call method "pushItem" on block "filter_list". Check if "pushItem" is a valid block method for block "filter_list". Received "{"blockId":"filter_list","method":"pushItem"}".
```

Is this a bug or am I doing something wrong? filter_list should definitely provide the method pushItem, shouldn't it?

**Comment by iron3oxide** [comment]
Addendum: of course it should be onInitAsync instead of onMountAsync, I don't want to add a filter box every time I reload the page.

**Comment by SamTolmay** [comment]
Hi @iron3oxide 

I am not sure wht the `pushItem` method isn't working.

But you can just use a `SetState` action to initialise the list. Like this:
```yaml
- id: set_selectors
  type: SetState
  params:
    filter_list:
      - column_selector: Nachname
        operator_selector: enthält
```

**Reply by iron3oxide** [reply]
First of all: thanks for your quick reply, I really appreciate you guys taking the time to do this. 

Regarding my problem: The issue is that I first need to add an initial filter box to the filter_list before I can set the selectors it contains. I don't know if your config example is attempting to achieve that, but I think it only does the second part (at least that is the outcome I observe).

Now that I think about what I'm trying to do after a good nights sleep, it may be better design to simply put the default filter box outside/above the filter_list and use the filter_list to add additional filter boxes. I'm still curious though if/how my initial design would have worked.

**Comment by Gervwyk** [comment]
Could you share the content or sample content of filter_box.yaml.njk . For lists your block ids need to be setup correctly.

**Reply by iron3oxide** [reply]
```
id: {{ parent }}.filter_box
type: Box
layout:
  contentGutter: 10
blocks:
  - id: {{ parent }}.column_selector
    type: Selector
    layout:
      span: 8
    properties:
      allowClear: false
      placeholder: Suchkriterium
      options:
        - Nachname
        - Vorname
        - Geburtsdatum
        - Nationalität
        - Geschlecht
        - ID
      label:
        disabled: true

  - id: {{ parent }}.operator_selector
    type: Selector
    layout:
      span: 8
    properties:
      allowClear: false
      showSearch: false
      placeholder: Operator
      options:
        - enthält
        - ist gleich
        - enthält nicht
        - ist ungleich
      label:
        disabled: true

  - id: {{ parent }}.search_input
    type: TextInput
    layout:
      span: 8
    properties:
      placeholder: Suchbegriff
      autoFocus: true
      allowClear: true
      label:
        disabled: true
```
