### DISCUSSION TITLE
Ability to use a Button as a Switch / Calendar widget

### DISCUSSION THREAD

**Discussion by iron3oxide** [lowdefy/lowdefy#1234] [Ideas and feature requests]
A little bit of background: I am building a calendar widget and would love to use circle buttons as my subwidgets representing the days. By toggling such a button, a user would add/delete an event from the database. The button color would be determined by the type of event one previously selected.

Problem: there seems to be no easy way to do this, as Buttons don't seem to have switch functionality. I would prefer not to use a Switch or CheckboxSwitch either, as those wouldn't look nearly as good.

Possible solutions:

- a full blown calendar widget
- a new "ButtonSwitch" block

What do you think of this? Is there an easy way I am overlooking?

**Comment by Gervwyk** [comment]
Hi @iron3oxide 

You can switch any button property using state, so if you use `SetState` action in the `onClick` event, then you should be able to toggle any property. Hope this helps..

**Reply by iron3oxide** [reply]
I did not know of the _if operator... this is the best I could come up with for my button template and it fails silently. What's missing/wrong? Sorry for asking you to help me debug again btw, I wish there were another way.
```
id: month{{ month }}.day{{ day }}
type: Button
layout:
  span: 2
properties:
  ghost: true
  shape: circle
  title: {{ day }}

events:
  onClick:
    - id: toggle_button
      type: SetState
      params:
        month{{ month }}.day{{ day }}:
          ghost:
            _if:
              test:
                _eq:
                  - _state: month{{ month }}.day{{ day }}.ghost
                  - false
              then: true
              else: false
```

**Reply by iron3oxide** [reply]
Update: Thanks to #1182 I could verify that my config actually manipulates the state object and both "ghost: true" and "ghost: false" get set correctly. The corresponding buttons however remain in ghost mode either way. I then tried it with 
".properties.ghost" to see if I simply got the format wrong, but the result remained...

**Reply by Gervwyk** [reply]
Try the following:
```yaml
id: month{{ month }}.day{{ day }}
type: Button
layout:
  span: 2
properties:
  ghost:
    _state: month{{ month }}.day{{ day }}.ghost
  shape: circle
  title: {{ day }}
events:
  onClick:
    - id: toggle_button
      type: SetState
      params:
        month{{ month }}.day{{ day }}.ghost:
         _not:
           _state: month{{ month }}.day{{ day }}.ghost
```
I assume `month` and `day` are vars which is passed into your `njk` template?
You might also want to add an `onMount` to init the state with your data.. How are you modelling your data in state for this?

btw: The _if is redundant since _eq returns true or false.
