### DISCUSSION TITLE
How to develop V4 plugins.

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1251] [Questions and Help] [answered]
In lowdefy 3.23.2 , blocks' metadata can be built in `lowdefy-main/packages/blocks/xxxx` directory,while modifying `meta.moduleFederation.remoteEntryUrl` in `webpack.prod.js`,like this:
```javascript
const addRemoteEntryUrl = (content, absoluteFrom) => {
  const scope = sanitizeName(packageJson.name);
  const meta = JSON.parse(content);
  // if no moduleFederation info is provided, default to unpkg
  if (!meta.moduleFederation) {
    meta.moduleFederation = {
      module: path.basename(absoluteFrom, '.json'),
      scope,
      version: packageJson.version,
      // unpkg can result in a unreliable module federation experience.
      // Deploy you block to your preferred static file host and update the remoteEntryUr
l.
      //remoteEntryUrl: `https://blocks-cdn.lowdefy.com/v${packageJson.version}/blocks-ag
grid/remoteEntry.js`,
       remoteEntryUrl: `${url}/blocks-antd/remoteEntry.js`,
    };
  }
  return JSON.stringify(meta);
};
```

I'm glad to see that lowdefy was upgrated to version 4.0.0-alpha.17 last week.But the blocks' metadata seems to be moved to `lowdefy-main/packages/plugins/blocks` and change from webpack to swc, which is unfamiliar to me.
Would you tell me how to build my cdn in new version?

**Comment by SamTolmay** [comment, marked as answer]
Hi @13316090972


In version 4 we have replaced the Module Federation custom blocks with a plugin system, which can be used to write your own blocks, connections, operators and actions. These are included into the server during the build process, so you no longer need to host your blocks on a separate server, which is  great for enterprise firewalls. You can publish your plugins to npm and use in your app, or you can simply import plugins from local files.

We haven't documented the plugin system yet, but I will use this explanation as the base for that documentation, so please let me know if anything is unclear or if I missed something.

A plugin needs to be a npm package. The package is installed into the server using npm or yarn, so any of the supported protocols like `file:` or `git:` should work (https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies). We copy the `plugins` folder in your config into the server, so you can use relative paths there in the package specifier if you place your plugins in the `plugins` folder.

I have created an example repository you can have a look at:
https://github.com/lowdefy/lowdefy-example-plugins

You can have a look at the official Lowdefy plugins here:
https://github.com/lowdefy/lowdefy/tree/main/packages/plugins
The official plugins are built using swc, but is not really necessary, as the Lowdefy server is built with webpack, so it is simpler not to include a build step.


To import the plugin into your app, you can add the following to the root of your lowdefy config (replacing the `types` array):

```yaml
plugins:
  - name: 'local-plugin'
    version: 'file:./plugins/local-plugin'
  - name: 'npm-plugin'
    version: 1.0.0
```

You can then use all of the types declared by the plugin as normal types.

The plugin `package,json` file should look like this:
```json
{
  "name": "plugin-name",
  "version": "1.0.0",
  "type": "module",
  "exports": {
    "./auth/callbacks": "./auth/callbacks.js",
    "./auth/events": "./auth/callbacks.js",
    "./auth/providers": "./auth/providers.js",
    "./blocks": "./blocks.js",
    "./connections": "./connections.js",
    "./operators/build": "./operatorsBuild.js",
    "./operators/client": "./operatorsClient.js",
    "./operators/server": "./operatorsServer.js",
    "./types": "./types.js"
  },
  "files": [
    "*"
  ],
  "dependencies": {}
}
```

You can change your folder structure in your package, but then you need to change the `exports` config to match your file structure.

You should have a `types.js` file, which exports all the types declared by the package. This is used so that the build knows which types can be used from that plugin.

The `types.js` file should look like

```js
export default {
  actions: ['PluginAction'],
  blocks: ['Block'],
  connections: ['Connection'],
  requests: ['Request'],
  operators: {
    client: ['_build_operator', '_shared_operator'],
    client: ['_client_operator', '_shared_operator'],
    server: ['_server_operator', '_shared_operator'],
  },
};
```

The plugin should also have a file that exports all the types as named exports. So for example, you should have a `blocks.js`:
```js
export { default as Block } from './blocks/Block/Block.js';
```

The block file also needs to change slightly, an example block is
```js
import React from 'react';
import { blockDefaultProps } from '@lowdefy/block-utils';

const Box = ({ blockId, content, events, methods, properties }) => (
  <div
    id={blockId}
    data-testid={blockId}
    onClick={() => methods.triggerEvent({ name: 'onClick' })}
    className={methods.makeCssClass([
      { outline: 'none', cursor: events.onClick && 'pointer' },
      properties.style,
    ])}
  >
    {properties.content || (content.content && content.content())}
  </div>
);

Box.defaultProps = blockDefaultProps;
Box.meta = {
  category: 'container', // one of 'container', 'display', 'input' or 'list'
  icons: [],
  styles: [],
};
```

**Comment by 13316090972** [comment]
It sounds a great advantage and have much more convenient to the developer.
I'll try it tomorrow.

**Comment by 13316090972** [comment]
I followed the example repository https://github.com/lowdefy/lowdefy-example-plugins this afternoon.There's a bug in plugins.version of [lowdefy.yaml](https://github.com/lowdefy/lowdefy-example-plugins/lowdefy.yaml):
```yaml
lowdefy: 4.0.0-alpha.17 # Please check for latest Lowdefy version.
license: MIT

plugins:
  - name: 'plugin-name'
#    version: 'file:./plugin-name'
    version: 'file:./plugins/plugin-name'
pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    areas:
      content:
        justify: center
        blocks:
          - id: Hello
            type: Button
            events:
              onClick:
                - id: msg
                  type: SetState
                  params:
                    _log:
                      content: Clicked
```
the result looks like following, and All network requests refered to http://localhost:3000 :
![image](https://user-images.githubusercontent.com/56707831/176428632-0a011949-625a-4dd4-9f95-9eca06694464.png)

**But there are some points should be impoved:**

1. If i change the content of lowdefy.yaml under the dev cli,It will lead to rebuilding and then fail.

![image](https://user-images.githubusercontent.com/56707831/176428131-6bfdd7b7-805f-476b-bf7c-c6218095c30d.png)
We can fix it by quit the dev cli and build(or dev) it again .
2. Message action seems to be discard in v4,But there's no v4 document to metion it.
3. It spend me about 10 minutes to fetch 4.0.0-alpha.17 package, far too slow.
