### DISCUSSION TITLE
How to change the lable font color of textInput ?

### DISCUSSION THREAD

**Discussion by 15602322852** [lowdefy/lowdefy#1281] [Questions and Help] [answered]
How to change the lable font color of textInput ?

**Comment by Gervwyk** [comment, marked as answer]
Hi @15602322852 

You can set html to the label like so:
```yaml
    id: input
    type: TextInput
    properties:
      title: <span style='color: red;'>My Input</span>
```
Does this help?
