### DISCUSSION TITLE
How to reference the Gauge chart?

### DISCUSSION THREAD

**Discussion by 15602322852** [lowdefy/lowdefy#1299] [Questions and Help] [answered]
How to reference the Gauge chart?

**Comment by JohannMoller** [comment, marked as answer]
Hi @15602322852,

You can create a gauge chart with the EChart block by using a series with type 'gauge'. Here is a simple example (one of the examples on their website https://echarts.apache.org/examples/en/editor.html?c=gauge-simple):

```yaml
id: echart_gauge
type: EChart
properties:
  option:
    tooltip:
      formatter: '{a} <br/>{b} : {c}%'
    series:
      - type: gauge
        name: Pressure
        progress:
          show: true
        detail:
          valueAnimation: true,
          formatter: '{value}%'
        data:
          - value: 50
            name: SCORE
```

This config will result in this chart:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/35911443/180147500-e34cd6b4-8434-4d89-96d6-d907a0ad9d99.png">

Is that what you were looking for?

PS: You can find the documentation for the gauge chart over here https://echarts.apache.org/en/option.html#series-gauge
