### DISCUSSION TITLE
how to generates an array of the specified length

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1313] [Questions and Help] [answered]
In some case, we need to generate an array with specified length. For example, we split a big order to serveral small work jobs.
But I can't get help from _array and _mgl operation documents.

**Comment by Gervwyk** [comment]
Hi @13316090972 
This should be possible, can you share a simplified config example of what you have attempted?

**Comment by 13316090972** [comment]
![image](https://user-images.githubusercontent.com/56707831/181729812-e95d3adf-9d44-48c6-b5d5-efedfdc6ebfd.png)
For example,I have an order which needs 1900 products.Which is too big to do it on the same machine .So I need to split it to 8 or 10 jobs.
I temporarily implement it by ControlledList, one click to increase the length of job list by one.

**Comment by 13316090972** [comment]
If I can generates an array of length 8, I could dislplay 8 jobs which have 1900/8 products instantly.

**Reply by Gervwyk** [reply]
ok, so you'd like to work through them 8 at a time? Until the entire list has been processed?

**Reply by 13316090972** [reply]
yeah.The user input the length of job list,e.g. 8, the app displays 8 items at a time ,with the initial count (1900/8), the user can adjust each count and then submit.

**Comment by 13316090972** [comment, marked as answer]
I did it with _nunjucks and range() and _json.parse.
![image](https://user-images.githubusercontent.com/56707831/182036786-5191cf10-7204-451a-9ab5-eaa7eeaf543b.png)

![image](https://user-images.githubusercontent.com/56707831/182037098-ac2cfee2-84f7-4077-b713-c6614f5ff89c.png)
Here's the code.
```YAML

lowdefy: 3.23.3
name: Lowdefy starter
global:
  total: 1900
pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    areas:
      content:
        justify: center
        blocks:
          - id: order size
            type: Descriptions
            properties:
              items:
                - label: order size
                  value:
                    _global: total
          - id: jobs_count
            type: NumberInput
            layout:
              span: 12
            properties:
              label:
                extra: how many jobs do you want to split?
                inline: true
                title: jobs count
          - id: split
            type: Button
            layout:
              span: 12
            events:
              onClick:
                - id: genArray
                  type: SetState
                  params:
                    _log:
                      jobs:
                        _json.parse:
                          _nunjucks:
                            template: |
                              [
                              {%for i in range(1,num+1)%}
                              {%if not loop.last%}
                              {"id": "job{{i}}", "size": {{total//num}}},
                              {%else%}
                              {"id": "job{{i}}", "size": {{total - (total //num) * (num - 1)}}}
                              {%endif%}
                              {%endfor%}
                              ]
                            on:
                              num:
                                _state: jobs_count
                              total:
                                _global: total
          - id: jobs
            type: List
            blocks:
              - id: jobs.$.id
                type: TextInput
                properties:
                  label:
                    title: id
                    inline: true
                  disabled: true
                layout:
                  span: 6
              - id: jobs.$.size
                type: NumberInput
                layout:
                  span: 16
                properties:
                  label:
                    title: job size
                    inline: true

          - id: button_box
            type: Box
            visible:
              _log:
                _gt:
                  - _array.length:
                      _state: jobs
                  - 0
            areas:
              content:  
                direction: row-reverse
                blocks:
                  - id: Submit
                    type: Button
                    layout:
                      span: 4
                    events:
                      onClick:
                        - id: ...
                          type: Message
                          params:
                            status: info
                            content: under construction
                  - id: Reset
                    type: Button
                    layout:
                      span: 4
                    events:
                      onClick:
                        - id: reset
                          type: Reset


```
