### DISCUSSION TITLE
_object.defineProperty docs example typo.

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1337] [Docs]
There is an error in [_object](https://docs.lowdefy.com/_object) demos:

```
_object.defineProperty:
  - firstName: Rachel
    series: Friends
  - lastName
  - descriptor:
      value: Green
```
should be
```
_object.defineProperty:
  on: firstName: Rachel
      series: Friends
  key: lastName
  descriptor:
      value: Green
```

Similar errors appear in [_yaml.stringify ](https://docs.lowdefy.com/_yaml).

**Comment by Gervwyk** [comment]
Hi @13316090972 

Thanks for bringing this to our attention. This it's simply an error in the example, it should be:
 ```yaml
_object.defineProperty:
  - firstName: Rachel
    series: Friends
  - lastName
  - value: Green
  ```
and yes, the object version, or named args version:
```yaml
_object.defineProperty:
  on: firstName: Rachel
      series: Friends
  key: lastName
  descriptor:
      value: Green
```
Will also work, we map both objects keys and arrays to function argument. So can use either or, see schema description:
```
(arguments: {
  on: object,
  key: string,
  descriptor: {
    value: any,
    configurable?: boolean,
    enumerable?: boolean,
    writable?: boolean
  }
}): any
(arguments: [
  on: object,
  key: string,
  descriptor: {
    value: any,
    configurable?: boolean,
    enumerable?: boolean,
    writable?: boolean
  }
]): any
```
