### DISCUSSION TITLE
how to clear a complex object quickly?

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1338] [Questions and Help]
I have three blocks which have a same id prefix "prop.",and I want to clear their value at the same time.How can I do ? Reset action is excluded, for there are other states which shouldn't be clear.

```yaml

lowdefy: 3.23.3
name: Lowdefy starter

pages:
  - id: welcome
    type: PageHeaderMenu
    areas:
      content:
        justify: center
        blocks:
          - id: content_card
            type: Card
            style:
              maxWidth: 800
            blocks:
              - id: prop.A
                type: TextInput
                layout:
                  span: 16
              - id: prop.B.1
                type: TextInput
                layout:
                  span: 16
              - id: prop.B.2
                type: TextInput
                layout:
                  span: 16
              - id: clear
                type: Button
                layout:
                  span: 16
                properties:
                  size: large
                  title: clear prop
                  color: '#1890ff'
                events:
                  onClick:
                    - id: reset
                      type: SetState
                      params:
                        _log:
                          prop: null
```
Btw, another question, how can i make the blocks below justified center in content_card? 
![image](https://user-images.githubusercontent.com/56707831/185760622-9101a528-6d8d-40d0-80b0-a756d2827c3e.png)

**Comment by Gervwyk** [comment]
Hi @13316090972 

Please see solution:
```yaml
lowdefy: 3.23.3
name: Lowdefy starter
pages:
  - id: welcome
    type: PageHeaderMenu
    blocks:
      - id: content_card
        type: Card
        style:
          maxWidth: 800
          margin: auto
        blocks:
          - id: content_center
            type: Box
            style:
              maxWidth: 600
              margin: auto
            layout:
              contentGutter: 16
            blocks:
              - id: prop.A
                type: TextInput
              - id: prop.B.1
                type: TextInput
              - id: prop.B.2
                type: TextInput
              - id: clear
                type: Button
                properties:
                  size: large
                  title: clear prop
                  color: '#1890ff'
                  a: # adding this here so you can watch state change
                    _log:
                      _state: true
                events:
                  onClick:
                    - id: reset
                      type: SetState
                      params:
                        prop.A: null
                        prop.B.2: null

```
What was interesting for me here is that the numeric keys resolves to an array value, so this causes `prop.B` to be an array, which is interesting.  However, this works as intended since that is how Lowdefy interprets numerical keys in dot notation.
