### DISCUSSION TITLE
Layout of a List

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1340] [Questions and Help] [answered]
Can some items in a List share the same line?For example,there's a two-dimensional array, I want all items of the same dimension layout in the same line,just look like:
```shell
#the result I want
data[0][0]= a1           data[0][1]= a2
data[1][0]= b1           data[1][1]= b2           data[1][2]= b3
```
code comes here:
```yaml

lowdefy: 3.23.3
name: Lowdefy starter

pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    events:
      onEnter:
        - id: init
          type: SetState
          params:
            data: 
              - - a1
                - a2
              - - b1
                - b2
                - b3
    areas:
      content:
        justify: center
        blocks:
          - id: data
            type: List
            blocks:
              - id: data.$
                type: List
                layout:
                  span: 
                    _log:
                      _divide:
                        - 24
                        - _array.length:
                            _state: data.$
                blocks:
                  - id: data.$.$
                    type: Markdown
                    properties:
                      content: 
                        _string.concat:
                          - '**data['
                          - _index: 0
                          - ']['
                          - _index: 1
                          - ']**= '
                          - _state: data.$.$
```
actually result is:
![image](https://user-images.githubusercontent.com/56707831/185916062-c8ce0212-3c95-42e8-a985-044d4eecadf2.png)

**Comment by Gervwyk** [comment, marked as answer]
Hi @13316090972 
See:
```yaml
lowdefy: 3.23.3
name: Lowdefy starter

pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    events:
      onEnter:
        - id: init
          type: SetState
          params:
            data:
              - - a1
                - a2
              - - b1
                - b2
                - b3
    areas:
      content:
        justify: center
        blocks:
          - id: data
            type: List
            blocks:
              - id: data.$
                type: List
                properties:
                  direction: row
                areas:
                  content:
                    style:
                      flex: 1 0 auto
                blocks:
                  - id: data.$.$
                    type: Markdown
                    properties:
                      content:
                        _string.concat:
                          - '**data['
                          - _index: 0
                          - ']['
                          - _index: 1
                          - ']**= '
                          - _state: data.$.$
```
This will get you almost there..
