### DISCUSSION TITLE
MultipleSelector with Group selecting

### DISCUSSION THREAD

**Discussion by 1xtr** [lowdefy/lowdefy#1362] [Questions and Help]
Is it possible to create MultipleSelector with groups and if group clicked/selected select all items in group?

**Comment by 13316090972** [comment]
What to be with groups, options in MultipleSelector or several MultipleSelector?
or you can see this example:
![image](https://user-images.githubusercontent.com/56707831/192204577-9b6b2c0b-6cf7-45dd-9cc4-3e05652ab710.png)
![image](https://user-images.githubusercontent.com/56707831/192204595-62e7bf3f-8166-498d-9c02-7e258e104d61.png)

```yaml
lowdefy: 3.23.3
name: Lowdefy starter

pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    areas:
      content:
        justify: center
        blocks:
          - id: content_card
            type: Card
            style:
              maxWidth: 800
            blocks:
              - id: mselector
                type: MultipleSelector

                properties:
                  title:
                    What do you want?
                  options:
                    - label: Fish
                      value: 1
                    - label: Life
                      value: 2
                    - label: Bear paw
                      value: 11
                    - label: dao yi
                      value: 12

              - id: junzi
                type: CheckboxSwitch
                properties:
                  label:
                    title: I want to be a junzi
                    inline: true
                layout:
                  span: 12
                events:
                  onChange:
                    - id: change
                      type: SetState
                      params:
                        normal: false
                        mselector: 
                          _if:
                            test:
                              _state: junzi
                            then:
                              - 11
                              - 12
                            else:
                              []
              - id: normal
                type: CheckboxSwitch
                properties:
                  label:
                    title: I want to be a normal
                    inline: true
                layout:
                  span: 12
                events:
                  onChange:
                    - id: change
                      type: SetState
                      params:
                        junzi: false
                        mselector: 
                          _if:
                            test:
                              _state: junzi
                            then:
                              - 1
                              - 2
                            else:
                              []
```
