### DISCUSSION TITLE
PostgreSQL (Knex) connection use pooling to avoid reaching the limit of sessions

### DISCUSSION THREAD

**Discussion by vicam001** [lowdefy/lowdefy#1370] [Questions and Help] [answered]
I am on *lowdefy: 3.23.3* , using as may main connection one to a PostgreSQL database.

Having a very moderate usage of the app built on Lowdefy already is making me exceed the number of idle sessions of PostgreSQL (I am running it on the free tier of AWS RDS for the moment) and makes me wonder if there is a possibility to configure  connection pooling so that the app does not try to establish a new connection every time a request is fired.

Does anybody in the community have experience solving this? I am highly concerned as the Lowdefy framework really covers my needs but I need to be able to have an application with multiple pages and mutiple requests without reaching the "**_psql: FATAL: remaining connection slots are reserved for non-replication superuser connections_**" error.

Thank you for your support.

Example of my ```lowdefy.yaml``` file
```yaml


connections:
  - id: aws_rds_postgres
    type: Knex
    properties:
      client: postgres
      connection:
        _secret: PG_CONNECTION_STRING
      version: '7.2'
      searchPath: 'public'
  - id: auth0_api
    type: AxiosHttp
    properties:
      baseURL: 
        _secret: OPENID_DOMAIN
      headers:
        content-type: 'application/json'

```

Example of a request:

```yaml

id: fetch_countries
type: KnexRaw
connectionId: aws_rds_postgres
properties:
  query: 
    SELECT id AS value, name AS label, is_inactive as disabled FROM public.countries WHERE name LIKE :like_query
  parameters:
    like_query: 
      _nunjucks: '%{{ search_input }}%'

```

**Comment by SamTolmay** [comment, marked as answer]
Hi @vicam001 

How are you deploying the Lowdefy app? In a serverless environment or as a Docker container.

You can use PgBouncer as a connection pooler for PostgreSQL: http://www.pgbouncer.org. This will pool the connections with the database.

Since you are on AWS RDS, you can also look at Amazon Aurora PostgreSQL Serverless (https://aws.amazon.com/blogs/aws/amazon-aurora-postgresql-serverless-now-generally-available/), which is designed to handle the many connections made by serverless functions.

**Reply by vicam001** [reply]
Hi @SamTolmay , thank you very much for such a super fast response.

I'm running the Lowdefy app as a Docker container on AWS App Runner. Would the deployment on AWS Lambda with the serverless framework ease this challenge?

Thanks for pointing towards pgbouncer or the benefits of AWS Aurora (a bit tricky this option as falls outside of AWS Free Tier and the cost scales up pretty fast compared to AWS RDS for PostgreSQL. 

This is really at the edge of my technical skills but I'll see what I can do to solve it.

Thanks!

**Reply by SamTolmay** [reply]
Running your app on Lambda won't help with this issue, it might actually make it worse because Lambda might create even more connections. I think running PgBouncer as a docker container might be the best solution. There is this docker image on dockerhub: https://hub.docker.com/r/edoburu/pgbouncer/

**Reply by vicam001** [reply]
You are right, @SamTolmay  !

By the way, I have solved this challenge by using the [**AWS RDS Proxy** ](https://aws.amazon.com/es/rds/proxy/) (it costs more than running a Docker container with pgbouncer) but quite easy to setup. The only caveat here is that AWS RDS Proxy only works within a VPC, so I have re-engineered the solution (wasn't that bad as having a database open to the public internet was not so great idea).

In order to connect the app running on AWS App Runner to the VPC I have had to enable its feature to connect to a VPC (via private subnet due to how its internal networking works) and that has meant adding a NAT Gateway (which is nearly as expensive as running the app on AWS App Runner!) 

I have kept investigating ways to avoid this costs and I am just trying the Lambda-deployment approach (https://docs.lowdefy.com/aws-lambda) , it's even better as will be cheaper than AWS App Runner.

I have not been able to open a PR to fix the docs, please note that ```useDotenv: true``` needs to be added, in order to read the environment variables properly (and also you'd like to update the frameworkVersion appearing on the docs) :

```yaml
service: lowdefy-example-aws-lambda
frameworkVersion: '3.22.0'
useDotenv: true
provider:
  name: aws
  region: us-east-1
  ecr:
    images:
      lowdefy:
        path: .
        file: Dockerfile

functions:
  lowdefy-server:
    image: lowdefy
    name: lowdefy-example-aws-lambda-${opt:stage}
    # Set secrets as environment variables here
    # environment:
    #   LOWDEFY_SECRET_MY_SECRET: ${env:LOWDEFY_SECRET_MY_SECRET}

    events:
      - httpApi: '*'
 ```


I hope one day I can contribute posting on how to run Lowdefy apps on AWS on a very low budget  :)
