### DISCUSSION TITLE
Aws cognito for user authentication

### DISCUSSION THREAD

**Discussion by TobyGWilliams** [lowdefy/lowdefy#1384] [Questions and Help] [answered]
Hi,

I'd like to use lowdefy with our existing user management AWS Cognito. I didn't find any documentation online and my initial stab wasn't fruitful.

- Is there any documentation about specific to cognito integration?
- is there any debugging about Auth config that can be enabled
- LOWDEFY_SECRET_OPENID_DOMAIN - is this the well-known endpoint or the domain that the client should redirect to for sign in?

Any help would be really appreciated

**Comment by SamTolmay** [comment, marked as answer]
Hi @TobyGWilliams 

Lowdefy V works with Identity Providers that follow the OpenID Connect specification. It looks like some people have got it to work with the library we use, which you can read about here: https://github.com/panva/node-openid-client/issues/95

According to this issue, the`LOWDEFY_SECRET_OPENID_DOMAIN` should be `https://cognito-idp.{{aws-region}}.amazonaws.com/{{your_pool_id}}`

You can also consider using Lowdefy V4, which isas this uses Next-Auth.js, which supports much more providers. The docs for for AWS Cognito are here: https://next-auth.js.org/providers/cognito. Even if you don't move to V4, I think making sure the settings they recommend would probably be neccesary to make things work in V3.

The configuration for AWS Cognito auth in V4 will be:
```yaml
auth:
  providers:
    - id: auth0
      type: CognitoProvider
      properties:
        clientId:
          _secret: COGNITO_CLIENT_ID
        clientSecret:
          _secret: COGNITO_CLIENT_SECRET
        issuer:
          _secret: COGNITO_ISSUER
  pages:
    protected: true
    public:
      - login
```
