### DISCUSSION TITLE
Can menu in PageHCSF be collapsable?

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1386] [Questions and Help] [answered]
I have a custom menu,which is contained in  a PageHCSF page,could this menu be collapsable?
![image](https://user-images.githubusercontent.com/56707831/192718413-1fe7e1ba-b2a7-4807-a4da-3199a98d3846.png)

```yaml

lowdefy: 3.23.3
name: Lowdefy starter
menus:
  - id: myMenu
    type: Menu
    links:
      - id: welcome
        type: MenuLink
        pageId: welcome
        properties:
          icon: HomeOutlined
          title: welcome
          danger: false
        links: []
        style: null
        
pages:
  - id: welcome
    type: PageHCSF
    properties:
      title: Welcome
   


    areas:
      sider:
        blocks:
          - id: myMenu
            type: Menu
      content:
        justify: center
        blocks:
          - id: content_card
            type: Card
            style:
              maxWidth: 800
            blocks:
              - id: content
                type: Result
                properties:
                  title: Welcome to your Lowdefy app
                  subTitle: We are excited to see what you are going to build
                  icon:
                    name: HeartTwoTone
                    color: '#f00'
                areas:
                  extra:
                    blocks:
                      - id: docs_button
                        type: Button
                        properties:
                          size: large
                          title: Let's build something
                          color: '#1890ff'
                        events:
                          onClick:
                            - id: link_to_docs
                              type: Link
                              params:
                                url: https://docs.lowdefy.com
                                newTab: true



```
