### DISCUSSION TITLE
How to make calls to a database (e.g. PostgreSQL) as an authenticated user?

### DISCUSSION THREAD

**Discussion by vicam001** [lowdefy/lowdefy#1400] [Questions and Help] [answered]
Hi there, I open this discussion to gather the community knowledge around making calls to a database (for example a PostgreSQL db hosted on AWS RDS using the Knex connector) with a user that is taken from the logged in user instead of a hard-coded user.

So, if in ```lowdefy.yaml``` we need to define a connection as follows:

```yaml
...
connections:
  - id: postgres
    type: Knex
    properties:
      client: postgres
      connection:
        host:
          _secret: PG_HOST
        user:
          _secret: PG_USER
        database:
          _secret: PG_DB
        password:
          _secret: PG_PASSWORD
...
```
Basically we are making calls to the database as one user. I would need to be able to make such calls as the logged-in user (which is managed in Auth0)

Would it make sense to use ```_user: name``` ?

```yaml
...
connections:
  - id: postgres
    type: Knex
    properties:
      client: postgres
      connection:
        user:
          _user: name
...
```
But then, what about the password ? 

Is there any possibility to connect the openID piece with the connections/requests piece in Lowdefy? Sorry if this is too obvious.

I am considering switching to AWS RDS with IAM connections (instead of standard PostgreSQL users) to the DB and then using AWS Cognito for the user management (apparently possible on Lowdefy thanks to this post https://github.com/lowdefy/lowdefy/discussions/1384#discussioncomment-3723278 from @SamTolmay ) but then I am far beyond my knowledge and I have no clue how to make calls to the database with IAM instead of the connection string ....

Thanks for any hint on how to solve this.
