### DISCUSSION TITLE
How to use the method setFilterModel in AG Grid

### DISCUSSION THREAD

**Discussion by vicam001** [lowdefy/lowdefy#1406] [Questions and Help] [answered]
Hi,
I am using the AG Grid block (https://github.com/lowdefy/blocks-aggrid) and would like to know how tu use the method ```setFilterModel```.

I am trying something like:

```yaml
id: button_unselect
type: Button
layout:
   flex: 0 1 auto
properties:
   title: Deseleccionar
   icon: UndoOutlined
events:
  onClick:
     - id: unselect_rows
       type: CallMethod
       params:
          blockId: my_table
          method: setFilterModel

```

According to the AG Grid Documentation ( https://www.ag-grid.com/javascript-data-grid/filter-api/ ) , the api is something like

```js
gridOptions.api.setFilterModel(null);
```

How can I make it work ?

I have also tried using as params:

```
...
params:
  blockId: my_table
  method: setFilterModel
  model: {}
```
or
```
...
params:
  blockId: my_table
  method: setFilterModel
  model: null
```

And I always get the error:
```
Failed to call method "setFilterModel" on block "my_table". Check if "setFilterModel" is a valid block method for block "my_table". Received "{"blockId":"my_table","method":"setFilterModel"}".
```
or
```
Failed to call method "setFilterModel" on block "my_table". Check if "setFilterModel" is a valid block method for block "my_table". Received "{"blockId":"my_table","method":"setFilterModel","model":{}}".
```
or 
```
Failed to call method "setFilterModel" on block "my_table". Check if "setFilterModel" is a valid block method for block "my_table". Received "{"blockId":"my_table","method":"setFilterModel","model":null}".
```

Thanks a lot for the help!
