### DISCUSSION TITLE
Filtering array of objects

### DISCUSSION THREAD

**Discussion by bertovn** [lowdefy/lowdefy#1420] [Questions and Help] [answered]
Hi team :)
First of all let me thank you for great tool, it is really cool :)
And my question is: How can i filter array of objects? 
i can do it with clear JS, something like:
```
const words = [
{
Backend_name: "BK_RDP",
Hostname: "rdphost1",
selected: false
},
{
Backend_name: "BK_RDP",
Hostname: "rdphost2",
selected: true
},
{
Backend_name: "BK_RDP",
Hostname: "rdphost3",
selected: false
},
{
Backend_name: "BK_SSH",
Hostname: "rdphost1",
selected: false
},
{
Backend_name: "BK_SSH",
Hostname: "rdphost2",
selected: true
},
{
Backend_name: "BK_SSH",
Hostname: "rdphost3",
selected: false
}
];

const result=words.filter(function (thiselement) {
	return thiselement.selected==true;
})
```
But i really can't get how to achieve the same with  ```_array.filter``` operator:
```
              - id: FilterArray
                type: SetState
                params:
                  SelectedServers:
                    _array.filter:
                      _log:
                        on: 
                          _state: servers_list
                        callback:
                          _function:
                            __if:
                              test:
                                __eq:
                                  - __args: 0.selected
                                  - true
```
but without success. Any ideas?

**Comment by JohannMoller** [comment, marked as answer]
Hi @bertovn,

I'm glad you are enjoying Lowdefy.
You are very close to having it working. For your callback function, you can just use the `_eq` operator instead of `_if`, since `_eq` returns true or false:
```yaml
        - id: FilterArray
          type: SetState
          params:
            SelectedServers:
              _array.filter:
                on:
                  _state: servers_list
                callback:
                  _function:
                    __eq:
                      - __args: 0.selected
                      - true
```

Since the `selected` field is already a boolean, you can make it even simpler and just use that in the callback function:
```yaml
        - id: FilterArray
          type: SetState
          params:
            SelectedServers:
              _array.filter:
                on:
                  _state: servers_list
                callback:
                  _function:
                    __args: 0.selected
```
