### DISCUSSION TITLE
forEach through array

### DISCUSSION THREAD

**Discussion by bertovn** [lowdefy/lowdefy#1424] [Questions and Help]
Hey dear Lowdefy team :)
Got today answer [here](https://github.com/lowdefy/lowdefy/discussions/1420), but faced some one trouble without any visible ways to resolve:

```
              - id: FilterArray
                type: SetState
                params:
                  SelectedServers:
                    #_log:
                    #_json.stringify:
                    _array.filter:
                      on: 
                        _state: servers_list
                      callback:
                        _function:
                            __args: 0.selected
```
 I got the array with entities i wanted using _array.filter (once again many thanks 2 Johann Möller):
```
              - id: FilterArray
                type: SetState
                params:
                  SelectedServers:
                    #_log:
                    #_json.stringify:
                    _array.filter:
                      on: 
                        _state: servers_list
                      callback:
                        _function:
                            __args: 0.selected
```
 but i don't see any way to make a request for each of them,  made some experiments with ```_array.reduce``` and ```_args``` in ```_function``` but without any success
 I tried also create a JSON string which will contains both objects, but it contains first element only:
```
- id: ServerVar
  type: Paragraph
  properties:
    content:
      _log:
        _json.stringify:
          _state: SelectedServers
  options:
    stable: true 
```
![image](https://user-images.githubusercontent.com/54134702/206280559-ebe602e7-710e-4313-b833-9a6aa044df5e.png)
