### DISCUSSION TITLE
How to use the _args operator in nested functions

### DISCUSSION THREAD

**Discussion by vicam001** [lowdefy/lowdefy#1444] [Questions and Help] [answered]
Dear Lowdefy Community,

I am totally blocked by something apparently trivial, but that I am failing to get right...

Could you please share an example on how to use _args in nested functions ?

For example, I have a request that returns an array such as:

```yaml
- id : 1
  name: Peter
  business_units:
  - business_unit:
     id: 1
     label: Unit 01
  - business_unit:
     id: 2
     label: Unit 02
- id : 2
  name: John
  business_units:
  - business_unit:
     id: 3
     label: Unit 03
  - business_unit:
     id: 4
     label: Unit 04

```

and I would need to convert it into:

```yaml
- id: 1
  name: Peter
  business_units: Unit 01,Unit 02

- id: 2
   name: John
   business_units: Unit 03,Unit 04

```

I am trying :

```yaml

- id: accounts
      type: SetState
      params:
        accounts:
           __array.map:
              on:
                   _request: get_accounts.data
              callback:
                 _function:
                    id:
                      __args: 0.id
                    name:
                      __args: 0.name
                    business_units:
                        __array.join:
                            on:
                               __array.map:
                                      on:
                                         __args: 0.business_units
                                      callback:
                                         __function:
                                              __args: business_unit.label
                    
```

The challenge is that the __args operator in the bottom part is not working as expected, I am not being able to access each of the elements of the array business_units: [] 

It might be that I am missing something very small, but I have tried many different combinations and no luck.

Thanks a lot in advance for your guidance. I think that the __array.map operator is one of the most powerful ones in Lowdefy (in any programing paradigm) and more examples on the documentation would be super valuable.

**Comment by SamTolmay** [comment, marked as answer]
Hi @vicam001 
I think what you need is:
```yaml
- id: accounts
  type: SetState
  params:
    accounts:
      _array.map:
        on:
          _request: get_accounts.data
        callback:
          _function:
            id:
              __args: 0.id
            name:
              __args: 0.name
            business_units:
              __array.join:
                on:
                  __array.map:
                    on:
                      __args: 0.business_units
                    callback:
                      __function:
                        ___args: business_unit.label
```
Specifically there should be three underscores in the last `___args: business_unit.label` line.

The way functions work in lowdefy is that all JSON keys with a double underscore get stripped of one underscore, and then the resulting JSON is evaluated. So to have a nested function inside another one, the operators used in the nested function need three underscores.

I agree that we need some better docs and examples for `_array.map`, it is very useful
