### DISCUSSION TITLE
Add text alignment of label extra fields as integrated property

### DISCUSSION THREAD

**Discussion by gramian** [lowdefy/lowdefy#1455] [Ideas and feature requests]
Dear Developers, Dear Community,

I would like to propose to add the text alignment of the extra field of labels as a Lowdefy setting. Currently, I find myself often using:
```
extraStyle:
  text-align: right
```
as it makes forms look less crowded if you also use a label and placeholder. So, I would like to have a label property like:
```
extra-align:
  default: left
  description: Align extra left or right.
  enum:
    - left
    - right
  type: string
```
for blocks with labels, like `TextInput`, `TextArea`, `Button`, `TitleInput`, `Selector` etc. as well as the `Label` container block.

Thank you for considering my proposal

Regards
