### DISCUSSION TITLE
i18n: Change validation messages globally

### DISCUSSION THREAD

**Discussion by vrilcode** [lowdefy/lowdefy#1457] [Questions and Help]
Is there any possibility to change form/input validation messages globally? My app is not in English, so it would be good to have translated messages in the application.

**Comment by vicam001** [comment]
Hi @vrilcode !

I'd also love to see a way to build fully localizable apps using Lowdefy ( my use case is mostly in Spanish).

In the meantime, I suggest you customize the validation messages by writing your custom message as below:

Instead of :

```yaml
- id: name
  type: TextInput
  required: true
  properties:
     title: Nombre

```

you may write something like:

```yaml
- id: name
  type: TextInput
  required: Es necesario indicar el Nombre    # The Spanish way to say "It is required to enter the Name"
  properties:
     title: Nombre
```

Also, a custom validation message could look like:

```yaml

id: mobile
type: TextInput
layout:
  span: 12
validate:
  - message: 'No tiene formato de teléfono: o incluye espacios, o no incluye prefijo telefónico (ej. +34) o no cumple la longitud necesaria)'
   status: error
   pass:
    _or:
      - _regex: '(^\+[1-9]\d{1,14}$)|(^$)'  # Phone Number format E.164
      - _not: # Empty
          _state: mobile
properties:
  title: Móvil
  prefixIcon: MobileOutlined
  placeholder: Añadir prefijo (ej. +34) para SMS


```

**Reply by vrilcode** [reply]
Thank you for the examples. It would be good to have an application-wide possibility for translation of common messages (and also number and date formats). But your solution still helps a a lot.

**Comment by SamTolmay** [comment]
Hi @vrilcode

Building localizable apps is not something supported by Lowdefy currently, but it is on our roadmap.

One thing you can in the meantime is use the `_ref` operator to reference translations from a centralised file, so that they are all defined in one place. In V4 we added a `key` argument to this operator whick makes this possible.

This would change @vicam001 example from:
```yaml
- id: name
  type: TextInput
  required: Es necesario indicar el Nombre    # The Spanish way to say "It is required to enter the Name"
  properties:
     title: Nombre
```
to:
```yaml
- id: name
  type: TextInput
  required:
    _ref:
      path: translations.yaml
      key: number_requried
  properties:
     title: Nombre
```
and
```yaml
# translations.yaml
number_required: Es necesario indicar el Nombre
```

You can use dot notation when referencing, so the translation file does not need to be flat.
