### DISCUSSION TITLE
How to validate non-required field with regular expressions?

### DISCUSSION THREAD

**Discussion by gramian** [lowdefy/lowdefy#1459] [Questions and Help] [answered]
Dear All,
If I am using regex validation, as in the example on https://docs.lowdefy.com/_regex ("Using the value of the block in which the operator is evaluated ...") , on a non-required field and the field is empty, it is **not valid**. If I append my pattern with an additional piped pattern that matches empty strings like `|^$` it is still not valid. Thus I would like to ask, how do I validate an non-required field with the `_regex` operator, so the field turns out valid if it is empty or fulfills a specfifc regex pattern.

Thank you for your help

**Comment by Gervwyk** [comment, marked as answer]
Hi @gramian 

Empty string inputs in Lowdefy will have a value of `null` in state and `_regex` returns `false` on a `null` value. So this is the expected behaviour.
 
So to exclude the empty input value, you need to explicitly allow it in the validation test like so:
```yaml
     - id: foo
        type: TextInput
        validate:
          - message: Invalid username.
            status: error
            pass:
              _or:
                - _regex: ^[a-z0-9_-]{3,16}$
                - _eq:
                    - _state: foo
                    - null
```
