### DISCUSSION TITLE
ConfirmModal block between other blocks breaks layout

### DISCUSSION THREAD

**Discussion by vrilcode** [lowdefy/lowdefy#1463] [Ideas and feature requests]
If I use a ConfirmModal between other blocks (e.g. Button) it breaks my layout, because it's a CSS block element (and also has gutter/padding etc). If I use extra style `display: none` it's fine. As a new Lowdefy user I am unsure, whether this is intended. If not, `display: none` should probably be a default property for ConfirmModal blocks. Maybe regular Modal blocks are also affected, I've not tested it.

```yaml
- id: my_confirm_modal
  type: ConfirmModal
  properties:
    content: Are you sure?
  style:
    display: none
```

**Comment by Gervwyk** [comment]
Hi @vrilcode 
Thanks for this, could you please provide an example of the config where you see the issue?

**Comment by vrilcode** [comment]
Hey @Gervwyk,

this is a minimal example, where the problem occurs:
```yaml
id: test
type: PageHeaderMenu
properties:
  title: Test
layout:
  contentGutter: 8
blocks:
  - id: my_button1
    type: Button
  - id: my_confirm_modal
    type: ConfirmModal
    properties:
      content: Are you sure?
  - id: my_button2
    type: Button
```
<img width="281" alt="image" src="https://user-images.githubusercontent.com/31141078/211554037-2d1c506a-71c5-4b2c-9f93-54ea20d72209.png">
<img width="252" alt="image" src="https://user-images.githubusercontent.com/31141078/211554123-2af325ca-9648-4592-82a1-831d57d131ca.png">

In this example, it just adds some gutter, but there are also cases where it forces line breaks etc. If I use `display: none` it looks like it should (like without ConfirmModal block):
```yaml
id: test
type: PageHeaderMenu
properties:
  title: Test
layout:
  contentGutter: 8
blocks:
  - id: my_button1
    type: Button
  - id: my_confirm_modal
    type: ConfirmModal
    properties:
      content: Are you sure?
    style:
      display: none
  - id: my_button2
    type: Button
```
<img width="276" alt="screenshot" src="https://user-images.githubusercontent.com/31141078/211555323-bcab7784-05f4-45c2-a865-557fe19068d3.png">

**Comment by kemeris2000** [comment]
It may be temp. solution:

```
.ant-row {
    row-gap: 0px !important;
}
```
in `app/public/styles.less` file

**Reply by Gervwyk** [reply]
This is not the best approach since it will break row padding for the entire app, layout relies on this to implement gutter spacing as required.

**Comment by Gervwyk** [comment]
The `contentGutter: 8` in this config introduces padding between child block, unfortunately also for the confirm modal block, which needs a div element to nest modal elements. An easy workaround here is:
```yaml
id: test
type: PageHeaderMenu
properties:
  title: Test
layout:
  contentGutter: 8
blocks:
  - id: btn_box
    type: Box
    blocks:
      - id: my_button1
        type: Button
      - id: my_confirm_modal
        type: ConfirmModal
        properties:
          content: Are you sure?
        style:
          display: none
  - id: my_button2
    type: Button
```
This will apply the gutter padding to the `test` content area, but since no gutter setting is applied to the `btn_box` area, the `my_button1` and `my_confirm_modal` will not be padded.
