### DISCUSSION TITLE
Global default values, especially for Blocks

### DISCUSSION THREAD

**Discussion by vrilcode** [lowdefy/lowdefy#1470] [Ideas and feature requests]
It would be helpful, if one could store default values for blocks etc. in a central location. So you don't have to specify certain values multiple times in the app. For instance a default value for `format` property of `DateSelector` or a default value of `inner` property of `Card` blocks.

I know, that you can combine variables with `_ref`, but you still have to specify it everytime you use a certain block.

**Comment by Gervwyk** [comment]
Hi @vrilcode 
Interesting idea, what we usually do is to create a template for such blocks. Like this:

##### components/rating_slider.yaml
```yaml
id:
  _var: id
type: RatingSlider
required:
  _var: required
visible:
  _var: visible
properties:
  title:
    _var: title
  label:
    colon: false
  color:
    _switch:
      branches:
        - if:
            _eq:
              - _state:
                  _var: id
              - null
          then: '#808080'
        - if:
            _lt:
              - _state:
                  _var: id
              - 6
          then: '#f5222d'
        - if:
            _gt:
              - _state:
                  _var: id
              - 8
          then: '#52c41a'
      default: '#fa8c16'
  disableNotApplicable: true
  min: 1
  maxIcon:
    name: AiOutlineSmile
    color: '#52c41a'
    size: 32
  minIcon:
    name: AiOutlineFrown
    color: '#f5222d'
    size: 32
```

Then when you use it, you simply specify the vars:
```yaml
...
blocks:
 - _ref:
     path: components/rating_slider.yaml
     vars:
       id: survey.nps
       title: Would you recommend Lowdefy to a friend?
...
```
