### DISCUSSION TITLE
V4 custom plugins error

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1483] [Questions and Help]
Hi, I am very happy to see lowdefy upgrade 4.0, but I have encountered some problems when using the V4.0 plugins.
I want to customize the Block in V4,  modify the `app/lowdefy.yaml` and `plugins/plugin-name/src/locks/Block/Block.js` in the official example https://github.com/lowdefy/lowdefy-example-plugins, and then run the error report. How can I solve it?
Error Message
![image](https://user-images.githubusercontent.com/72787010/215314468-8695def7-0abf-4f46-8458-1ce1013e3663.png)
app/lowdefy.yaml
```yaml
lowdefy: 4.0.0-alpha.36 # Please check for latest Lowdefy version.
license: MIT

plugins:
  - name: "plugin-name"
    version: "workspace:*"
  - name: "plugin-times-eleven-operator"
    version: "workspace:*"

pages:
  - id: plugin-example
    type: Block
    blocks:
      - id: number
        type: NumberInput
        properties:
          title: Type a number
      - id: result
        type: Html
        properties:
          html:
            _nunjucks:
              template: |
                {% if number != null %}
                  {{ number }} times eleven is: {{ result }}
                {% endif %}
              on:
                number:
                  _state: number
                result:
                  _times_eleven:
                    number:
                      _state: number

```
plugins/plugin-name/src/locks/Block/Block.js
```js
import React from 'react';
import { blockDefaultProps } from '@lowdefy/block-utils';

const Block = ({ basePath, blockId, components, content, events, list, loading, methods, menus, pageId, properties, required, validation, value }) => (
  <div
    id={blockId}
    onClick={() => methods.triggerEvent({ name: 'onClick' })}
    className={methods.makeCssClass([
      { outline: 'none', cursor: events.onClick && 'pointer' },
      properties.style,
    ])}
  >
    {properties.content || (content.content && content.content())}
  </div>
);

Block.defaultProps = blockDefaultProps;
Block.meta = {
  category: 'display', // one of 'container', 'display', 'input' or 'list'
  icons: [],
  styles: [],
};

export default Block;

```
