### DISCUSSION TITLE
reference of _nunjucks template

### DISCUSSION THREAD

**Discussion by mahdyarief** [lowdefy/lowdefy#1492] [Questions and Help] [answered]
Can some one explain, where is reference nunjuck template?

`created_at:
      _nunjucks:
        template: '{{ my_date | date("YYYY-MM-DD hh:mm:ss") }}'
        on:
          my_date:
            _date: now`
            
from that code, if i wanna use format currency or another format, where i can see reference to use the code?

**Comment by SamTolmay** [comment, marked as answer]
Hi @mahdyarief 

We only have date formatting in nunjucks templates, like the example you shared. You can use any moment.js format string to format the date, as described here: https://momentjs.com/docs/#/displaying/format/.

If you just want to format the date string and not use it in a nunjucks template, or if you want to do a currency format you can use the [`_format`](https://docs.lowdefy.com/_format) operater if using V3, or the [`_intl`](https://docs-git-develop-lowdefy.vercel.app/_intl) and [`_moment`](https://docs-git-develop-lowdefy.vercel.app/_moment) operators if using V4.

For example, you might do:
```yaml
# V3
formatted_currency:
  _format.intlNumberFormat:
    on: 1318.47
    params:
      options:
        style: currency
        currency: USD
```
```yaml
#V4
formatted_currency:
  _intl.numberFormat:
    on: 1318.47
    options:
      style: currency
      currency: USD
```
