### DISCUSSION TITLE
Get Data from Google Sheet & store data to Selector

### DISCUSSION THREAD

**Discussion by mahdyarief** [lowdefy/lowdefy#1501] [Questions and Help] [answered]
Can some one tell me how to use data from google sheet
https://docs.google.com/spreadsheets/d/1p5zXxyN42_z8MKP2ZIoTCoPOY-5P6TIvRk0GbQJrnBw/edit#gid=446605129

make connection:
```
id: gs_cabang
type: GoogleSheet
properties:
  client_email:
    _secret: SHEETS_CLIENT_EMAIL
  private_key:
    _base64.decode:
      _secret: SHEETS_PRIVATE_KEY
  sheetId: '446605129'
  spreadsheetId: 1p5zXxyN42_z8MKP2ZIoTCoPOY-5P6TIvRk0GbQJrnBw
  write: true
```
i already make request:
```
id: getCabang
type:  GoogleSheetGetMany
connectionId: gs_cabang
properties:
  options:
    limit: 10
```
already call request on event onInit:
```
events:
  onInit:
    - id: getCabang
      type: Request
      params: 
        - getCabang
```
how, i can use that data to selector block
```
blocks:
        - id: pilih_cabang
          type: Selector
          properties:
            options:
              - label: 
                  _var: nama_cabang
                value: 
                  _var: nama_cabang
                disabled: false
                style: null
```        
Please help me..
