### DISCUSSION TITLE
SetState of array element with variable index

### DISCUSSION THREAD

**Discussion by vrilcode** [lowdefy/lowdefy#1523] [Questions and Help]
I need to set an element of an array (SetState), but element index is variable, not static. How can I achieve that?

**Comment by JohannMoller** [comment]
Hi @vrilcode,

Can you give me some more context on this? A simple example will also help.

**Reply by vrilcode** [reply]
Unfortunately I don't have a simple example. My scenario is a quite common master-detail-view. Think of a table (eg. agGrid) to select a record on row click and have some form inputs for editing the selected record below the table. Additionally: It's not possible to save and load single records through database, because all records/items are saved and loaded together (so they have to stay in memory/context/state).
I can copy selected record to a state property "current_record", but I couldn't write it back to the array of records. That's what I wanted to achieve. Now I've used a List widget as workaround (it shows all details of all records at the same time, but no array issues).

**Comment by Gervwyk** [comment]
I think @vrilcode is trying to do the equivalent of:
```js
arr[x] = 'y';
```

Which is very valid. Currently we only have some array methods mapped to `_array` operator and since there is no array method in js to do the above, it wasn't included. 

I think we should implement something like:
```yaml
_array.defineItem:
    - _state: arr
    - _state: x
    - _state: y
```
Technically you should be able to do this in the current version by modifying the object property you pass to `SetState`. But this is not user friendly.

```yaml
- id: set_index
  type: SetState
  params:
    _object.defineProperty:
        - {}
        - _string.concat:
             - 'arr.'
             - _number.toString: 
                 _state: x
         - descriptor:
              value: 
                _state: y
```
