### DISCUSSION TITLE
How to populate List block with array from _request

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1533] [Questions and Help] [answered]
How to populate List block with array from _request.data?

According to manual https://docs.lowdefy.com/lists its possible with statically defined array.

```yaml
contacts:
  - name: Name 1
    emails:
      - email1@example.com
      - email2@example.com
  - name: Name 2
    emails: []
id: contacts
type: ControlledList
properties:
  # ...
blocks:
  - id: contacts.$.name
    type: TextInput
    properties:
      # ...
  - id: contacts.$.emails
    type: ControlledList
    properties:
      # ...
    blocks:
      - id: contacts.$.emails.$
        type: TextInput
        properties:
          # ...
```

**Comment by JohannMoller** [comment, marked as answer]
Hi @kemeris2000,

To use the data from a request to populate the List block, you just need to set the request data in state. So if you have a request that returns:
```json
"data": [
    {
      "name": "Name 1",
      "emails": [
        "email1@example.com",
        "email2@example.com"
      ]
    },
    {
      "name": "Name 2",
      "emails": []
    }
  ]
```
You need to use the `SetState` action to set the data to state before you can use it in the List block:
```yaml
id: my_page
type: PageHeaderMenu
requests:
  - id: my_request
  # ...
events:
  onMount:
    - id: fetch_data
      type: Request
      params: my_request
    - id: set_data_to_state
      type: SetState
      params:
        contacts:
          _request: my_request.data
blocks:
  - id: contacts
    type: ControlledList
    properties:
      # ...
    blocks:
      - id: contacts.$.name
        type: TextInput
        properties:
          # ...
      - id: contacts.$.emails
        type: ControlledList
        properties:
          # ...
        blocks:
          - id: contacts.$.emails.$
            type: TextInput
            properties:
              # ...
              ```

**Comment by kemeris2000** [comment]
Thank you Johann, your solution works.

**Comment by kemeris2000** [comment]
Another related question. In the following example how to reference array items in span content property.
List does create span block for each array item, but `content: GetClientsProducts.$.translated_groupname` does not work.

```
blocks:
  - id: GetClientsProducts
    type: List
    properties:
      direction: column
    blocks:
      - id: GetClientsProducts.$
        type: Span
        properties:
          content: GetClientsProducts.$.translated_groupname
```

**Reply by JohannMoller** [reply]
You just need to reference the value from state using the `_state` operator.
```yaml
blocks:
  - id: GetClientsProducts
    type: List
    properties:
      direction: column
    blocks:
      - id: GetClientsProducts.$
        type: Span
        properties:
          content: 
            _state: GetClientsProducts.$.translated_groupname
```
