### DISCUSSION TITLE
How to convert each item in array

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1535] [Questions and Help] [answered]
I need to sum all 'total' values from each array items, but this value type is string. How can I achieve this?

I have tried:

```
blocks:
  - id: box1
    type: Box
    properties:
      content:
        _sum:
          _state: GetInvoices.$.total
```

```
blocks:
  - id: box1
    type: Box
    properties:
      content:
        _sum:
          _number.parseInt:
            _state: GetInvoices.$.total
```

_state: GetInvoices contains
```
[
   {
      "id":3,
      "userid":3,
      "total":"22.00"
   },
   {
      "id":11,
      "userid":3,
      "total":"14.95"
   }
]
```

**Comment by bertovn** [comment, marked as answer]
I had task like this in my app, and it was resolved by [_array.reduce](https://docs.lowdefy.com/_array) function
My datastructure:
```
[
  {
    "Backend_name": "Test Group",
    "CPU_usage": "4",
    "HDD_usage": "59",
    "Hostname": "host1",
    "IP": "10.10.245.201",
    "RAM_usage": "50",
    "Sessions_count": 0,
    "State": "online",
    "Status": "online",
    "selected": false
  },
  {
    "Backend_name": "Test Group",
    "CPU_usage": "25",
    "HDD_usage": "59",
    "Hostname": "host2",
    "IP": "10.10.245.202",
    "RAM_usage": "82",
    "Sessions_count": 1,
    "State": "maint",
    "Status": "online",
    "selected": false
  },
  {
    "Backend_name": "Test Group",
    "CPU_usage": "8",
    "HDD_usage": "59",
    "Hostname": "host3",
    "IP": "10.10.245.203",
    "RAM_usage": "52",
    "Sessions_count": 0,
    "State": "online",
    "Status": "online",
    "selected": false
  }
]
```
and event block to join hostname value from each element in array is:

```
      - id: prepareDatatoSend
        type: SetState
        params:                            
          SelectedServersString: 
            _array.reduce:
              on:
                _state: SelectedServers
              callback:
                _function:
                  __string.concat:
                    - __args: 0
                    - __args: 1.Hostname
                    - ';'
```
and as result i have a ;-separated string
Please don't ask why i chose this way instead of _array.map))))

**Reply by kemeris2000** [reply]
Thank you [bertovn](https://github.com/bertovn) for pointing me to right direction.
My current solution is:

```
                blocks:
                  - id: box1
                    type: Box
                    layout:
                      span: 12
                    properties:
                      content:
                        _array.reduce:
                          on:
                            _state: GetInvoices
                          callback:
                            _function:
                              __sum:
                                - __args: 0
                                - __number.parseFloat:
                                    __args: 1.total
```
