### DISCUSSION TITLE
How to store value securely on server side

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1536] [Questions and Help] [answered]
I am validating user login via external API call. On successful login I need to store user_id value securely so user would not be able to change it. As I understand SetGlobal and SetState are not secure? Is it possible to use _user operator for this purpose?

**Comment by SamTolmay** [comment, marked as answer]
Hi @kemeris2000 

Are you using Lowdefy v3 or v4?

If you are using v3 the id might already be on the user object, depending on the provider used. There might also be a `sub` claim, which is the OpenID Connect user id standard claim. So you would access this using `_user: sub`. You might need to configure something at the provider to add the user id to the idToken from the provider.

In v4 you have move flexibility. You can use the [`auth.userFields`](https://docs-git-develop-lowdefy.vercel.app/auth-configuration) config option to map a value from the provider to the user object, or you can write a custom callback to add the user id to the user object. 

The V4 auth docs are currently a work in progress and are incomplete, but please ask if you have any questions

**Comment by kemeris2000** [comment]
Thank you [SamTolmay](https://github.com/SamTolmay) for reply.

My question was not clear enough.
I am using v3, my lowdefy application does not use OpenID provider. It authenticate user via HTTP post request using AxiosHttp connection. Basically my app is frontend for existing php script which provides API.
```
requests:
  - id: ValidateLogin
    type: AxiosHttp
    connectionId: webappphp_api
    responseType: json
    properties:
      method: post
      data: 
        identifier=xxx1&secret=xxx2&responsetype=json&action=ValidateLogin
```
on successful authentication user get response

```
{
    "result": "success",
    "userid": "1",
    "passwordhash": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "twoFactorEnabled": "false"
}
```


My requirement is to include "userid" to post fields in all future AxiosHttp requests without ability to change it from client side (I mean it should be stored on server side).

Is it possible to accomplish this?
