### DISCUSSION TITLE
Array filtering based on other array

### DISCUSSION THREAD

**Discussion by bertovn** [lowdefy/lowdefy#1537] [Questions and Help] [answered]
Hi team and once again thank you for this great product :)
I continue development of my app and in one of the pages  I'd like to have lists, where two arrays will be listed but one of them has to be filtered based on other.
E.g: 
array1 has values [host1,host2,host3,host4,host5]
array2 has values [host2,host5]
how can i filter array1 (maybe into brand new array?) to get only values which not listed in array2 (result i want to see is array with values [host1,host3,host4])
i tried something like this:

```
- id: set_free_workers
        type: SetState
        params:
          _log:
            free_workers:
              _log:
                _array.filter:
                  on:
                    _state: workers_names_array
                  callback:
                    _function:
                      _log:
                        __gt:
                          _log:
                            - _array.indexOf:
                                on: 
                                  _state: SelectedGroupDataWorkers
                                value:
                                  _args: 1
                            - 0
```
and this:

```
free_workers:
  _log:
    _array.filter:
      on:
        _state: workers_names_array
      callback:
        _function:
          _log:
            _array.includes:
              on:
                _log:
                  _state: SelectedGroupDataWorkers
              value: 
                _log:
                  _state: $
```
but without success :(
And one more proble

Any suggestions here?

**Comment by Gervwyk** [comment, marked as answer]
At a glace it is important to know that when you enter a `_function` operator all nested operators must be prefixed with an extra `_`, this implies order of execution (you could for example have operators with single `_`, then it would be evaluated during higher level execution instead of inside the function. See docs: https://docs.lowdefy.com/_function

With some logic corrections, I think your example code should be (I have not tested it):
```yaml
     - id: set_free_workers
        type: SetState
        params:
            free_workers:
                _array.filter:
                  on:
                    _state: workers_names_array
                  callback:
                    _function:
                        __eq:
                            - __array.indexOf:
                                on: 
                                  __state: SelectedGroupDataWorkers
                                value:
                                  __args: 0
                            - -1                
```

**Reply by bertovn** [reply]
Hi @Gervwyk and thank you for your answer, but it doesn't work too. As my investigation showed, ```__args: 0 ```  point returned 0 value, so the problem is that i cant pass to ```_array.indexOf``` current  element of ```workers_names_array```

**Reply by Gervwyk** [reply]
I suspect some other issue with your code or data format.

Consider the following example app which work and prints `[ "host1", "host3", "host4" ]`
```yaml
lowdefy: 4.0.0-rc.6
name: Lowdefy starter
pages:
  - id: welcome
    type: Box
    events:
      onMount:
        - id: init
          type: SetState
          params:
            workers_names_array:
              - host1
              - host2
              - host3
              - host4
              - host5
            SelectedGroupDataWorkers:
              - host2
              - host5
    blocks:
      - id: html
        type: Html
        properties:
          html:
            _json.stringify:
              - _array.filter:
                  on:
                    _state: workers_names_array
                  callback:
                    _function:
                      __eq:
                        - __array.indexOf:
                            on:
                              __state: SelectedGroupDataWorkers
                            value:
                              __args: 0
                        - -1
```
