### DISCUSSION TITLE
File download: need suggestions

### DISCUSSION THREAD

**Discussion by bertovn** [lowdefy/lowdefy#1541] [Questions and Help] [answered]
Hello dears :)
I have a UI with LowDefy and Flask app as API\backend
And now i got a problem, then i can't download file and have no idea how to do it. Flask returns file with ```send_from_directory``` function and i can store it with SetState but have no idea how to save it to client computer. Any suggestion will be appreciated

UPD:
Tried to code a function in JS to click the link (in ```lowdefy.yaml```):
```
lowdefy: 3.23.3
name: start
connections:
  - id: script_api
    type: AxiosHttp
    properties:
      baseURL: http://localhost:5001/
app:
  html:
    appendHead: |
      <script>
      function OpenInNewTabWinBrowser(url) {
        var link = document.createElement("a")
        link.href = url
        link.target = "_blank"
        link.click()
      }
      </script>     
```
and call from other page ```my_apps``` looks like:
```
                - id: filedownload
                  type: SetState
                  params:
                    _log:
                      FileString: 
                        _nunjucks: http://localhost:5001/getmyapp?username={{user_details.preferred_username}}&filename={{icafilename}}
                - id: OpenInNewTabWinBrowser                  
                  type: JsAction
                  params:
                    name: OpenInNewTabWinBrowser
                    args:
                      - _state: FileString
```
but got an error. the same result if i import function via files in ./public folder
![image](https://user-images.githubusercontent.com/54134702/226607268-dbc92493-e837-4476-a95c-bfe40aceaf37.png)

**Comment by bertovn** [comment, marked as answer]
Resolved by JsAction action, but found some moment that i have to share for other, i suppose :)
The documentation recommends create a separate module for each JS function in your solution, import this module in ```public/modules.js``` file and add this final module in ```lowdefy.yaml```, but it doesn't work because in this way app gets an error of MIME types ("Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec."). So, as workaround i just added function code in ```modules.js``` and function was imported. One more point about function's arguments, it will not get any arguments if you'l not list ```context``` as first arg. 
and as final solution:
function call from Lowdefy:
```               - id: generatefile
                  type: Request
                  params:
                    - generatefile #generates file in backend
                - id: filename
                  type: SetState
                  params:
                    _log:
                      icafilename:
                          _request: generatefile.data  #returns filename
                - id: filedownload
                  type: SetState
                  params:
                    _log:
                      FileString: 
                        _nunjucks: http://localhost:5001/getmyapp?username={{user_details.preferred_username}}&filename={{icafilename}} #creates link to call API function which will be processed by FLASK side
                - id: OpenInNewTabWinBrowser                  # calls JS function and file downloads :)
                  type: JsAction
                  params:
                    _log:
                      name: OpenInNewTabWinBrowser
                      args:
                        _log:
                          - _state: FileString
```

**Reply by SamTolmay** [reply]
Hi @bertovn 

Glad you got this working. Did you try to use the Link action? Ideally something like this should work as well:
```yaml
- id: link_url
  type: Link
  params:
    url:
      _nunjucks: http://localhost:5001/getmyapp?username={{user_details.preferred_username}}&filename={{icafilename}}
    newTab: true
```
