### DISCUSSION TITLE
Anchor with Data URL from Request Object

### DISCUSSION THREAD

**Discussion by gramian** [lowdefy/lowdefy#1542] [Questions and Help] [answered]
Dear All,

I am trying to add an anchor display block containing a (JSON) data URL which is build from a request object:

```yaml
- id: dataurl
  type: Anchor
  properties:
    newTab: true
    title: My Data URL
    href:
      _string.concat:
        - data:application/json;,
        - _uri.encode:
            _json.stringify:
              on:
                _request: my_request.data
```
This results in a successful build but the link is disabled and a loading icon is spinning next to it.

A static data URL like this:
```yaml
- id: dataurl
  type: Anchor
  properties:
    newTab: true
    title: My Data URL
    href: data:application/json;,{"test":"Hi"}
```
works as expected.

So, I would like to ask if anchor hrefs just cannot be assembled dynamically or if I am doing something wrong here?

Thank you for your help

**Comment by gramian** [comment]
I made some more test cases also with types `Html` and `DangerousHtml` (by building a link via an `<a href="data:..">Test</a>` tag). None of it works as soon as a the `href` is prefixed by `data:`. Are data URLs just not permitted in Lowdefy as link targets or should I file a bug report?

Thank you for any insights

**Reply by SamTolmay** [reply, marked as answer]
Hi @gramian 

We use [DOMPurify](https://github.com/cure53/DOMPurify) to sanitise HTML content. It looks like DOMPurify sanitises data URI's, so maybe something like this might work (Not able to test this right now, and their docs aren't super clear on this):

```yaml
id: data_uri
type: DangerousHtml
properties:
  html: <a href="data:..">Test</a>
  DOMPurifyOptions:
    ADD_DATA_URI_TAGS:
      - a
```
