### DISCUSSION TITLE
Tabs

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1546] [Questions and Help]
Hi, I encountered some style issues when trying to use ```Tabs```. The tab contains some ```Input Blocks```, but when using ```DateSelector```, selecting the date box cannot display all of them. If I set the height of the tab to display it, but I don't want to do so, is there a better way?

Img:
![image](https://user-images.githubusercontent.com/72787010/227127394-4f56a637-1573-4ab7-8a2a-7a92f25aeeb5.png)

**Comment by Gervwyk** [comment]
Hi @xiaoxiji1234 

Please provide a simple reproduction of your config which will help us to provide faster help.

The following config was tested and does not have the issue you indicated. Please provide your config for us to debug.
Config:
```yaml
lowdefy: 4.0.0-rc.7
name: Lowdefy starter
pages:
  - id: welcome
    type: Box
    style:
      padding: 20
    blocks:
      - id: block_id
        type: Tabs
        style:
          border: 1px solid red
        properties:
          tabs:
            - key: tab1
        areas:
          tab1:
            blocks:
              - id: c
                type: NumberInput
                layout:
                  span: 12
                properties:
                  label:
                    inline: true
              - id: num
                type: DateSelector
                layout:
                  span: 12
                properties:
                  label:
                    inline: true
```
<img width="1419" alt="Screenshot 2023-04-17 at 10 28 51" src="https://user-images.githubusercontent.com/7165064/232429066-f12b602f-e49c-4d71-9e44-569ee73861cb.png">

**Reply by xiaoxiji1234** [reply]
Hi, @Gervwyk 
My code
```yaml
lowdefy: 3.23.2
name: Lowdefy starter
pages:
  - id: welcome
    type: PageHSCF
    blocks:
      - id: block_id
        type: Tabs
        style:
          border: 1px solid red
        properties:
          tabs:
            - key: tab1
        areas:
          tab1:
            blocks:
              - id: c
                type: NumberInput
                layout:
                  span: 12
                properties:
                  label:
                    inline: true
              - id: num
                type: DateSelector
                layout:
                  span: 12
                properties:
                  label:
                    inline: true
```
![image](https://user-images.githubusercontent.com/72787010/232650221-d2164fb0-401a-45ce-a4a9-45d15211f060.png)
