### DISCUSSION TITLE
lowdefy-example-crud brands and products seems to be displayed using diffrent methods?

### DISCUSSION THREAD

**Discussion by JonBendtsen** [lowdefy/lowdefy#1552] [Questions and Help]
How come lowdefy-example-crud brands and products seems to be displayed using different methods?

brands.yaml
```
      - id: brands_table
        type: AgGridAlpine
```

products.yaml
```
id: product_list # A List block to render the following blocks for all items in the product_list page state variable.
type: List
```

What I am trying to do is to fetch and display all rows from a google sheet, but using the product method I am only able to get one field listed, sure one from each row in the sheet, but still only 1 field and I wanna see many fields.

```
      - id: dance_registrations
        type: ButtonSelector
        required: true
        properties:
          title: Dance Registrations
          size: large
          options:
            # The list of selector options are populated from the result of our get_employees request. Here we make use of the mql aggregate operator to modify our request response and sort according to label. The mql.aggregate operator is a client side implementation to run aggregations on client side data using an implementation of MongoDB's Aggregation language.
            _mql.aggregate:
              on:
                _if_none: # Since we are fetching the `get_employees` with onInitAsync, `_request: get_employees` will be `null` until a request response is received. Checking for _if_none here handles the non-array type `on` input error until the data is returned be the request.
                  - _request: all_registrations
                  - []
              pipeline:
                - $project:
                    value: $created_date
                    label: $created_date
                - $sort:
                    label: 1
```
