### DISCUSSION TITLE
Repetead actions without click

### DISCUSSION THREAD

**Discussion by thanosits** [lowdefy/lowdefy#1555] [Questions and Help] [answered]
Could be repeated an event several times, without clicking the mouse;
I mean repeating an action after a certain period of time. (no Wait action, because it's a simple delay for one time action).

**Comment by Gervwyk** [comment]
Hi @thanosits 

Do you mean something like periodically polling a request for example?

**Reply by konstchri** [reply]
Yes, is this possible?

**Reply by Gervwyk** [reply, marked as answer]
This isn't currently supported out of the box. The Wait action provides a one-time delay, but there's no built-in interval/polling mechanism.

Workaround: You can create a custom block plugin that uses setInterval internally and triggers events via methods.triggerEvent. This block could expose properties like interval (ms) and fire an onInterval event that you can attach actions to.

This is on our roadmap - we're planning to add interval/polling support in a future release.

For now:
  Workaround: Create a custom block plugin:
```js
  // plugins/blocks/Interval/Interval.js
  function Interval({ methods, properties }) {
    React.useEffect(() => {
      if (!properties.ms) return;
      const id = setInterval(() => {
        methods.triggerEvent({ name: 'onInterval' });
      }, properties.ms);
      return () => clearInterval(id);
    }, [properties.ms]);
    return null;
  }

  Interval.meta = { category: 'context' };
  export default Interval;
```

 Usage:
```yaml
  - id: poller
    type: Interval
    properties:
      ms: 5000
    events:
      onInterval:
        - id: refresh_data
          type: Request
          params: get_latest_data
```

 Consider the plugins docs and starter repo to get started with plugins.
 https://github.com/lowdefy/lowdefy-example-plugins
 https://docs.lowdefy.com/plugins-introduction
