### DISCUSSION TITLE
Reuse AxiosHttp connection with parameter

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1557] [Questions and Help] [answered]
I need to fetch same request multiple times with dynamic "invoiceid" value.
Is it possible to accomplish this with v3?

```
requests:
  - id: GetInvoices
    type: AxiosHttp
    connectionId: whmcs_api
    responseType: json
    properties:
      method: post
      data: identifier=TLvnYz&secret=sxa2LwiuSI7&action=GetInvoices&invoiceid=3
events:
  onEnter:
    - id: fetch_GetInvoices
      type: Request
      params: GetInvoices 
```

**Comment by SamTolmay** [comment, marked as answer]
Hi @kemeris2000 

I think you should be able to do this (this will send the body as JSON)

```yaml
requests:
  - id: GetInvoices
    type: AxiosHttp
    connectionId: whmcs_api
    responseType: json
    properties:
      method: post
      data:
        identifier: TLvnYz
        secret: sxa2LwiuSI7
        action: GetInvoices
        invoiceid:
          _state: invoiceid
```

Otherwise you could also do

```yaml
requests:
  - id: GetInvoices
    type: AxiosHttp
    connectionId: whmcs_api
    responseType: json
    properties:
      method: post
      data: 
        _string.concat:
          - identifier=TLvnYz&secret=sxa2LwiuSI7&action=GetInvoices&invoiceid=
          - _state: invoiceid
```
or:
```yaml
requests:
  - id: GetInvoices
    type: AxiosHttp
    connectionId: whmcs_api
    responseType: json
    properties:
      method: post
      data: 
        _nunjucks:
          template: identifier=TLvnYz&secret=sxa2LwiuSI7&action=GetInvoices&invoiceid={{ invoiceid }}
          on:
            invoiceid:
              _state: invoiceid
```
