### DISCUSSION TITLE
Lowdefy4.0DocsError

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#1558] [Questions and Help] [answered]
Hi, I found that there is an issue with the configuration of Next Auth Providers in the Lowdefy4.0 document currently being written, as shown in the document example:
```yaml
lowdefy: 4.0.0-rc.7
providers:
  - id: github
    type: GitHubProvider
    properties:
      clientId:
        _secret: GITHUB_CLIENT_ID
      clientSecret:
        _secret: GITHUB_CLIENT_SECRET
```
I followed the example to write my app and logged in with an error, and then I modified the code to successfully log in.
My code
```yaml
lowdefy: 4.0.0-rc.7
auth:
  providers:
    - id: github
      type: GitHubProvider
      properties:
        clientId:
          _secret: GITHUB_CLIENT_ID
        clientSecret:
          _secret: GITHUB_CLIENT_SECRET
```
