### DISCUSSION TITLE
How to preserve global data on page refresh

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1560] [Questions and Help] [answered]
I am populating global data "GetClientsDomains" from request on page "page1" and accessing this global data on page "page2". 
Once I refresh page "page2" on my browser, global data disappears. What could be a problem? lowdefy v3.

page1:

```
requests:
  - id: GetClientsDomains
    type: AxiosHttp
    connectionId: whmcs_api
    responseType: json
    properties:
      method: post
      data: identifier=TLvnY2&secret=U7RY&responsetype=json&action=GetClientsDomains&clientid=3
events:
  onEnter:
    - id: fetch_GetClientsDomains
      type: Request
      params: GetClientsDomains
    - id: state_GetClientsDomains
      type: SetGlobal
      params:
        GetClientsDomains:
          _request: GetClientsDomains.data.domains.domain

```

page2:
```
blocks:
  - id: content_card
    type: Card
    layout:
      size: 1000 # Set the size of the card so it does not fill the full screen.
      contentGutter: 20 # Make a 16px gap between all blocks in this card.
    blocks:
      - id: mark_1
        type: Markdown
        properties:
          content:
            _json.stringify:
              - _log:
                  _global: GetClientsDomains
```

My lowdefy server is behind reverse proxy.
I am starting development server via systemd:

```
[Service]
ExecStart=/usr/bin/npx lowdefy@latest dev
RestartSec=10
Restart=always
User=www-data
Group=www-data
WorkingDirectory=/var/lib/lowdefy/web

# Output to syslog
StandardOutput=journal
StandardError=journal

Environment=PATH=/usr/bin:/usr/local/bin

[Install]
WantedBy=multi-user.target

```
