### DISCUSSION TITLE
Tabs - How to change the activeKey ?

### DISCUSSION THREAD

**Discussion by vicam001** [lowdefy/lowdefy#1561] [Questions and Help] [answered]
I am starting to use the block "Tabs" (in 4.0.0-rc.7) and I would like how I can change the tab from another part of the app (e.g. I would like to click a button placed within the area of the active tab, to validate the fields within that tab and then if everything is fine, move to the tab to the right, resembling a wizard)

I suspect this could be achieve if the Tabs block would expose any method to be called with the action 'CallMethod' . I have failed to find this in the documentation and after trying to guess a few times I give up.

Of course my first attempt was to change the state with the action "SetState", so, if my tabs block has the id 'my_tabs_block" as below:

```yaml
- id: tabs_block
  type: Tabs
  layout:
    size: 800
    contentGutter: 16
    contentJustify: center
  properties:
    animated: false
    tabs:
      - key: step1
        title: Step 01
        icon: AiFillCheckCircle
        disabled: false
      - key: step2
        title: Step 02
        icon: AiFillCheckCircle
        disabled: false

```

I try 

```yaml
- id: set_state
  type: SetState
  params:
    tabs_block: step2
```

or
```yaml
- id: set_state
  type: SetState
  params:
    tabs_block.activeKey: step2
```

Any possible workaround here or suggestion on how to achieve a "wizard" like experience? 
Many thanks in advance!

**Comment by SamTolmay** [comment, marked as answer]
Hi @vicam001 

The tabs block has an `activeKey` property that reads from state:
```yaml
- id: tabs_block
  type: Tabs
  layout:
    size: 800
    contentGutter: 16
    contentJustify: center
  properties:
    animated: false
    activeKey:
      _state: active_tab
    tabs:
      - key: step1
        title: Step 01
        icon: AiFillCheckCircle
        disabled: false
      - key: step2
        title: Step 02
        icon: AiFillCheckCircle
        disabled: false
```
and
```yaml
- id: set_step_2
  type: SetState
  params:
    active_tab: step2
```
