### DISCUSSION TITLE
How to use AG-grid setFilterModel method?

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1566] [Questions and Help] [answered]
I am unable to find an example on how to set the setFilterModel model.
I would appreciate for help.

model:

```
{
    domainname: {
        filterType: 'text',
        type: 'Contains',
        filter: '.de'
}

```

```
- id: block_id
  type: TextInput
  events:
    onChange:
	  - id: filter
	    type: CallMethod
	    params:
		  blockId: table
		  method: setFilterModel                
- id: table
  type: AgGridAlpine
  properties:
    columnDefs:
	  - headerName: Domenas
	    field: domainname
	    width: 200
	  - headerName: Registracijos data
	    field: regdate
	    width: 170
```

**Comment by JohannMoller** [comment, marked as answer]
Hi @kemeris2000,

You are very close to the solution, the only thing you need is to pass the filter model to the `setFilterModel` method's args, and to set `filter: true` on the columns which you want to filter on. The below config should do what you want to do:

```yaml
- id: block_id
  type: TextInput
  events:
    onChange:
      - id: filter
        type: CallMethod
        params:
          blockId: table
          method: setFilterModel
          args: ## Pass the model to the method's args
            - domainname:
                filterType: 'text'
                type: 'Contains'
                filter:
                  _state: block_id ## Here we are reading your text input's state value directly instead of hardcoding '.de'
- id: table
  type: AgGridAlpine
  properties:
    rowData:
      - domainname: 'www.google.com'
        regdate: 2020-01-01
      - domainname: 'www.google.de'
        regdate: 2021-01-01
      - domainname: 'www.blabla.com'
        regdate: 2023-01-01
      - domainname: 'www.blabla.de'
        regdate: 2010-01-01
    columnDefs:
      - headerName: Domenas
        field: domainname
        filter: true ## Activate the filter on the columns which should be filterable
        width: 200
      - headerName: Registracijos data
        field: regdate
        width: 170
```

I hope this solves your problem.
