### DISCUSSION TITLE
Is it possible to reference list of actions in another list

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1570] [Questions and Help] [answered]
Hi,
is it possible to reference list of actions in another list. As I understand _array.flat does not work here as _ref is build time operator.
I would appreciate suggestions

pages/user_services/actions/get_Clients.yaml:
```
- id: state2
  type: SetState
  params:
    state2: value2
- id: state3
  type: SetState
  params:    
   state3: value3
```

```
events:
  onEnter:
    - id: state1
      type: SetState
      params:
        state1: value1
    - _ref:
        path: pages/user_services/actions/get_Clients.yaml
```

```
events:
  onEnter:
    _array.flat:
      on:
        - id: state1
          type: SetState
          params:
            state1: value1
         - _ref:
              path: pages/user_services/actions/get_Clients.yaml
```

**Comment by Gervwyk** [comment, marked as answer]
Hi @kemeris2000 
So the list of actions are not evaluated during runtime, it is only initialized with the provided list. But on v4 you can use the `_build` operator to flatten the array during build which should provide the desired config output in this case.
For example:
```yaml
events:
  onEnter:
    _build.array.flat:
      on:
         - - id: state1
             type: SetState
             params:
                state1: value1
         - _ref:
              path: pages/user_services/actions/get_Clients.yaml
```
Note that you also need to pass two arrays to Array.flat method.
