### DISCUSSION TITLE
Knex PostgreSQL connections

### DISCUSSION THREAD

**Discussion by bertovn** [lowdefy/lowdefy#1577] [Questions and Help] [answered]
Hello team :)
Developing some CRUD application around PSQL database and get some problems with requests to database:
![image](https://user-images.githubusercontent.com/54134702/235003131-0d6c1c07-a46e-4e86-bea5-b333696ab771.png)
My code:

```
lowdefy: 3.23.3
name: Lowdefy starter

connections:
  - id: postgres
    type: Knex
    properties:
      client: postgres
      connection:
        user:
          _secret: PG_USER
        host:
          _secret: PG_HOST
        database:
          _secret: PG_DB
        password:
          _secret: PG_PASSWORD
```
```
id: userslist
type: PageSiderMenu
properties:
  title: Пользователи
requests:
  - id: GetAllUsersRequest
  #   type: KnexRaw
  #   connectionId: postgres
  #   properties:
  #     query: select * from user_list
    type: KnexBuilder
    connectionId: postgres
    properties:
      query:
        - select:
            - '*'
        - from:
            - user_list
blocks:
    - id: GetUsersButton
      type: Button
      properties:
        size: large
        title: Button
        color: '#1890ff'
      events:
        onClick:
          - id: GetAllRecords
            type: Request
            params: GetAllUsersRequest
          - id: GetAllUsersVar
            type: SetState
            params:
              _log:
                varRecords: GetAllUsersRequest.data
```
also i got the error 
![image](https://user-images.githubusercontent.com/54134702/235003869-dc7b3379-f659-46c4-bcc5-a02deef872da.png)
but required depencies were installed

i'm getting error in both cases if i use KnexRaw or KnexBuider
Credentials are 100% correct

Thank you in advance :)

**Comment by bertovn** [comment, marked as answer]
Found solution and realize myself as stupid bird :(
Just added 2 rows in connector and it started work as expected:
```
connections:
  - id: postgres
    type: Knex
    properties:
      client: pg
      connection:
        user:
          _secret: PG_USER
        host:
          _secret: PG_HOST
        database:
          _secret: PG_DB
        password:
          _secret: PG_PASSWORD
      version: '15.2'
      searchPath: 'public'
```
BTW it is not clear in appropriate documentation's page :(
Thanks @vicam001 for post with requests limitation :)
