### DISCUSSION TITLE
Open a modal window when clicking on a row in a AgGrid table

### DISCUSSION THREAD

**Discussion by Maxim270693** [lowdefy/lowdefy#1584] [Questions and Help] [answered]
modal window should open on click on each row, thanks

- id: users_table
  type: AgGridAlpine
  properties:
    rowData:
      - id: 1
        name: 'Jim'
        email: 'alex.smith@gmail.com'
        address: 'Spain'
      - id: 2
        name: 'Marshall Smith'
        email: 'bob.london.smith@gmail.com'
        address: 'London'
    columnDefs:
      - headerName: ID
        field: id
        width: 70
      - headerName: Name
        field: name
        width: 198
      - headerName: Email
        field: email
        width: 198
      - headerName: Address
        field: address
        width: 620

**Comment by Gervwyk** [comment, marked as answer]
Hi @Maxim270693 
You can add the following to do this:
```yaml
- id: users_table
  type: AgGridAlpine
  ...
  events:
    onRowClick:
      - id: set_selected
        type: SetState
        params:
          selected:
            _event: row 
      - id: open_modal
        type: CallMethod
        params:
          blockId: foo_modal
          method: toggleOpen
- id: foo_modal
  type: Modal
  blocks:
    - id: selected.name
      type: TextInput
  events:
    onClose:
      - id: reset
        type: Reset
```
The event executes to trigger the modal. You'd probably also want to set state to access the selected data.
