### DISCUSSION TITLE
Auth not configured

### DISCUSSION THREAD

**Discussion by Maxim270693** [lowdefy/lowdefy#1587] [Questions and Help] [answered]
Hello, please help me with authorization.

created .env file
OpenID Connect provider - Auth0
JWT_SECRET - created
login on screenshot 3

Error while logging in

Any help would be helpful, thanks

![image](https://github.com/lowdefy/lowdefy/assets/77190011/a6e1d1db-e0c5-46ec-bfa9-aa80c110be6b)
![image](https://github.com/lowdefy/lowdefy/assets/77190011/6f6a1d45-e642-4dd2-b4b2-590440613bad)
![image](https://github.com/lowdefy/lowdefy/assets/77190011/6434ba07-cb51-4bd2-9e38-053d73a9a749)
![image](https://github.com/lowdefy/lowdefy/assets/77190011/eec52fa9-3134-4ef1-b8a0-ed29f565f495)
![image](https://github.com/lowdefy/lowdefy/assets/77190011/cd8e8737-3d1d-4c1b-a88d-949e4aaa03ab)

**Comment by SamTolmay** [comment, marked as answer]
Hi @Maxim270693 

> NB: PLEASE UPDATE YOUR AUTH0 CLIENT ID AND SECRET AS YOU HAVE SHARED THESE PUBLICLY AND THIS IS A SECURITY RISK. YOU CAN CREATE A NEW "APPLICATION" IN AUTH0 TO DO THIS.

There are a few things you should be doing:
- You are using Auth0, so the provider should be of type `Auth0Provider` and not `CognitoProvider`
- The OPENID_DOMAIN should start with `https://`
- The LOWDEFY_SECRET_JWT_SECRET environment variable name should be changed to `NEXTAUTH_SECRET`

Also, when using and OpenID Connect flow like Auth0, the user is directed to a page hosted by Auth0 where they fill in their username and password. When the `Login` action is called, a state variable is created by the Lowdefy server, and the user is redirected to Auth0. Once they have authenticated on Auth0, they are redirected back. So you login page should look something like this:
```yaml
id: login
type: Box
events:
  onMount:
    - id: logged_in_redirect
      type: Link
      skip:
        _eq:
          - _user: id
          - null
      params:
        pageId: home
    - id: login
      type: Login
      skip:
        _ne:
          - _user: id
          - null
      params:
        providerId: auth0
        callbackUrl:
          pageId: home
```
This will redirect the user to Auth0, and then to a page with id `home` once logged in. This page should be a public page, and you can set it as the homePage of your app if you want.

You can read more on user authentication in our development docs here: https://docs-git-develop-lowdefy.vercel.app/users-introduction
