### DISCUSSION TITLE
question about example repo of k8s

### DISCUSSION THREAD

**Discussion by 13316090972** [lowdefy/lowdefy#1591] [Questions and Help]
I feel puzzled that the lowdefy image metioned by `lowdefy-example-k8s/config-simple-deploy/deploy.yaml` is `imvegeta/img_lowdefy`,what's that?
``` yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lowdefy
  namespace: default
  labels:
    app: lowdefy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lowdefy
  template:
    metadata:
      name: lowdefy
      labels:
        app: lowdefy
    spec:
      containers:
        - name: lowdefy
          image: imvegeta/img_lowdefy
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: LOWDEFY_SERVER_PORT
              value: '3000'
          imagePullPolicy: Always
```
