### DISCUSSION TITLE
How to properly style default menu?

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1604] [Questions and Help] [answered]
Can't find how to decrease default menu height, I would appreciate any help. My failed attempt:

```
menus:
  - id: default
    style:
      '#home_menu':
        line-height: '40px !important;'
      .ant-layout-header:
        line-height: '40px !important;'
      ant-layout-header:
        line-height: '40px !important;'
    links:
      - id: b4a1d739-3595-412e-859f-215246cc32ab1
        type: MenuLink
        pageId: home
        properties:
          title: Home
          icon: HomeOutlined
```

![image](https://github.com/lowdefy/lowdefy/assets/48207709/702ce582-aa94-4675-b19c-aee6d0355698)
