### DISCUSSION TITLE
Menu visible property

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1606] [Ideas and feature requests]
I suggest to add "visible" option for MenuLink and MenuGroup menu items.

**Comment by Gervwyk** [comment]
Thanks, @kemeris2000. This makes sense. I thikn this would be a useful feature, however, already the many is filtered based on user roles. So you can use the menu in combination with roles and the user will only see the pages which they have access to.

**Reply by kemeris2000** [reply]
Thank you, I am aware of the user roles.

**Comment by kemeris2000** [comment]
Any plans to implement this in near future? Use case for example is to hide "Login"/"Register" menu items when user is authenticated. As the workaround I am using public/styles.less. Maybe there is other options?

**Reply by SamTolmay** [reply]
Hi @kemeris2000 

Both the `PageHeaderMenu` and `PageSiderMenu` have a `menu` property, that can be used to overwrite the lowdefy menu options. 
You could use operators to filter or construct the menu items from the menu.

So you could do (unfortunately I am unable to test this, so it might not work, but I hope it illustrates the idea):
```yaml
id: block_id
type: PageHeaderMenu
properties:
  menu:
    links:
      _array.concat:
        - _menu: default.links
        - _if:
            test:
              _eq:
                - _user: sub
                - null
            then: []
            else:
              - id: home
                type: MenuLink
                pageId: login
                properties:
                  title: Login
```

The other option is to add a login button in the header area of the page, and not as a menu item.
