### DISCUSSION TITLE
Alternative to v4's _build operator in v3.23.3 or how to access env variables at build time

### DISCUSSION THREAD

**Discussion by vicam001** [lowdefy/lowdefy#1614] [Questions and Help]
Hi, I have integrated Algolia Instantsearch.js into my Lowdefy v3.23.3 app and in order to control which variables (e.g. application_id, api_key, index_name) I pass on depending on the environment (e.g. dev, test, prod) I would need to pass as arguments to the custom code as shown below (ideally)

public/algoliaInstantSearch.js
```js
function initInstantSearch(context,var_app_id,var_api_key,var_index_name) {

 <!-- My logic goes here -->

// Register the JsAction for the Lowdefy app to use.
window.lowdefy.registerJsAction("initInstantSearch", initInstantSearch);

```

```yaml
- id: init_instantsearch
  type: JsAction
  skip: false
  params:    
      name: initInstantSearch
      args:
        - _secret: ALGOLIA_APPLICATION_ID
        - _secret: ALGOLIA_API_KEY
        - _secret: ALGOLIA_INDEX_NAME

```

The example above does not work because the _secret operator is a server only operator, so does not load the necessary values from .env

I would like to have (in v3.23.3 ) something like :

```yaml

- id: init_instantsearch
  type: JsAction
  skip: false
  params:    
      name: initInstantSearch
      args:
        - _build.env: ALGOLIA_APPLICATION_ID
        - _build.env: ALGOLIA_API_KEY
        - _build.env: ALGOLIA_INDEX_NAME

```

Is it possible ? 

Thanks a lot in advance for your support.
