### DISCUSSION TITLE
How can I make a AxiosHttp request with dynamically generated path parameters in Lowdefy?

### DISCUSSION THREAD

**Discussion by jonathanhoss** [lowdefy/lowdefy#1656] [Questions and Help] [answered]
👋 Hello

I'm working (with version `4.0.0-rc.10`) on a task where I need to send a GET request to an API, and the challenge is to create dynamic path parameters based on user input. Essentially, I want users to be able to provide certain values that will be incorporated into the path of the GET request.

Currently, I've tried using Nunjucks Templates to pass in the Path Parameter, and it works perfectly when using hard-coded values like `on: order_id: "1"`. However, I'm encountering issues when trying to access the state.

This seems like a common use case, yet I haven't been able to find a suitable example.

Here's an excerpt from my YAML configuration:

```yaml
id: get-order
type: PageHeaderMenu

requests:
  - id: get_order
    type: AxiosHttp
    connectionId: api
    properties:
      url:
        _nunjucks: 
          template: '/orders/{{ order_id }}'
          on:
            _state: true
            
blocks:
      - id: order_id
        type: TextInput
        properties:
          title: Order ID
      - id: submit_button
        type: Button
        layout:
          span: 12
        properties:
          title: Submit
          block: true
        events:
          onClick:
            - id: get_order_button
              type: Request
              params: get_order
            - id: reset
              type: Reset

      - id: get_order_md
        type: Markdown
        properties:
          content:
            _string.concat:
              - |
                ```yaml
              - _yaml.stringify:
                  - _log:
                    data:
                      _request: get_order
              - |
                ```
```

Could you please provide guidance on how to properly incorporate the dynamic path parameters based on user input into the GET request?

Thank you for your help! 🙏

**Comment by jonathanhoss** [comment, marked as answer]
Found the solution. [Connections and Requests](https://docs.lowdefy.com/connections-and-requests)

My now working YAML configuration:

```yaml
id: get-order
type: PageHeaderMenu

requests:
  - id: get_order
    type: AxiosHttp
    connectionId: api
    payload:
      id:
        _state: order_id
    properties:
      url:
        _string.concat:
          - /orders/
          - _payload: id
            
blocks:
      - id: order_id
        type: TextInput
        properties:
          title: Order ID
      - id: submit_button
        type: Button
        layout:
          span: 12
        properties:
          title: Submit
          block: true
        events:
          onClick:
            - id: get_order_button
              type: Request
              params: get_order
            - id: reset
              type: Reset

      - id: get_order_md
        type: Markdown
        properties:
          content:
            _string.concat:
              - |
                ```yaml
              - _yaml.stringify:
                  - data:
                      _request: get_order.data
              - |
                ```
```
