### DISCUSSION TITLE
GraphQL connection plugin

### DISCUSSION THREAD

**Discussion by SamTolmay** [lowdefy/lowdefy#1671] [Ideas and feature requests]

**Comment by ad-si** [comment]
For anyone looking for a workaround: This is already possible with the `AxiosHttp` module.
Here a short example:

```yaml
lowdefy: 3.23.2
name: Lowdefy GraphQL Example

connections:
  - id: graphql_api
    type: AxiosHttp
    properties:
      baseURL: https://countries.trevorblades.com

pages:
  - id: Continents
    type: PageHeaderMenu
    requests:
      - id: continents_request
        type: AxiosHttp
        connectionId: graphql_api
        properties:
          url: /
          method: post
          data:
            query: |
              query {
                continents {
                  name
                }
              }

    events:
      onEnter:
        - id: fetch_continents
          type: Request
          params: continents_request

        - id: set_continents
          type: SetState
          params:
            continents_list:
              _request: continents_request.data.data.continents

    blocks:
      - id: title_main
        type: Title
        properties:
          content: Continents

      - id: continents_list
        type: List
        blocks:
          - id: continent_container_$
            type: Box
            style:
              background: white
              margin: 10
              padding: 10
            blocks:
              - id: continent_title_$
                type: Title
                properties:
                  level: 3
                  content:
                    _state: continents_list.$.name
```

A dedicated GraphQL module would be cool nevertheless!
