### DISCUSSION TITLE
API endpoints/webhooks/data pipelines

### DISCUSSION THREAD

**Discussion by SamTolmay** [lowdefy/lowdefy#1674] [Ideas and feature requests]
Depends on #640, #641 

A feature to expose a rest API endpoint that executes a directed acyclic graph (DAG) of requests/actions. These could be called by the Lowdefy app, or from an external service, or could execute on a cron schedule. 

One use case is similar to Zapier or Apache Airflow, to run a set of data jobs.

These could also be used instead of requests on an app, especially if the requests need to be called from more than one page, or if the action requires multiple requests.

The schema should support the simple use case, which is an array of jobs, but should also support a branching DAG.

Proposed schema:
```
endpoints:
  - id: simple_api
    jobs:
      - id: req1
        type: Type
      - id: req2
        type: Type
  - id: complex_api
    jobs:
      branch1:
        jobs:
          - id: req1
            type: Type
          - id: req2
            type: Type
      branch2:
        jobs:
          try:
            - id: req3
              type: Type
          catch:
            - id: req4
              type: Type
      branch3:
        dependsOn:
          - branch1
          - branch2
        jobs:
          - id: req5
            type: Type
          - id: respond
            type: Type
```
