### DISCUSSION TITLE
Define HTTP header in Link action?

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1678] [Questions and Help] [answered]
Is it possible to define HTTP header (Authorization) in Link action (Lowdefy 4.0.0-rc.10)?

**Comment by SamTolmay** [comment]
Hi @kemeris2000 

The Link action uses `window.open` which does not allow you to set headers. Most web standards do not allow you net headers like that.
https://stackoverflow.com/questions/4325968/window-open-with-headers
https://developer.mozilla.org/en-US/docs/Web/API/Window/open

Maybe you could use the `Fetch` action? I see it isn't documented, but it uses the standard fetch params:
https://developer.mozilla.org/en-US/docs/Web/API/fetch
```yaml
id: fetch
type: Fetch
params:
  - https://example.com
  - method: GET
    headers:
       Authorization: Bearer ...
     
```

**Comment by kemeris2000** [comment]
Thank you for reply [SamTolmay](https://github.com/SamTolmay).
Never tried Fetch before. I am looking the way to load [NoVNC client](https://github.com/novnc/noVNC) from external website into new window or iframe. According to fetch documentation it is possible to get text string of HTML with Fetch text() method. 
Question is how to get body of fetch response and render it? with _actions and Html display block?

**Reply by SamTolmay** [reply]
Have you tried using an iframe in an Html block? You need to whitelist some tags with DOMPurify, by default we purify tags that might be a security issue. This is an iframe of a youtube video in the docs as an example:

```yaml
id: tutorial_video
type: DangerousMarkdown
properties:
  DOMPurifyOptions:
    ADD_TAGS:
      - iframe
    ADD_ATTR:
      - allowfullscreen
      - allow
      - frameborder
  content: |
    <iframe
      width="800"
      height="470"
      src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
    </iframe>
```

**Comment by kemeris2000** [comment]
I just did a quick test, fetching json file in app public folder:

```
- id: fetch
  type: Fetch
  params:
    - https://mysite.com/test.json
    - method: GET
      mode: same-origin
- id: 006c17eb-8a87-43cb-8aa2-bbf4efd050a1
  type: SetState
  params:
    fetch_data:
      _actions: fetch
```

I always getting empty response. Am I missing something obvious?

```
- id: 4c7a1f98-946b-482e-a3a9-333a462ddd5e
  type: Markdown
  properties:
    content:
      _json.stringify:
        - _state: fetch_data

{ "type": "Fetch", "response": {}, "index": 2 }
```

**Reply by SamTolmay** [reply, marked as answer]
Maybe try:
```yaml
- id: fetch
  type: Fetch
  params:
    - https://mysite.com/test.json
    - method: GET
      mode: same-origin
    - json
```
Alternatively
```yaml
- id: fetch
  type: Fetch
  params:
    url: https://mysite.com/test.json
    options:
      method: GET
      mode: same-origin
    responseFunction: json
```
