### DISCUSSION TITLE
Consider supporting more than just yaml or json for configuration (cue, typescript, etc)

### DISCUSSION THREAD

**Discussion by knpwrs** [lowdefy/lowdefy#1700] [Ideas and feature requests]
The starter yaml for lowdefy looks like the following:

```yaml
lowdefy: 4.0.0-rc.12
name: Lowdefy starter

pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    areas:
      content:
        justify: center
        blocks:
          - id: content_card
            type: Card
            style:
              maxWidth: 800
            blocks:
              - id: content
                type: Result
                properties:
                  title: Welcome to your Lowdefy app
                  subTitle: We are excited to see what you are going to build
                  icon:
                    name: AiOutlineHeart
                    color: '#f00'
                areas:
                  extra:
                    blocks:
                      - id: docs_button
                        type: Button
                        properties:
                          size: large
                          title: Let's build something
                        events:
                          onClick:
                            - id: link_to_docs
                              type: Link
                              params:
                                url: https://docs.lowdefy.com
                                newWindow: true
      footer:
        blocks:
          - id: footer
            type: Paragraph
            properties:
              type: secondary
              content: |
                Made by a Lowdefy 🤖
```

It would be really nice to support type-safe languages for the config, such as [cue](https://cuelang.org/) or TypeScript (like how Vite is configured), especially as the config grows.

- https://github.com/gulpjs/liftoff is a module from back in the day that makes this kind of thing easy. I'm not personally aware of any contemporary/maintained solutions.
- Here is where vite handles their config, for reference: https://github.com/vitejs/vite/blob/2124264ceebce83d94116aa53f6db9bed5e8af4b/packages/vite/src/node/config.ts#L949-L1013
- Prettier supports json, yaml, toml, and js: https://prettier.io/docs/en/configuration.html
  - Here is where it appears prettier handles their config loading, for reference: https://github.com/prettier/prettier/blob/353cb43079b8123d4dfb4ec84524b0ed98015fc0/src/config/get-prettier-config-explorer.js
