### DISCUSSION TITLE
onChange event of Tab block does not trigger on activeKey change

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1704] [Questions and Help] [answered]
I have Tab block like this:

```
- id: a76bc014-9a8f-453e-b5a9-21b41cf27521
  type: Tabs
  properties:
    defaultActiveKey: tab1
    activeKey:
      _state: active_tab
  tabs:
    - key: tab1
      title: tab1
    - key: tab2
      title: tab2
  events:
    onChange:
      - id: 39b680d8-5f08-4df3-9dd2-09aa81e5915e
        type: CallMethod
        params:
          blockId: block_id
          method: open
```

Tab event `onChange` does not trigger when I assign new `_state: active_tab` value. However it does trigger when I change active tab with mouse click. Is this an expected behavior?

```
- id: 74a79b75-ded9-423e-89f1-aa9424483280
  type: SetState
  params:
    active_tab: tab2
```

Lowdefy 4.0.0-rc.12.
