### DISCUSSION TITLE
_email operator suggestion

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1713] [Ideas and feature requests]
Operator to validate email address. Not critical, but nice to have.

```
validate:
  - status: error
    message: Incorrect email format.
    pass:
      _regex: ^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$ 
```
