### DISCUSSION TITLE
How to use 'formatter' property of NumberInput input

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1722] [Questions and Help]
Can't figure out how to set suffix 'GB' to NumberInput value. I would appreciate for help.

```
- id: abe7357d-d7df-42d7-a0aa-51d5de24f48a
  type: NumberInput
  required: true
  properties:                                                                
    label:
      title: 'title'
    min: 100                                 
    max: 10000
    precision: 0
  formatter:
    _function:
      __intl.numberFormat:
        on:
          __args: 0
        options:
          style: 'unit'
          unit: gigabyte
```

also tried:

  `formatter: '{value} GB'`

  `formatter: '${value} GB'`
