### DISCUSSION TITLE
List of Links: `href`s are not working

### DISCUSSION THREAD

**Discussion by gramian** [lowdefy/lowdefy#1727] [Questions and Help]
Dear Community,

I am trying to render a list of links, which are either coming from the Lists `_state` or a `_request`. Neither seems to work: the `href`s of the rendered `a` tags always contain `null`. I have tried a `List` of `Anchor`s, a `List` of `Html`s, and a `List` of `DangerousHtml`s:

```yaml
blocks:
  - id: "my_list"
    type: "List"
    blocks:
      - id: "links.$"
        type: "Anchor"
        properties:
          title:
            _state: "my_list.$.name"
          href:
            _state: "my_list.$.uri"  # also tried: _request: "my_request.data.links.$.uri"
```

```yaml
blocks:
  - id: "my_list"
    type: "List"
    blocks:
      - id: "links.$"
        type: "DangerousHtml"
        properties:
          html:
            _string.concat:
             - "<a href'"
             - _state: "my_list.$.uri"  # also tried: _request: "my_request.data.links.$.uri"
             - "'>"
             - _state: "my_list.$.name"
             - "</a>"
```

With `DangerousHtml` I also tried the following `DOMPurifyOptions` (with no effect):
```
ADD_URI_SAFE_ATTR: ['href']
ALLOWED_TAGS: ['a']
ALLOWED_ATTR: ['href']
ADD_TAGS: ['a']
ADD_ATTR: ['href']
```

Note that in each test case the link title is rendered correctly.

Thank you for your help
