### DISCUSSION TITLE
button background color

### DISCUSSION THREAD

**Discussion by Yenzago** [lowdefy/lowdefy#1778] [Questions and Help]
#### Describe the bug

I want to put a color white in the background of my button but it's not working
=
#### To Reproduce

Example configuration reproducing the issue, or steps to reproduce the behavior.
this is my code : 
- id: button_assets
            type: Button
            properties:
              title: "Assets"
              variant: "contained"
              type: "primary"
              size: "large"
            style:
              marginLeft: "10px"
              background: "#f5f5f5"
            layout: 
              flex: 0 1 auto

![image](https://github.com/lowdefy/lowdefy/assets/104826833/ae360257-16e5-47fd-9aa4-a504ded9283b)

#### Lowdefy Version

lowdefy@4.0.0-alpha.37

**Comment by Yenzago** [comment]
can we also change the color of the title please ?

**Comment by Gervwyk** [comment]
You can do this by setting the `properties.color`, and applying the style to the button with `properties.style`, top-level style is the block layout style, so an element higher than the block component. 
```yaml
id: block_id
type: Button
properties:
  color: "#ffffff"
  style:
    color: black
```
But I think what you are actually looking for is:
```yaml
id: block_id
type: Button
properties:
  type: default
```
or: 
```yaml
id: block_id
type: Button
properties:
  ghost: true
```
You can play with these properties in the docs to see how they work.
https://docs.lowdefy.com/Button

**Reply by Yenzago** [reply]
Okay thank you

**Comment by Yenzago** [comment]
Can we change the color of the title of the button ?

**Reply by Gervwyk** [reply]
```yaml
id: block_id
type: Button
properties:
  style:
    color: '#ff0000'
```

**Reply by Yenzago** [reply]
thank you 
```
         - id: selector_app
            type: Selector
            properties:
              label: 
                disabled: true
                color: "#FFF1ED"
              placeholder: "App"
              bordered: false
              title: App
              type: "primary"
              size: "large"
              style:
                color: "#08379B"
              marginLeft: "10px"
            layout: 
              flex: 0 1 auto
   ```
              
  i also tried for a selector but nothing happen
