### DISCUSSION TITLE
Block for actions

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1780] [Ideas and feature requests]
It would be great to have block/container for actions which accept condition like "skip". 

```
events:
  onEvent1:
    - id: id1
       type: ActionBlock
       actions:
	 - id: action1
	   type: ActionType1
	   params:
	     # ...
	 - id: action2
	   type: ActionType2
        skip:
	  # Operator ex
```
