### DISCUSSION TITLE
Filter nested list of dictionaries

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1781] [Questions and Help] [answered]
I can't figure out how to select list items which "options" array contains dictionary with name="Option1" and value="100".
Thank you in advance

```
[
    {
        "id": 1,
        "name": "Item1",
        "options": [
            {
                "id": 104,
                "name": "Option1",
                "value": "100"
            },
            {
                "id": 105,
                "name": "Option2",
                "value": "200"
            }
        ]
    },
    {
        "id": 2,
        "name": "Item2",
        "options": [
            {
                "id": 104,
                "name": "Option1",
                "value": "300"
            },
            {
                "id": 105,
                "name": "Option2",
                "value": "400"
            }
        ]
    }
]
```

expected result is:

<pre>
[
    {
        "id": 1,
        "name": "Item1",
        "options": [
            {
                "id": 104,
                <b>"name": "Option1"</b>,
                <b>"value": "100"</b>
            },
            {
                "id": 105,
                "name": "Option2",
                "value": "200"
            }
        ]
    }
]
</pre>

**Comment by Gervwyk** [comment, marked as answer]
I have not tested it, but try this:
```yaml
_mql.aggregate:
  on:
    _state: my_data
  pipeline:
     - $match:
         $expr:
            $gt:
              - $size:
                  $filter:
                     input:
                       $options
                     cond:
                       $and:
                          - $eq: 
                            - $$this.name
                            -  Option1
                          - $eq:
                             - $$this.value
                             - '100'
               - 0
```
