### DISCUSSION TITLE
Introduce "when:" test

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1782] [Ideas and feature requests]
I suggest alternative test "when". Most often "skip" test require to negate expression which is inconvenient.

**Comment by Gervwyk** [comment]
Hi @kemeris2000 
There is a plan in the backlog to do conditional logic for request pipelines. See https://github.com/lowdefy/lowdefy/discussions/1674

Would a solution like this make your current setup easier?

**Reply by kemeris2000** [reply]
As it will be conditional and callable from Lowdefy app - it will.
Actually new conditional action which stops event action chain would be sufficient.
```
events:
  onClick:
	- id: 2a8dda47-8b6c-4abb-9bf2-a29a89e63f20
	  type: Link
	  params:
		pageId: page_next
	  skip:
		_ne:
		  _state: redirect	  
	- id: 2a8dda47-8b6c-4abb-9bf2-a29a89e63f21
	  type: Stop
	  skip:
		_ne:
		  _state: redirect
    - id: 2a8dda47-8b6c-4abb-9bf2-a29a89e63f22
	  type: Request
    - id: 2a8dda47-8b6c-4abb-9bf2-a29a89e63f23
	  type: SetState
```

**Reply by JohannMoller** [reply]
Hi @kemeris2000, the [Throw](https://docs.lowdefy.com/Throw) action stops the event chain based on a condition. It sounds like this is what you are looking for. In your example you could do the following then:

```yaml
events:
  onClick:
    - id: 2a8dda47-8b6c-4abb-9bf2-a29a89e63f20
      type: Link
      params:
        pageId: page_next
      skip:
        _ne:
          _state: redirect	  
    - id: 2a8dda47-8b6c-4abb-9bf2-a29a89e63f21
      type: Throw
      messages:
        error: false ## This is to throw silently, otherwise an error will appear on screen
      params:
        throw: ## The action will throw and break the event chain if throw: true
          _state: redirect
    - id: 2a8dda47-8b6c-4abb-9bf2-a29a89e63f22
      type: Request
    - id: 2a8dda47-8b6c-4abb-9bf2-a29a89e63f23
      type: SetState
```

**Comment by kemeris2000** [comment]
Thank you [JohannMoller](https://github.com/JohannMoller). I made completely wrong assumption, sorry for that. This feature request was attempt to reduce code amount in cases, when for example Action1, 2, 3, 4 should execute, while Action11, 12, 13 should skip. 


```
events:
  onMount:
    try:  
      _build.array.flat:
        on:
          - - id: Action1
              type: Request
          - - id: Action2
              type: Request
          - _ref: ref1.yaml        --> 
                                      _build.array.flat:
                                        on:
                                          - id: Action11
                                            type: Link
                                            params:
                                            pageId: page_next
                                            skip:
                                              _ne:
                                                _state: redirect    
                                          - id: Action12
                                            type: Request
                                            skip:
                                              _ne:
                                                _state: redirect                                                                                        
                                          - id: Action13
                                            type: Request
                                            skip:
                                              _ne:
                                                _state: redirect                                                                                        
          - - id: Action3
              type: Request
          - - id: Action4
              type: Request
    catch:
      _build.array.flat:
        on:                    
          - _ref: get_error_last.yaml
          - _ref: notify.yaml
```
