### DISCUSSION TITLE
How to use spinner container?

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1784] [Questions and Help] [answered]
Display block `skeleton` works for page initialization events, but doesn't work for `Content` events like `onMount`.
Tried `spinner` container, but from documentation it's not very clear how to use it.

The following doesn't work for me. In all cases spinner always spin:

```
            blocks:
              - id: d20dce1d-2e6c-47c7-890e-2336f89b5917
                type: Button
                properties:
                  title: Show spinner
                events:
                  onClick:
                    - id: dad4e11a-e691-4672-b9a1-f2e518102e2f
                      type: SetState
                      params:
                        spinning: true                    
                    - id: wait
                      type: Wait
                      params:
                        ms: 2000
                    - id: 9d4f6c4a-d0c4-433c-94d4-082a7cb29006
                      type: SetState
                      params:
                        spinning: false
              - id: spinner1
                type: Spinner
                blocks:
                  - id: 876c1b75-a63d-4b19-b035-502b10d48159
                    type: Span
                    properties:
                      content: Spinner content  
```

```
            blocks:
              - id: d20dce1d-2e6c-47c7-890e-2336f89b5917
                type: Button
                properties:
                  title: Show spinner
                events:
                  onClick:
                    - id: dad4e11a-e691-4672-b9a1-f2e518102e2f
                      type: SetState
                      params:
                        spinner_state: true                    
                    - id: wait
                      type: Wait
                      params:
                        ms: 2000
                    - id: 9d4f6c4a-d0c4-433c-94d4-082a7cb29006
                      type: SetState
                      params:
                        spinner_state: false
              - id: spinner1
                type: Spinner
                spinning: spinner_state
                blocks:
                  - id: 876c1b75-a63d-4b19-b035-502b10d48159
                    type: Span
                    properties:
                      content: Spinner content  
```

**Comment by Gervwyk** [comment, marked as answer]
Hi @kemeris2000 
It's actually a little simpler than this.
On the blocks page in the docs see "Blocks loading" https://docs.lowdefy.com/blocks
```yml
      - id: a_block
        type: Span
        loading:
          _eq:
            - _state: spinner_state
            - true
        skeleton:
          type: Spinner
        properties:
          content: Conent when not loading
```
However, if you want to use the spinner with state management like in your example, maybe the `visible` key is what you are looking for?
```yaml
             - id: d20dce1d-2e6c-47c7-890e-2336f89b5917
                type: Button
                properties:
                  title: Show spinner
                events:
                  onClick:
                    - id: dad4e11a-e691-4672-b9a1-f2e518102e2f
                      type: SetState
                      params:
                        spinner_state: true                    
                    - id: wait
                      type: Wait
                      params:
                        ms: 2000
                    - id: 9d4f6c4a-d0c4-433c-94d4-082a7cb29006
                      type: SetState
                      params:
                        spinner_state: false
              - id: spinner1
                type: Spinner
                visible: 
                  _state: spinner_state
                blocks:
                  - id: 876c1b75-a63d-4b19-b035-502b10d48159
                    type: Span
                    properties:
                      content: Spinner content  
```
