### DISCUSSION TITLE
Epoch to date question

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1786] [Questions and Help] [answered]
Code below produce wrong result as `_math.imul` return `-944668072` instead of expected `1639732839000`.
How to convert Epoch to human readable date string?

```
_date:
  _math.imul:
    - 1639732839
    - 1000
```

anything better than this?
```
_date:
  _number.parseInt:
    - _string.concat:
      - _number.toString:
        - 1639732839
      - '000'
```

**Comment by Gervwyk** [comment, marked as answer]
Hi @kemeris2000 
You could also do:
```yaml
_date:
  _product:
    - 1639732839
    - 1000
```
