### DISCUSSION TITLE
PHP's serialize plugin

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1787] [Snippets]
```
_phpserialize:
  data:
    a: aaaaa
    b: bbbbb
    c: ccccc
```
produce:
```
a:3:{s:1:"a";s:5:"aaaaa";s:1:"b";s:5:"bbbbb";s:1:"c";s:5:"ccccc";}
```

```
_phpunserialize:
  data: a:3:{s:1:"a";s:5:"aaaaa";s:1:"b";s:5:"bbbbb";s:1:"c";s:5:"ccccc";}
```
produce:
```
a: aaaaa
b: bbbbb
c: ccccc
```

[lowdefy-plugin-phpserialize.zip](https://github.com/lowdefy/lowdefy/files/14378984/lowdefy-plugin-phpserialize.zip)
