### DISCUSSION TITLE
List's content area does not apply gutter

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1813] [General]
```
list:
  - aaaa
  - bbbb
  - cccc
```

```yaml  
blocks:
- id: list
  type: List
  properties:
    direction: row
  areas:
    content:
      gutter: [32, 32]
      blocks:
        - id: list.$
          type: Card
          blocks:
            - id: span
              type: Span
              properties:
                content:
                  _state: list.$
```

![image](https://github.com/lowdefy/lowdefy/assets/48207709/8dae2fa0-b97a-447c-b106-ef6c5b6f4a90)

**Comment by Gervwyk** [comment]
Hi @kemeris2000, This is actually by design as the content area wraps not the list items but forms the container areas of each item, whcih then contains a list of blocks. Thus the gutter will be appied to the child area of each list item's blocks. 

Debatable if this is how it should be, but when we wrote the code it was the more direct implementation.

To apply the gutter here, you could do the following to add some padding:
```yaml
blocks:
      - id: list
        type: List
        properties:
          direction: row
        areas:
          content:
            style:
              paddingRight: 32px
            blocks:
              - id: list.$
                type: Card
                blocks:
                  - id: span
                    type: Span
                    properties:
                      content:
                        _state: list.$
```
