### DISCUSSION TITLE
Sharing jq plugin

### DISCUSSION THREAD

**Discussion by kemeris2000** [lowdefy/lowdefy#1820] [Ideas and feature requests]
Sharing _jq plugin which is based on [jqjs](https://github.com/mwh/jqjs) which is js implementation of powerful [jq](https://jqlang.github.io/jq/) JSON processor written in portable C.
This code is completely free to use and modify.

Usage:

```yaml
names:
  - Key1:
      - name: John
        age: 18
      - name: Olivia
        age: 43
  - Key2:
      - name: Henry
        age: 39
      - name: James
        age: 43
```

```yaml
_json.stringify:
  - _jq:
      object:
        _state: names
      query: '.[] | select(.Key1)'
```
```yaml
Key1:
  - name: John
    age: 18
  - name: Olivia
    age: 43
```

```yaml
_json.stringify:
  - _jq:
      object:
        _state: names
      query: '(.[] | .[] | .[] | select(.age == 43) | .age) |= 15'
```
```yaml
- Key1:
  - name: John
    age: 18
  - name: Olivia
    age: 15
- Key2:
  - name: Henry
    age: 39
  - name: James
    age: 15
```

```yaml
_json.stringify:
  - _jq:
      object:
        _state: names
      query: '[.[] | .[] | .[].name]'
```
```yaml
- John
- Olivia
- Henry
- James
```
[lowdefy-plugin-jq.zip](https://github.com/user-attachments/files/15525027/lowdefy-plugin-jq.zip)
