### DISCUSSION TITLE
OpenID Connect implementation in v3.11.x.

### DISCUSSION THREAD

**Discussion by SamTolmay** [lowdefy/lowdefy#483] [Announcement]
Lowdefy v3.11.x includes initial support for OpenID Connect. There might be breaking changes to the configuration required as this is tested in the wild. The features included won't be documented until the implementation is stable. The purpose of this discussion is to document the new features and to discuss problems and ideas regarding the implementation.

# Documentation

To use a OpenID Connect provider in your application, the following secrets need to be set (set a env variable `LOWDEFY_SECRET_ JWT_SECRET` for example.):
```
JWT_SECRET = The secret string that will be used to sign user json web tokens. This shoukd be a 256-bit random string to avoid brute force attacks
OPENID_CLIENT_ID = The OpenID Connect client id.
OPENID_CLIENT_SECRET = The OpenID Connect client secret.
OPENID_DOMAIN = The domain that will be used for client discovery
```

The following optional config can also be set in the lowdefy configuration:
```yaml
config:
  auth:
    openId:
      # Whether the user should be logged out from the provider if the logout action is used.
      # This is not supported by all providers. See below for Auth0 specifically.
      logoutFromProvider: [boolean] 
      # The url the user should be redirected to after logout.
      # If logoutFromProvider is true, this should be configured with the provider
      logoutRedirectUri: [string]
      # The OpenID Connect scope to request. The default is 'openid profile email'
      scope: [string]
    jwt:
      # The length of time a user token should be valid.
      # Can be expressed as a number in seconds, or a vercel/ms string (https://github.com/vercel/ms)
      expiresIn: [string | number]
    pages:
      # See below
      protected: [boolean | string[]]
      public: [boolean | string[]]           
```
### Protecting pages

By default, all pages in an app are public. To protect all pages in the app (make them unavailable unless logged in), set `config.auth.pages.protected` to true. Certain pages can be excluded by setting `config.auth.pages.public` to an array of pageIds that should be public. Alternatively, `config.auth.pages.public` can be set to true, and `config.auth.pages.protected` can be an array of pageIds that should be protected.

You will probably need to set a public page to allow users to login.

You cannot set `protected` or `public` to false, and both can't be an array or boolean.

### Login and Logout

To log users in to your app, use the `Login` action. This will initiate a OpenID Connect authorization code flow. The `Login` action can take a `pageId`, `input`, and `urlQuery` as paramters. The user will be linked to that page using those parameters after login. Users will be redirected to the home page if this is not set.

To log users out, use the `Logout` action. The logout behavior is specified in the `config.auth.openId` object.

### The user object and `_user` operator.

A user object, with all the claims provided by the OpenID Provider, except the `aud`, `exp`, `iat`, and `iss` can be accessed using the `_user` getter operator. Use `_user: true` to get the entire object, or `_user:key` (`_user: email` for example) to get a specifiec field.

**Comment by SamTolmay** [comment]
###  Auth0.

You need to configure the Callback URLs for your client in Auth0. This should be:
```
http://localhost:3000/auth/openid-callback
https://www.example.com/auth/openid-callback
```

`logoutFromProvider ` is not supported by Auth0. Set logoutRedirectUri to `https://YOUR_DOMAIN/v2/logout?returnTo=https%3A%2F%2Fwww.example.com&client_id=CLIENT_ID`. See https://auth0.com/docs/logout/redirect-users-after-logout for more details.

**Reply by AhmedBytesBits** [reply]
`config.auth.pages.protected` and `config.auth.pages.public` working as expected but I am struggling figuring out how to setup a working Log In page.

I am using Keycloak installed locally on machine, so here is the config:
```
JWT_SECRET=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgRMd21mXRoZ9Jp8qET85YuLCzcSV5zDwgVP03+y0DoKY0i3gd9f/02rwXetDMG1h3tZerDzUMnaGxqfD05g4c/w528Vm25HfxhCDABF4AbVyZ7FoAdJc3yIqmYDr6UyrTKG2fgavYjF6OAshka75klR+NXu6QpRgtnpsPPxZUGJgoD2OqYn2A8BsOjlpKFOYjPp4rwTZkNU1SzrATDgm59btfCXaDz1zKDFdYaYSFT6U0kCF0cdmsluA3x5T7fIbXxv2QAR925ibnZyZEqSAo0hyKd6v73vQyH4o3FedbdBxZHA+86hURq4Bmsm0a8fdow0uR/IElSgk1/PCxHgwIDAQAB
OPENID_CLIENT_ID=web-app
OPENID_CLIENT_SECRET=d9397752-e694-4541-809c-35c55073f72d
OPENID_DOMAIN=http://localhost:8080/auth/realms/eval-lowdefy/protocol/openid-connect/auth
```

For testing purposes I am using an event in Log In page as following:
```
id: login
type: PageHCF
layout:
  contentJustify: center
properties:
  title: Remoto- Log In

areas:
  content:
    blocks:
      - id: welcome
        type: Title
        properties:
          content: Welcome to Remoto
events:
  onEnter:
    - id: auth-login
      type: Login
        
```

Here is the GQL response in browser:
```
{"data":{"openIdAuthorizationUrl":null}}
```
