### DISCUSSION TITLE
Is it possible to run arbitrary javascript?

### DISCUSSION THREAD

**Discussion by Fluffy9** [lowdefy/lowdefy#501] [Questions and Help] [answered]
I have code already, just need a UI

**Comment by Gervwyk** [comment]
Hi @fluffy9!

Firstly where would you like to run this code? Client side or server side? Then what type of code are we talking? Some functions, or a packaged bundle?

Any example code, repo or snippet you can share?

**Reply by Fluffy9** [reply]
All client side code. Just some functions. I don't have the code working yet to share, but basically just loading some client side libraries from a cdn and incorporating that into functions. I was hoping to be able to call `MyFunction()` from a button click or something. 

Thanks for getting back to me so fast though, I'm loving lowdefy so far 😊

**Reply by Gervwyk** [reply]
So currently your best way to do that would be to create a custom block, see the template for details and please shout if you get stuck and I can help! This can get a little complicated, you basically make your own button and wrap it in a react component. 

But this is complicated, we are working on a way to run js code on the client using a operator, this will be very easy, however, it has some serious security implications so we will be running this in a contained environment, which also means no external imports or pulling in packages. Would this be sufficient?

There is already a experimental operator in the current version, which just uses eval, bur this will definitely change soon.

**Reply by Fluffy9** [reply]
Is the experimental operator mentioned in the docs? I'm not familiar with react and I'm not that concerned about the security implications for my use case so eval would be fine

**Reply by Gervwyk** [reply]
No its not, as it will definitely change in the next few versions.

So you should be able to do:
```
_experimental_unsafe_js.evaluate:
  file:
    _ref: myjsfile.js
  args:
   - 1
   - 2
```
We use the [filterDefaultValue](https://github.com/lowdefy/lowdefy/blob/main/packages/docs/templates/blocks/filterDefaultValue.js) function in the docs to filter one object from another on the blocks pages in the docs.


You can look at the implementation here: https://github.com/lowdefy/lowdefy/blob/main/packages/operators/src/common/experimental_unsafe_js.js

**Reply by Fluffy9** [reply]
Quick question. I've gotten the code to run, but it runs on the page load not when my button has been clicked
```
        blocks: 
        - id: Button
          type: Button
          properties: 
            title: Button
            events: 
              onClick: 
                _experimental_unsafe_js.evaluate:
                  file:
                    _ref: myjsfile.js
                  args:
                  - 1
                  - 2
```
Here's the myjsfile.js
```
function Test(...args){
    alert("It works!")
}
export default Test()

```

Edit: 

I know I'm gonna need to return data too. Hopefully there is nothing special I need to do for that?

**Reply by Gervwyk** [reply]
I'm just going to take it a few steps further, I hope its not confusing but consider this little more complex example:

##### myfile.js:
```js
function Test(...args) {
  if (args[0]) {
    return 'The Foo input has a length of: ' + args[0].length;
  }
  return 'Foo is not defined';
}
export default Test();
```

##### and my lowdefy.yaml
```yaml
name: test
lowdefy: 3.10.2
licence: MIT
pages:
  - id: new
    type: Context
    blocks:
      - id: foo_input
        type: TextInput
        properties:
          title: Enter Foo
      - id: foo_result
        type: Markdown
        properties:
          content:
            _nunjucks:
              template: |
                ### Your input for Foo is: {{ val }}

                ### {{ calculated_val }}

                ### Also with operators, Foo length is: {{ foo_length }}
              on:
                _log:
                  val:
                    _state: foo_input
                  foo_length:
                    _string.length:
                      _state: foo_input
                  calculated_val:
                    _experimental_unsafe_js.evaluate:
                      file:
                        _ref: myfile.js
                      args:
                        - _state: foo_input
```

I'm doing a few things here, but I'm trying to show how operators can be used in most cases. and how the js works as an operator.

In this example, as you enter a value into `foo_input`, Lowdefy reevaluates the config continuously and renders the result.

Getting back to you button example, it is important to understand that [`events` trigger `actions`](https://docs.lowdefy.com/events-and-actions). So the `Button` `onClick` event fires a list of `actions` in  sequential order.

Let's give that a try, I'll change my lowdefy.yaml to:
```yaml
name: test
lowdefy: 3.10.2
licence: MIT
pages:
  - id: new
    type: Context
    blocks:
      - id: foo_input
        type: TextInput
        properties:
          title: Enter Foo
      - id: calculate_foo
        type: Button
        properties:
          title: Calculate It 🙈
        events:
          onClick:
            - id: do_it
              type: SetState
              params:
                val:
                  _state: foo_input
                foo_length:
                  _string.length:
                    _state: foo_input
                calculated_val:
                  _experimental_unsafe_js.evaluate:
                    file:
                      _ref: myfile.js
                    args:
                      - _state: foo_input
      - id: foo_result
        type: Markdown
        properties:
          content:
            _nunjucks:
              template: |
                ### Your input for Foo is: {{ val }}

                ### {{ calculated_val }}

                ### Also with operators, Foo length is: {{ foo_length }}
              on:
                _log:
                  _state: true
```

And tada  🪄  when my `calculate_foo` Button is clicked, the [`SetState`](https://docs.lowdefy.com/SetState) action is triggered and my `foo_result` content is updated. Here I'll just give `foo_result` the entire `state` to use. 

> Notice that I included the [`_log`](https://docs.lowdefy.com/_log) operator. This will `console.log` every time the operator is evaluated.
