### DISCUSSION TITLE
Iterate over an object instead of an array with a list

### DISCUSSION THREAD

**Discussion by G33KatWork** [lowdefy/lowdefy#508] [Questions and Help] [answered]
Hi,

in all the examples a `List` is always used to iterate over an array, but in my case I have an object that contains keys and more objects as the value. I would like to generate a Box with the key of the object as the title and below that a few values from the object. Is there a way to use a `List` to iterate over an object?

Example:
```
{
    "block1": {"field1": "foo", "field2": "bar"},
    "block2": {"field1": "baz", "field2": "foop"}
}
```

I tried using the usual $ syntax as the placeholder for the key just like with an array, but I can't seem make it work and I also don't know how I would access the key then in another block inside the list.

Any help would be cool!

Thanks,
\- Andy

**Comment by SamTolmay** [comment, marked as answer]
Hi @G33KatWork 

You can use the `_mql.expr` operator, with the MongoDB `$objectToArray` operator. This will convert the object into key value pairs.

For example:
```yaml
onInit:
  - id: init
    type: SetState
    params:
      array:
        _mql.expr:
          on:
            object:
              block1: #...
              block2: #...
           expr:
             $objectToArray:
               $object
```

State will look like:
```yaml
array:
  - k: block1
    v:
     field1:
     #...
```

You can use `array.$.k` to reference the key in state, and `array.$.v.field1` to reference a field.

Hope that helps. Please let me know if you have any issues, I wasn’t able to test if this works.
