### DISCUSSION TITLE
Validation is always false

### DISCUSSION THREAD

**Discussion by AhmedBytesBits** [lowdefy/lowdefy#553] [Questions and Help] [answered]
Hi,
First thanks for the great job you are doing here. I just making some tests on the framework before including it in my next project.
In the following code, validate always show errors as fields are reuqired although there are content in each.
```
  id: add_professional_drawer
  type: Drawer
  properties:
    title: Add a new professional
    width: 400
  layout:
    contentGutter: 16
  blocks:
    - id: first-name
      type: TextInput
      required: true
      layout:
        span: 12
      properties:
        title: First name
    - id: last-name
      type: TextInput
      required: true
      layout:
        span: 12
      properties:
        title: Last name
    - id: email
      type: TextInput
      properties:
        title: email
      validate:
        - message: "Please enter a valid email address"
          status: error
          pass:
            _not:
              _not:
                _state: email
        - message: Please provide a valid email address.
          status: error
          pass:
          _regex: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
    - id: status
      type: Selector
      properties:
        title: Status
        options:
          - Available
          - Not Available
          - Terminated
    - id: reset_button
      type: Button
      layout:
        span: 12 # Set the size of the button (span 12 of 24 columns)
      properties:
        title: Reset
        block: true # Make the button fill all the space available to it
        type: default # Make the button a plain button
        icon: ClearOutlined
      events:
        onClick:
          - id: reset
            type: Reset
    - id: submit_button
      type: Button
      layout:
        span: 12
      properties:
        title: Submit
        block: true
        type: primary # Make the button a primary button with color
        icon: SaveOutlined
      events:
        onClick:
          - id: validate
            type: Validate
```

**Comment by Gervwyk** [comment, marked as answer]
Hi @ahmedrshdy, thanks for bringing this to our attention. Seems like there is an issue introduced in v3.13.0, #554 
We will publish a patch asap, in the meantime, your validation should work in v3.12.6. Just change `lowdefy: 3.14.0` to `lowdefy: 3.12.6` for now. 

Also, just check your yaml above, there is an indentation error:
```yaml
       - message: Please provide a valid email address.
         status: error
         pass:
          _regex: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
```
should be:
```yaml
       - message: Please provide a valid email address.
         status: error
         pass:
            _regex: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
```

**Reply by Gervwyk** [reply]
Hi @ahmedrshdy 

The issue has been resolved. Fix published in [v3.14.1](https://github.com/lowdefy/lowdefy/releases/tag/v3.14.1)
Update the `lowdefy` field in your `lowdefy.yaml` to `lowdefy: 3.14.1` and the above code should work as expected.
Shout if you need any help!

**Reply by AhmedBytesBits** [reply]
Wow, that was really quick!
I tested it again and it works as expected, thanks a lot

**Reply by AhmedBytesBits** [reply]
One more help if you can, how can I insert into a postgres db, it is not mentioned in documentation of Knex!

**Reply by SamTolmay** [reply]
Hi @ahmedrshdy 

To do an insert using the `KnexBuilder` request:
```yaml
id: insert
type: KnexBuilder
connectionId: postgres
properties:
  tableName: professionals
  query:
    - insert:
        - first-name:
            _state: first-name
          last-name:
            _state: last-name
          status:
            _state: status
          email:
            _state: email
```
The knex insert method takes an object, or array of objects with column names as keys and values as the values to insert. You can also insert the  value in state if the names correspond to the column names in your table:
```yaml
id: insert
type: KnexBuilder
connectionId: postgres
properties:
  tableName: professionals
  query:
    - insert:
        - _state: true
```
