### DISCUSSION TITLE
Can not make Postgres connection work

### DISCUSSION THREAD

**Discussion by AhmedBytesBits** [lowdefy/lowdefy#558] [Questions and Help] [answered]
Hi Lowdefy team,
I am struggling to populate postgres lookup table to a selector following the dynamodb example
here is my page:
```
id: add_professional_drawer
type: Drawer
properties:
  title: Add a new professional
  width: 400
layout:
  contentGutter: 16
requests:
  - id: statuses_selector
    type: KnexBuilder
    connectionId: postgres
    properties:
      query:
        - select:
            - value
            - label
            - disabled
        - from:
          - professionals_statuses

events:
  onEnter:
    - id: fetch_statuses
      type: Request
      params: statuses_selector
blocks:
  - id: first-name
    type: TextInput
    required: true
    layout:
      span: 12
    properties:
      title: First name
  - id: last-name
    type: TextInput
    required: true
    layout:
      span: 12
    properties:
      title: Last name
  - id: status
    type: Selector
    properties:
      title: Status
      placeholder: Assign Status
      options:
        _request: statuses_selector
  - id: reset_button
    type: Button
    layout:
      span: 12 # Set the size of the button (span 12 of 24 columns)
    properties:
      title: Reset
      block: true # Make the button fill all the space available to it
      type: default # Make the button a plain button
      icon: ClearOutlined
    events:
      onClick:
        - id: reset
          type: Reset
  - id: submit_button
    type: Button
    layout:
      span: 12
    properties:
      title: Submit
      block: true
      type: primary # Make the button a primary button with color
      icon: SaveOutlined
    events:
      onClick:
        - id: validate
          type: Validate
```

And here is my table `professionals_statuses` structure:
- label
- value
- disabled

Finally hereunder my connection:
```
id: postgres
type: Knex
properties:
  client: postgres
  connection:
    _secret: PG_CONNECTION_STRING
  searchPath:
    - knex
    - public
   
```
