### DISCUSSION TITLE
Typo in AxiosHttp example

### DISCUSSION THREAD

**Discussion by mat02** [lowdefy/lowdefy#606] [Docs]
Hi!
Yesterday I spent some time with AxiosHttp requests and I noticed (only after 1h of debugging ;) ), that there is a typo in first example: 
```
connections:
  - id: app_api
    type: AxiosHttp
    properties:
 <------ TYPO HERE ----->
      baseUrl: app.com/api
 <------ TYPO HERE ----->
      auth:
        username: api_user
        password:
          _secret: API_PASSWORD
```

In the example there is a field base**Url,** but it should be base**URL**. This causes the Axios to skip the base url part and fail with rather cryptic message "connect ECONNREFUSED 127.0.0.1:80".
