### DISCUSSION TITLE
Is there any way to do string formatting using state variables?

### DISCUSSION THREAD

**Discussion by APTy** [lowdefy/lowdefy#656] [Questions and Help] [answered]
Right now, I am able to display some part of my state as it's own block, but can I interpolate some state variables into the content?

**Today**
```
              - id: brands.$.name
                type: Paragraph
                properties:
                  content:
                    _state: channels.$.id
```

**Proposed**
```
              - id: brands.$.name
                type: Paragraph
                properties:
                  content: Check out the cool {{_state.brands.$.name}} brand!
```

What is the best way to achieve this today? Composing some html spans together?

**Comment by Gervwyk** [comment, marked as answer]
Hi @APTy 

Yes! Check out the [_nunjucks](https://docs.lowdefy.com/_nunjucks) operator. Nunjucks is very powerful and fast string parsing library. 
But for your example above you could also use the [_string](https://docs.lowdefy.com/_string) operator. Something like this:
```yaml
- id: brands.$.name
  type: Paragraph
  properties:
       content: 
         _string.concat:
             - 'Check out the cool '
             - _state: brands.$.name
             - ' brand!'
```

**Reply by APTy** [reply]
Ahh exactly what I was looking for, thank you @Gervwyk ! I searched for `template`, `interpolation`, `format`, etc. and surprised the nunjucks page didn't come up, especially since the word "template" appears on the nunjucks page 17 times! Search is a hard problem 😄 Hopefully this discussion thread helps with discoverability.

e.g.:
<img width="639" alt="Screen Shot 2021-06-23 at 1 04 50 PM" src="https://user-images.githubusercontent.com/9010671/123139078-ce98db00-d423-11eb-9501-8307e731d453.png">

**Reply by Gervwyk** [reply]
Ahh. sorry about that, the algolia search on the docs is new and we are still refining the search index settings with them. It seems like their index crawler times out, and then only indexes a part of the docs. We'll create a PR for them to improve the index.

**Reply by APTy** [reply]
Nice thank you. And just for completeness, is this the correct nunjucks syntax?
```yaml
- id: brands.$.name
  type: Paragraph
  properties:
       content: 
         _nunjucks: "Brand: {{ brands.$.name }}"
```

edit: i couldn't get the above to work, but this one seemed to work:
```yaml
- id: brands.$.name
  type: Paragraph
  properties:
       content: 
         _nunjucks:
           template: "Brand: {{ brandName }}"
           on:
             brandName:
               _state: brands.$.name
```
