### DISCUSSION TITLE
Connection/request error handling

### DISCUSSION THREAD

**Discussion by APTy** [lowdefy/lowdefy#662] [Questions and Help] [answered]
Is there any way to configure the message that pops up when a connection/request fails? Currently it says: "Action unsuccessful", but it'd be nice to be able to pull out some data from the response and display that to the user instead.

<img width="185" alt="Screen Shot 2021-06-24 at 3 12 00 PM" src="https://user-images.githubusercontent.com/9010671/123319787-e3966c80-d4fe-11eb-99ba-b1f5dab1ed30.png">

**Comment by SamTolmay** [comment, marked as answer]
Yes, you can. You can see the full description at https://docs.lowdefy.com/events-and-actions.

There is a `messages` object on actions, and you can set the loading, success, and error messages here.
The success and loading messages are not shown by default, but the error message is.

So you could do:
```yaml
id: my_action
type: Request
messages:
  success: Did the thing!
  error: Oops...
  loading: Trying to do the thing...
params:
  # ...
```
or:
```yaml
id: my_action
type: Request
messages:
  success: true
  error: false
  loading: true
params:
  # ...
```

You can also use operators in the messages, but the operators are evaluated before the action is executed, so you won't be able to use the `_actions` operator to read the error message. (This is probably something we should change).

For now you will need to use the a try, catch, and then use a `Message`  action to show the message in the catch.
