### DISCUSSION TITLE
Automatically reload the block when the associated data changes

### DISCUSSION THREAD

**Discussion by xiexj2** [lowdefy/lowdefy#682] [Questions and Help] [answered]
Hi，

Blocks can define events which the block can trigger when something happens on the page. However，suppose there is a display block on the page used to display the data of a table in the database. When a record is inserted into the database table, if we want the display block to be automatically updated, how does Lowdefy App implement it.

Good Luck

Xie Xiaojun

**Comment by SamTolmay** [comment, marked as answer]
Hi Xie Xiaojun

Lowdefy uses operators to update the user interface as need. Operators are functions that are evaluated whenever something on the page changes. If a block's properties have changed since the last time the operators were evaluated, the block will update.

Exactly how you use the operators will depend on your exact use case. So for example, if the content of a `Title` block should be equal to a value in state, you could do:
```yaml
id: title
type: Title
properties:
  content:
    _state: my_title
```
If the data in `state` changes, either because of an input block with id `my_title`, or because you called the `SetState` action, the title will change.

If you are using an [AgGrid](https://github.com/lowdefy/blocks-aggrid) table, for example, which has a `rowData` property, you might make the `rowData` property equal to the response from a request. So for example: 
```yaml
id: my_table
type: AgGridAlpine
properties:
 rowData:
    _request: fetch_data
```
In this case you would need to refresh the request after the data in the database has changed. So if you do an insert on the click of a button, you might do:
```yaml
id: insert_button
type: Button
events:
  onClick:
    - id: insert_data
      type: Request
      params: insert_data
    - id: fetch_data
      type: Request
      params: fetch_data
```
Then, after the data has been inserted, the `fetch_data` request will be updated, and the UI will update once the request has returned.

I hope this helps and makes things clear. If it doesn't, or you aren't sure how to apply it to your specific use case, you are welcome to share an example with me to help with.
