### DISCUSSION TITLE
Error in making a form with the Google Sheet API

### DISCUSSION THREAD

**Discussion by astrogewgaw** [lowdefy/lowdefy#692] [Questions and Help] [answered]
So I tried connecting a form to a Google Sheet (following the steps in the lowdefy tutorial) and I am running into this weird error: `Request Error: cleanRows received invalid input type undefined.`. How do I resolve it? I have no idea where the problem is, so I don't know where to look for solutions 😅. My code is all here: **https://github.com/astrogewgaw/whoswho**.

**Comment by Gervwyk** [comment]
Hi @astrogewgaw 
I ran your code and it worked fine on my side. I did not have to change anything.
https://docs.google.com/spreadsheets/d/1wldNzkdP7-qSBz8pdtYrx8dlTw01vqQ9gn6KfXPg5DU/edit#gid=801663685

The only thing I needed to do is add the header row to the google sheet. 
Perhaps just double check your `sheetId` and `spreadsheetId`? For the above link mine is:
```yaml
connections:
  - id: google_sheet
    type: GoogleSheet
    properties:
      client_email:
        _secret: SHEETS_CLIENT_EMAIL
      private_key:
        _base64.decode:
          _secret: SHEETS_PRIVATE_KEY
      spreadsheetId: '1wldNzkdP7-qSBz8pdtYrx8dlTw01vqQ9gn6KfXPg5DU'
      sheetId: '801663685'
      write: true
```

Please let me know how it goes?
