### DISCUSSION TITLE
Displaying a Google Sheet as an AgGrid

### DISCUSSION THREAD

**Discussion by astrogewgaw** [lowdefy/lowdefy#694] [Questions and Help] [answered]
I have a Google Sheet that I want to display as a table using the AgGrid block. The syntax of the AgGrid block is like:

```yaml
- id: whoswho_data
  type: AgGridAlpine
  properties:
    rowData:
```

and I am getting the Google Sheet data with:

```yaml
requests:
  - id: get_data
    type: GoogleSheetGetMany
    connectionId: data_sheet
    properties:
      options:
        skip:
          _product:
            - _state: page_size
            - _subtract:
                - _state: page_number
                - 1
        limit:
          _state: page_size
```

What should I put in `rowData` to get my data into the AgGrid from the Google Sheet? All the examples in the repository README are based on hard-coded data so they just do:

```yaml
rowData:
  - title: One
    year: 2010
    viewerReviews: 30
  - title: Two
    year: 2011
    viewerReviews: 20
```

where `title`, `year` and `viewerReviews` are the columns. In my case, the headers in the Google Sheet are:
* `Name`
* `Institution`
* `Position`
* `Email`
* `Website`
* `Twitter`

**Side note**: Is there a way to display particular columns as links? For example, in my case, the last three columns should be displayed as links to various things (email, website and twitter profiles, respectively).

**Comment by Gervwyk** [comment, marked as answer]
Hi @astrogewgaw 
Yes, there is! So on your example, here are a few things to check:
1) The request is defined on any block on the same page.
2) You need to first fetch you request data using the [`Request`](https://docs.lowdefy.com/Request) action. We usually do this in the `onEnter` event on a page / context, or the `onClick` of a [`Button`](https://docs.lowdefy.com/Button).
3) You can access the request-response using the [`_request`](https://docs.lowdefy.com/_request) operator.
4) Finnaly, let's look at your AgGrid setup:
```yaml
- id: whoswho_data
  type: AgGridAlpine
  properties:
    rowData:
      _request: get_data
   colDefs:
       - field: Twitter
         headerName: Twitter Link
         width: 120
         cellStyle: # just an additional example for styling a cell
            _function:
              color: white
              border: 0px solid white
              borderLeft: 10px solid white
              borderColor:
                __args: '0.data.status_details.color'
         cellRenderer:
            _function: # creates a function which wraps the row data in an <a/> tag.
              __string.concat:
                - '<a href="'
                - __args: 0.data.Twitter
                - '">'
                - __args: 0.data.Twitter
                - </a>
   
```

#### TIPS

Note the use of the [`_function`](https://docs.lowdefy.com/_function) operator and how we use this to provide functions to AgGrid for cell rendering. 

Also often useful to use the [`_log`](https://docs.lowdefy.com/_log) operator to log the output of `_request` to the browser console in order to see the response shape of your request. You want to pass your data array to `rowData` so sometimes you need to use the [`_get`](https://docs.lowdefy.com/_get) operator to pass the array to `rowData`.
