### DISCUSSION TITLE
How do I write an 'insert' query in yaml for SQL similar to the 'requests' example from the documentation

### DISCUSSION THREAD

**Discussion by AmateurAcademic** [lowdefy/lowdefy#695] [Questions and Help] [answered]
Hi, I was trying to recreate the [ticket system example: requests](https://docs.lowdefy.com/tutorial-requests), and I just can't seem to get the yaml right. I tried to use the information provided about [Knex](https://docs.lowdefy.com/Knex). No matter what syntax I tried, I just couldn't wrap my head around it. It is also harder to play around with it until I get it right because of the lack of logging.

```
  - id: save_data
    type: KnexBuilder
    connectionId: mariadb
    properties:
      tableName: submitted_tickets
      query:
        - insert:
        ....
```
So more or less I am trying to recreate this query: 
```
INSERT INTO 'submitted_tickets' (ticket_title,ticket_type,ticket_description,confirm_restart,created_date)
VALUES (value1, value2, value3,...);
```

Where the valueN are the parameters to pass, similar to the example ticket system requests. Any ideas? 
Thanks very much!

**Comment by SamTolmay** [comment, marked as answer]
Hi @AmateurAcademic 

I think you could try something like:
```yaml
- id: save_data
  type: KnexBuilder
  connectionId: mariadb
  properties:
    tableName: submitted_tickets
    query:
      - insert:
          # this needs to be a list since args will be spread into 'insert' method
          - ticket_title:
              _state: ticket_title
            ticket_type:
              _state: ticket_type
            ticket_description:
              _state: ticket_description
            # ...
```
or, if you want to save the whole state:
```yaml
- id: save_data
  type: KnexBuilder
  connectionId: mariadb
  properties:
    tableName: submitted_tickets
    query:
      - insert:
          - _state: true
```

This will translate into:
```js
knex('submitted_tickets').insert({
  ticket_title: 'Ticket title',
  // ...
});
```

The way the `KnexBuilder` request works is that each item in the query list is a method on the knex object. The methods are chained, in the order of the query list. The arguments to the method are specified as an array.

So in this case we want to call the `insert` method, and give it an object `{ticket_title: 'Ticket title'}` as the first argument.

Please let me know if this helps, and if my example works, I am unable to test it to make sure at this time, but hopefully, this also helps with the general idea.

**Reply by AmateurAcademic** [reply]
@SamTolmay  thanks so much for the reply. I was so close with the first one, I just messed up putting in the hyphens correctly. Thanks for that. But for some reason it still doesn't work like that. It seems to work for the title, but not the other fields (the fields stay NULL, maybe I messed up something otherwise?). I don't get any errors, so I have no idea what is wrong there.

As for the second example, this works except for the date (because it isn't saved already as a state, I guess?). How do I include:

```
            - created_date: 
                _date: now
```
As a state?
Thanks again for the quick reply!

**Reply by SamTolmay** [reply]
I'm not sure what's going wrong with the fields that are null, maybe the state operator isn't set up correctly. To debug that, you can do two things.

Firstly, you can use the log operator. This will log to the server console if you use it in a request, so you can see the intermediate operator results. So you could do (for example):
```yaml
- id: save_data
  type: KnexBuilder
  connectionId: mariadb
  properties:
    tableName: submitted_tickets
    query:
      - insert:
          # this needs to be a list since args will be spread into 'insert' method
          - ticket_description:
              _log:
               _state: ticket_description
            # ...

```

The other thing you can do is explore the `lowdefy` object added to the window scope. In the browser console, type `lowdefy` and hit enter. In the development server, this object contains the full lowdefy application state on the client. The state for a specific page will be at: `lowdefy.contexts['pageId:pageId:{}'].state`, but feel free to explore the rest of that object.

**Reply by SamTolmay** [reply]
If you want to combine two data objects, like state and the created date, for example, you can use the `_object.assign` operator. So you can do:
```yaml
- id: save_data
  type: KnexBuilder
  connectionId: mariadb
  properties:
    tableName: submitted_tickets
    query:
      - insert:
          - _object.assign:
              - _state: true
              - created_date:
                   _date: now
```
