### DISCUSSION TITLE
Any examples of sending POST JSON data with AxiosHTTP?

### DISCUSSION THREAD

**Discussion by APTy** [lowdefy/lowdefy#705] [Questions and Help] [answered]
I'm currently trying to send JSON in post data following the [AxiosHTTP docs](https://docs.lowdefy.com/AxiosHttp), but having issues. Here is my config.

```yaml
requests:
  - id: create_user
    type: AxiosHttp
    connectionId: users_api
    properties:
      method: post
      url: /v1/users
      headers:
        content-type: application/json
      data:
        name: myself
```

I'd expect lowdefy-server to send `{"name":"myself"}`, but it looks like no data is being sent at all (from what I can tell on the api-server side).

1. Is there any way to verify what request the lowdefy server is sending? This would help a great deal with debugging so I can confirm it.
2. Does anyone know the proper usage for sending post data? I couldn't find any examples in the wild.

Currently running `lowdefy: 3.18.1`.

Thanks!

**Comment by Gervwyk** [comment, marked as answer]
Hi @APTy 

I cannot find what's wrong with your request. Perhaps share your connection and `Request` action setup?

Consider the following test example :
```yaml
lowdefy: 3.18.1
name: Lowdefy starter
connections:
  - id: axios
    type: AxiosHttp
pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    requests:
      - id: call
        type: AxiosHttp
        connectionId: axios
        properties:
          method: post
          url: https://mockbin.org/bin/9c8af6df-ba23-4e19-a860-ac6a032a27c8
          headers:
            content-type: application/json
          data:
            name: myself
    events:
      onEnter:
        - id: fetch
          type: Request
          params: call
```

When running this page the `onEnter` event triggers the request. You can view the request log for this example at: https://mockbin.org/bin/9c8af6df-ba23-4e19-a860-ac6a032a27c8/log

We're planning to add a verbose logging option to the cli in future versions. This will likely only be added in V4. If you have any advice, requirements or ideas for the logging implementation, it will be great if you can add it to #688
