### DISCUSSION TITLE
Concatenate lists on build time

### DISCUSSION THREAD

**Discussion by mat02** [lowdefy/lowdefy#736] [Questions and Help] [answered]
Is it possible to concatenate lists in YAML config files? 
I have some reusable actions and I would like to do something like this:
```
- id: fetch
  type: Request
  params:
    - request_1
- id: set
  type: SetState
  params:
    data:
      _get:
        _request: fetch.data
- _ref: process.yaml
```
where process.yaml contains reusable list of actions

Another usecase would be a list of resusable actions for events:
```
onInitAsync:
  - _ref: fetch_resources.yaml
  - _ref: fetch_options.yaml
```

**Comment by SamTolmay** [comment, marked as answer]
We have been planning to create build time operators to handle something like this. The issue is #619.

These operators would be evaluated at build time, so you would be able to do something like this:
```yaml
_build.array.concat:
  - - id: fetch
      type: Request
      params:
        - request_1
    - id: set
      type: SetState
      params:
        data:
          _get:
            _request: fetch.data
  - _ref: process.yaml
```

In the mean time, you can use an `_ref` operator transformer function to achieve this. It is a little hacky, but it shouldn't be hard to convert to build operators when they are released, so it might be a good idea to use this to keep your file structure in good shape. I am using the transformer to concat an array of `vars` passed to the reference operator. The path is to an empty file, since the `_ref` operator needs to resolve to something. Here are the files:
```yaml
# lowdefy.yaml
lowdefy: 3.19.0
pages:
  - id: welcome
    type: PageHeaderMenu
    blocks:
      _ref:
        path: concatArrays.yaml
        transformer: concatTransformer.js
        vars:
          toConcat:
            - _ref: one.yaml
            - _ref: two.yaml
```
```yaml
# concatArrays.yaml
# Empty file as a hack to use _ref transformer
[]
```
```js
// concatTransformer.js
function concatTransformer(_, { toConcat }) {
  return [].concat(...toConcat);
}

module.exports = concatTransformer;
```
```yaml
# one.yaml / two.yaml
- id: A
  type: Button
- id: B
  type: Button
```
