### DISCUSSION TITLE
Protected Pages with KeyCloak as the OpenID Connect Provider

### DISCUSSION THREAD

**Discussion by xiexj2** [lowdefy/lowdefy#774] [Questions and Help] [answered]
Hi, Guys

We use KeyCloak as the OpenID Connect provider, and the page that needs to be protected is ‘welcome’, which can only be accessed by users whose role is ‘app-admin’. The field of idToken for the roles, 'config.auth.openId.rolesField' is configured as 'resource_access.localapp.roles'. After the user 'xiexj' is logged in and authenticated, it can be viewed from the Chrome Console that lowdefy.user.resource_access.localapp.roles is [ "app-admin"], but  the protected page 'welcome' cannot be accessed. Where is the problem? Thanks for any hints.

```
auth:
    openId:
      rolesField: 'resource_access.lowdefy.roles' 
      logoutRedirectUri: 'http://localhost:3000/logged-out'       
    pages:
      protected: true
      public:
        - login
        - logged-out
        - '404'
     roles:
        app-admin:
          - welcome
```

![image](https://user-images.githubusercontent.com/17896329/130338532-ce9073b2-05d5-4eea-8739-0319d71bfa0d.png)
