### DISCUSSION TITLE
Menu according to the role

### DISCUSSION THREAD

**Discussion by xiexj2** [lowdefy/lowdefy#780] [Questions and Help] [answered]

**Comment by SamTolmay** [comment, marked as answer]
Hi @xiexj2

The Lowdefy menus are already filtered by role and page access. So if you are not logged in, only public pages will be visible in any menu. And if you don't have the required role, you won't be able to see those menu links. So everything should just work.

You can also specify different menus using the `_menu` operator. 

So you could do:
```yaml
# lowdefy.yaml
menus:
  - id: default
    links:
        # ...
  - id: other_menu
    links:
        # ...
```
And then use the other menu on a specific page:
```yaml
id: my-page
type: PageSiderMenu
properties:
  menu:
    _menu: other_menu
# ...
```
