### DISCUSSION TITLE
_hash operator

### DISCUSSION THREAD

**Discussion by Radiergummi** [lowdefy/lowdefy#782] [Ideas and feature requests]
I would like to suggest a `_hash` operator to generate various hashes, as provided by [node's `crypto` module](https://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm_options), thus limiting it to server-side. The operator could be used as follows:
```yaml
_hash.sha1: value_to_hash
_hash.sha256: value_to_hash
_hash.md5: value_to_hash
```

The implementation could be something like:
```ts
import crypto from 'crypto';

type Hash = 'md5' | 'sha1' | 'sha265';

export default function (algorithm: Hash, data: string): string {
  return crypto
    .createHash(algorithm)
    .update(data)
    .digest("hex");
}
```
