### DISCUSSION TITLE
_switch operator

### DISCUSSION THREAD

**Discussion by Radiergummi** [lowdefy/lowdefy#822] [Ideas and feature requests]
Sometimes I'm missing a switch-case operator. Think of something like a ticket status (open, pending, confirmed, blocked, closed) - merely displaying the correct icon per status is a real pain using `_if` constructs alone, as it would be in any programming language - that's what switch-cases or match expressions are for:
```yaml
icon:
  _if:
    test:
      _eq:
        - _state: ticket.status
        - _state: open
    then: IconNameOutlined
    else:
      _if:
        test:
          _eq:
            - _state: ticket.status
            - _state: pending
        then: SomeOtherIconNameOutlined
        else:
          _if:
            test:
              _eq:
                - _state: ticket.status
                - _state: confirmed
            then: RandomIconNameOutlined
            else:
              # and so on
```

Now, the same could be written elegantly with a `_switch` operator:
```yaml
icon:
  _switch:
    on:
      _state: ticket.status
    cases:
      open: IconNameOutlined
      pending: SomeOtherIconNameOutlined
      confirmed: RandomIconNameOutlined
```

**Comment by SamTolmay** [comment]
I have also been missing a switch operator. We have an issue tracking this: [#689](https://github.com/lowdefy/lowdefy/issues/689)

This is an interesting syntax, very similar to the JavaScript switch. We were thinking of doing something similar to the MongoDB `$switch` operator. I have an example of the syntax in the issue.

**Comment by SamTolmay** [comment]
I just realised you can achieve the same thing you need using the `_get` operator:
```yaml
_get:
  key:
    _state: input
  from:
    value1: Value One
    value2: Value Two
```
