### DISCUSSION TITLE
_Array.reduce Operator

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#842] [Questions and Help] [answered]
Hello, How to use the _array.reduce operator? Can you give an example?

**Comment by JohannMoller** [comment, marked as answer]
Hi @xiaoxiji1234 ,

The `_array.reduce` operator is basically just [Array.prototype.reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce).
It executes a function (specified in `callback` ) on each element of the array (specified in `on`) and passes the result of the function on to the next step. We use the [_function](https://docs.lowdefy.com/_function) operator to create the callback function.
`_array.reduce` returns 4 arguments that can be used in the `callback` function:
- `_args: 0`: The result of the previous calculation.
- `_args: 1`: The value of the current array element.
- `_args: 2`: The index of the current array element.
- `_args: 3`: The array over which the function is looping (basically the same as the array specified in `on`).

The simplest example would probably be adding all the elements in an array:
```yaml
sum:
  _array.reduce:
    on: [1, 2, 3, 4]
    callback:
      _function:
        __sum:
          - __args: 0
          - __args: 1
```
This will return `sum: 10`

You can start off by counting from 10 by specifying an `initialValue` for the reducer function:
```yaml
sum:
  _array.reduce:
    on: [1, 2, 3, 4]
    callback:
      _function:
        __sum:
          - __args: 0
          - __args: 1
    initialValue: 10
```
This will return `sum: 20`

You can use the index of the array element to add some logic to your `callback`. For instance, when you reach index 2 of your array (the 3rd entry), add 100 instead of the current element value:
```yaml
sum:
  _array.reduce:
    on: [1, 2, 3, 4]
    callback:
      _function:
        __sum:
          - __args: 0
          - __if:
              test:
                __eq:
                  - __args: 2
                  - 2
              then: 100
              else:
                __args: 1
```
This will return `sum: 107`

Do these examples help in explaining the use of `array.reduce` better?
