### DISCUSSION TITLE
AxiosHTTP configure

### DISCUSSION THREAD

**Discussion by AndriiSydorenko1904** [lowdefy/lowdefy#855] [Questions and Help] [answered]
Hi,
How I can configure BaseURL into .env for AxiosHTTP connector?

**Comment by SamTolmay** [comment, marked as answer]
Hi @AndriiSydorenko1904 

You can use the [`_secret`](https://docs.lowdefy.com/_secret) operator to use an environment variable in a connection or request. You can set Lowdefy secrets by creating an environment variable starting with `LOWDEFY_SECRET_`.

In your .env file you can set:
```
LOWDEFY_SECRET_API_BASE_URL = https://example.com/api/
```

Then in your connection config:
```yaml
connections:
  - id: api
    type: AxiosHttp
    properties:
      baseURL:
        _secret: API_BASE_URL
```
