### DISCUSSION TITLE
AxiosHttp and send get request with url params

### DISCUSSION THREAD

**Discussion by AndriiSydorenko1904** [lowdefy/lowdefy#861] [Questions and Help] [answered]
Hello,
I want to create get request with url params
my request

```
requests:
  - id: get_translation_id_namespace
    type: AxiosHttp
    connectionId: translate_api
    properties:
      _log:
        url: /translations
        query:
          id:
            _url_query: id
          namespace:
            _url_query: namespace
events:
  onEnter:
    - id: fetch_translation
      type: Request
      params: get_translation_id_namespace
```

in my console log is
`
{
  url: '/translations',
  query: {
    id: '614c80e38557139efea4e651',
    namespace: 'test'
  }
}
`

But the backend does not receive parameters
When I use curl:

`
curl "http://127.0.0.1:8002/translations?id=614c80e38557139efea4e651&namespace=test"
`
My backend receive parameters

**Comment by SamTolmay** [comment, marked as answer]
The Axios library uses the params key for url query params. So your request should be:
```yaml
requests:
  - id: get_translation_id_namespace
    type: AxiosHttp
    connectionId: translate_api
    properties:
      _log:
        url: /translations
        params:
          id:
            _url_query: id
          namespace:
            _url_query: namespace
```
