### DISCUSSION TITLE
fetching array items by their index position

### DISCUSSION THREAD

**Discussion by acivitillo** [lowdefy/lowdefy#863] [Docs]
I just found out that fetching items from an array is done using the `.` notation instead of the `[]` one. I can send you a PR to update the docs, but the question is where should we document this in the docs? My proposal is to add a tutorial "Working with Objects".

Say we have a json response like this one:

```json
[
  {"label":"Italy","value":1,"disabled":false,"filterString":null}
  , {"label":"Germany","value":1,"disabled":false,"filterString":null}
]
```

And a request defined like so:

```yaml
connections:
  - id: app_api
    type: AxiosHttp
    properties:
      baseURL:  http://127.0.0.1:8000
requests:
  - id: get_countries
    type: AxiosHttp
    connectionId: app_api
    properties:
      url: /dropdowns/dd_countries
```

And we wanted to show the country label of the `first` item of the countries array, we would do it like this:

```yaml
id: content
    type: Result
     properties:
          title: Welcome to your Lowdefy app
           subTitle: 
                _request: get_countries.data.0.label #<- check here
```

Basically we need to do `get_countries.data.0.label` instead of `get_countries.data[0].label`. We also need to use `.data` which is documented here in an answer but it is not super clear from the docs.
