### DISCUSSION TITLE
Dynamic pages and container Tabs

### DISCUSSION THREAD

**Discussion by AndriiSydorenko1904** [lowdefy/lowdefy#871] [Questions and Help] [answered]
Hello
I am creating an admin service for several projects and these projects can have different services. To choose a project, I decided to select the Tabs component. But it's not clear to me how it works.
Could you tell me how to display the different containers by clicking on a tab?

**Comment by SamTolmay** [comment, marked as answer]
Hi @AndriiSydorenko1904 

A normal container block has predefined content areas like `content`, `extra`, or `footer`.  The [`Tabs`](https://docs.lowdefy.com/Tabs) component has user-defined content areas. That means you need to specify the content areas in your config, at `properties.tabs`. A simple example with two tabs is:

```yaml
id: my_tabs
type: Tabs
properties:
  tabs:
    - key: tab1
      title: Tab 1
    - key: tab2
      title: Tab 2
areas:
  tab1:
    blocks:
      - id: tab_1_content
        type: Title
        properties:
          content: Tab 1 content
  tab2:
    blocks:
      - id: tab_2_content
        type: Title
        properties:
          content: Tab 2 content
```
Because I have defined two tabs with keys `tab1` and `tab2`, the tabs block now has 2 content areas `tab1` and `tab2` in which I can place blocks. 

The Tabs block also has an "extra" content area, which is a content area to the right of the tabs. To use this area, you need to provide a name for this area in the `extraAreaKey` property:
```yaml
id: my_tabs
type: Tabs
properties:
  extraAreaKey: extra
  tabs:
    - key: tab1
      title: Tab 1
    - key: tab2
      title: Tab 2
areas:
  extra:
    blocks:
      - id: extra
        type: Button

  tab1:
    blocks:
      - id: tab_1_content
        type: Title
        properties:
          content: Tab 1 content
  tab2:
    blocks:
      - id: tab_2_content
        type: Title
        properties:
          content: Tab 2 content
```
