### DISCUSSION TITLE
markdown eat http response new line.

### DISCUSSION THREAD

**Discussion by huangmingyou** [lowdefy/lowdefy#873] [Questions and Help] [answered]
a http request get a response like " line1\n line2"; 
use markdown show this content ,will no new line . 
how to resolve this problem?

**Comment by SamTolmay** [comment, marked as answer]
Hi @huangmingyou 

In markdown syntax, you need two new lines to render a new line. So this will render without a new line:
```yaml
id: md
type: Markdown
properties:
  content: "line1\nline2"
```
But this will render with a new line:
```yaml
id: md
type: Markdown
properties:
  content: "line1\n\nline2"
```
If you can't change your API response, you can use the `_string.replace` operator to replace a single new line with two newlines:
```yaml
id: md
type: Markdown
properties:
  content:
    _string.replace:
      on: "line1\nline2"
      regex: \n
      newSubstr: "\n\n"
      regexFlags: g
```
