### DISCUSSION TITLE
how format date

### DISCUSSION THREAD

**Discussion by huangmingyou** [lowdefy/lowdefy#875] [Questions and Help] [answered]
a api need a time format like "YYYY-MM-DD HH:MM:SS", but I can't find ad method send this format date.

I had test _format , _string method.

**Comment by JohannMoller** [comment, marked as answer]
Hi @huangmingyou,

You can format a date either using the [`_nunjucks`](https://docs.lowdefy.com/_nunjucks) operator's date filter:
```yaml
_nunjucks: 
  template: '{{ my_date | date("YYYY-MM-DD hh:mm:ss") }}'
  on:
   my_date:
     _date: now
```

or with the [`_format.momentFormat`](https://docs.lowdefy.com/_format) operator:
```yaml
_format.momentFormat:
  on:
    _date: now
  params:
    format: 'YYYY-MM-DD hh:mm:ss'
```

There is also a [`_format.intlDateTimeFormat`](https://docs.lowdefy.com/_format) operator which you can have a look at.

I hope this helps.

**Comment by huangmingyou** [comment]
I make a request. but send null , 
test in a markdown , _format will work. 
so, _format can't use in a request ?

```yaml
  - id: post_add
    type: AxiosHttp
    connectionId: wgqapi
    properties:
      url: /addCapacity/
      method: post
      data:
        orderNo:
          _state: oid
        userId:
          _state: uid
        phone:
          _state: phone
        capType: 3
        type: 1
        startTime:
          _format.momentFormat:
            on:
              _date: 2019-01-01
            params:
              format: 'YYYY-MM-DD hh:mm:ss'

```

**Comment by huangmingyou** [comment]
I had use the SetState action save the _format.momentFormat to state. then use it ,will work !

**Comment by JohannMoller** [comment]
Yes, sorry I forgot to mention the `_format` operator only works client-side, so you cannot use it in a request. Setting it in state first and then using the state value, as you did, is a good workaround. 
Another option would be to format the date in the request using `_nunjucks` (my first example) since the `_nunjucks` operator can be used in requests.

**Comment by jmarshall222** [comment]
This was a great thread to stumble across, thanks for this information Johann!

Just as a note for anyone else who comes to this thread in the future, the nunjucks code had an extra quote mark in it which meant it was returning a null value. The corrected code that will return a date value is:

```yaml
                _nunjucks: 
                  template: '{{ my_date | date("YYYY-MM-DD hh:mm:ss") }}'
                  on:
                    my_date:
                      _date: now
```

Further information on the date string formatting can be found [here](http://momentjs.com/docs/#/displaying/format/)
