### DISCUSSION TITLE
No results using KnexRaw request

### DISCUSSION THREAD

**Discussion by stefaschmi** [lowdefy/lowdefy#877] [Questions and Help] [answered]
#### Describe the bug

I started playing around with lowdefy to list entries from a Postgres database. If I use KnexRaw to fetch the data I can see in the Postgres stats that the SQL query reaches the database, but the list remains empty. If I change KnexRaw to KnexBuilder everything works fine. Therefore I know that at least the connection settings are correct.

#### To Reproduce
This is the request which doesn't show any data in the list, though the SQL query is shown in the Postgres stats. To be sure that the SQL is correct I tried different versions of the query (with and without ";" and quotation marks). Since KnexBuilder works I made sure that the exact same query is shown in the Postgres stats.
```yaml
- id: user_list
  type: KnexRaw
  connectionId: mydb
  properties:
    query: select name from "users"
```

This KnexBuilder request works.
```yaml
- id: user_list
  type: KnexBuilder
  connectionId: mydb
  properties:
    query:
      - select:
        - name
      - from:
        - users
```
#### Lowdefy Version

v3.22.0

**Comment by SamTolmay** [comment, marked as answer]
Hi @stefaschmi 

The responses from the `KnexBuilder` and `KnewRaw` are different. The response from the builder request (in YAML) is:
```yaml
- name: Sam
- name: Gerrie
```
where the response from the raw request is:
```yaml
RowCtor: null
command: SELECT
fields:
  - columnID: 2
    dataTypeID: 25
    dataTypeModifier: -1
    dataTypeSize: -1
    format: text
    name: name
    tableID: 16386
oid: null
rowAsArray: false
rowCount: 2
rows:
  - name: Sam
  - name: Gerrie
```

So to access the rows response using the raw request you would need to change from using `_request: user_list` to `_request: user_list.rows`

You can see the response of the request using the `_log` operator, or by looking at the `lowdefy` object that is added to `window` when running the development server. To explore this object, open the browser console, type `lowdefy` and press enter. The requests be at `lowdefy.contexts["pageId:pageId:{}"].requests`.
