### DISCUSSION TITLE
How to use context.actions.Request with JsAction for data polling

### DISCUSSION THREAD

**Discussion by monica0529** [lowdefy/lowdefy#878] [Questions and Help] [answered]
I want to call a request and get the response data  in jsaction function .Following is the code:
````yaml
app:
  html:
    appendBody: |
      <script>  
        function fetchrequest(context) {
          var datarequestid = context.requests.datarequestid;  //datarequest is request id.      
          var dataResponse = context.state.dataResponse;
          var data = context.state.data;  //data is a variable in page
          var tempResponse = context.actions.Request({ datarequestid });
          context.actions.SetState({ tempResponse });   //tempResponse is a variable in page
          data = tempResponse.data.length;
          context.actions.SetState({ data });
        }

        function execfetchrequest(context) {
          setTimeout(function () {
            fetchrequest(context);
          }, 0);
          setInterval(function () {
           fetchrequest(context);
          }, 3000);
        }        
        window.lowdefy.registerJsAction('fetchrequest', fetchrequest);
        window.lowdefy.registerJsAction('execfetchrequest', exefetchrequest);

**Comment by monica0529** [comment]
following is the code of  the page :
```yaml
id: data_request
type: PageHeaderMenu
properties:
  title: data_request
requests:  
  - id: datarequestid
    type: AxiosHttp
    connectionId: axios
    properties: 
      url: 
        _secret: TMP_REQUEST
      method: get
layout:
  contentGutter: 16 
events:
  onEnter:
    - id: fetchTempDataList
      type: Request
      params: datarequestid
    - id: setTempDataList
      type: SetState
      params:
        tempResponse:
            _request: datarequestid
    - id: setdata
      type: SetState
      params:
        data:
          _array.length:  
                  _state:   tempResponse.data
    - id: call_execfetchrequest
      type: JsAction
      params:
        name: execfetchrequest
        args:
          - _location: pageId 
```

**Comment by Gervwyk** [comment, marked as answer]
Hi @monica0529 

This is a really cool example. I've not tried something like this before, but it works well. 
See this basic example for polling to https://postman-echo.com

```yaml
lowdefy: 3.22.0
name: Lowdefy Demo
connections:
  - id: my_connection
    type: AxiosHttp
    properties:
      baseURL: https://postman-echo.com
app:
  html:
    appendHead: |
      <script>
        function pollRequest(context, requestId) {
          setInterval(() => context.actions.Request(requestId), 1000);
        }
        window.lowdefy.registerJsAction('pollRequest', pollRequest);
      </script>
pages:
  - id: welcome
    type: PageHeaderMenu
    requests:
      - id: my_request
        type: AxiosHttp
        connectionId: my_connection
        properties:
          url: /post
          method: post
          data:
            call_time:
              _date: now
    events:
      onEnter:
        - id: init_data
          type: Request
          params: my_request
        - id: start_refresh
          type: JsAction
          params:
            name: pollRequest
            args:
              - my_request
    blocks:
      - id: response
        type: Markdown
        properties:
          content:
            _nunjucks:
              template: |
                ```
                # Postman response
                {{ data | safe }}
                ```
              on:
                data:
                  _yaml.stringify:
                    - _request: my_request
```

For your implementation, I see that you are trying to do a little more using SetState, consider the following code for your implementation:
```yaml
lowdefy: 3.22.0
name: Lowdefy Demo
connections:
  - id: my_connection
    type: AxiosHttp
    properties:
      baseURL: https://postman-echo.com
app:
  html:
    appendHead: |
      <script>
        async function fetchRequest(context, requestId) {
          const tempResponse = await context.actions.Request(requestId);
          context.actions.SetState({ data: tempResponse.data.length, tempResponse });
        }
        function pollRequest(context, requestId) {
          setInterval(() => context.actions.Request(requestId), 1000);
        }
        window.lowdefy.registerJsAction('pollRequest', pollRequest);
      </script>
pages:
  - id: data_request
    type: PageHeaderMenu
    properties:
      title: data_request
    requests:
      - id: datarequestid
        type: AxiosHttp
        connectionId: axios
        properties:
          url:
            _secret: TMP_REQUEST
          method: get
    layout:
      contentGutter: 16
    events:
      onEnter:
        - id: fetchTempDataList
          type: Request
          params: datarequestid
        - id: setTempDataList
          type: SetState
          params:
            tempResponse:
              _request: datarequestid
            data:
              _array.length:
                _request: datarequestid
        - id: call_execfetchrequest
          type: JsAction
          params:
            name: pollRequest
            args:
              - datarequestid
```

**Comment by xm0809** [comment]
Thank you very much! But still have some question:
1:   Does the async function named  ‘fetchRequest’  need to be registerJsAction？ 
2：Error  message found: "tempResponse is not defined"  in  async function fetchRequest. why？
3:    Does the async function named  ‘fetchRequest’  need to be called  in  onEnter event  like this ？ 
```
        - id: call_fetchrequest
          type: JsAction
          params:
            name:  fetchRequest
            args:
              - datarequestid
 ```
4:   Does the param  ‘context’  need to be added  when JsAction is called  in onEnter event when the request  is in  a separate page? like this?
```
    - id: call_pollRequest
      type: JsAction
      params:
        name: pollRequest
        args:
          - _location:  pageId    #Is pageid or contextid required when the request  is in  a separate page?
          - getTemplateList
```

**Reply by SamTolmay** [reply]
Hi @xm0809

1. You do not need to register the function `fetchRequest ` as a Lowdefy JsAction, since it is called by the `pollRequest` function. The purpose of `window.lowdefy.registerJsAction('pollRequest', pollRequest);` is to expose the `pollRequest` function to the Lowdefy engine so it can be called from inside Lowdefy.

2. The tempResponse variable might be undefined because the requestId  provided is undefined. I would log the requestId and tempResponse variables to see what is going on. You might also want to throw an error if the requestId is undefined. Lastly, the Request function returns an array, so you need to use the first element in the returned array (change `tempResponse.data.length` to `requestResponse[0].data.length`). So you could do:
```js
async function fetchRequest(context, requestId) {
  console.log('requestId', requestId);
  if (!requestId) {
    throw new Error("requestId is undefined")
  }
  const requestResponse = await context.actions.Request(requestId);
  console.log('requestResponse', requestResponse);
  context.actions.SetState({ data: requestResponse[0].data.length, tempResponse: requestResponse[0] });
}
```

3. We are using the Lowdefy `Request` and `SetState` actions to do the same thing:
```yaml
events:
  onEnter:
    - id: fetchTempDataList
      type: Request
      params: datarequestid
    - id: setTempDataList
      type: SetState
      params:
        tempResponse:
          _request: datarequestid
        data:
          _array.length:
            _request: datarequestid
```
You can call the `fetchRequest` function as a JsAction instead, but then you would need to register it as a JsAction.

4. The param `context` is added automatically by the Lowdefy engine as the first argument to your action function, and then your args are added as additional arguments. The context operator contains data objects like `state` and `event`, and also contains all the action functions like `Request` and `SetState`. The `_location` operator you are using will return the pageId as a string, not the context. Your function will receive arguments `pollRequest(context, pageId, requestId)`. You can log the context object to have a look at it.


Please let me know if you have any other questions of if anything is unclear.
