### DISCUSSION TITLE
How do I store a variable?

### DISCUSSION THREAD

**Discussion by AndriiSydorenko1904** [lowdefy/lowdefy#880] [Questions and Help] [answered]
There are two projects that use the same service. Each project has its own database. I write the admin panel in which I select a project, after which I select a service and go to the admin panel of this service. The service communicates with the backend via AxiosHttp and I thought it would be nice if the backend was given information about what service I chose.
When I select a project, let some parameter `project` take the conditional value `my_project1` and when I do some actions in the service, let the url `{project}/action -> my_project1/action` be generated.
How much is it possible to implement it? I would not want to duplicate the entire service for another project, changing only the url

**Comment by SamTolmay** [comment, marked as answer]
Hi @AndriiSydorenko1904 

You should be able to use the Lowdefy `global` data object to achieve this.

When you select the project, you can set the project parameter using the [`SetGlobal`](https://docs.lowdefy.com/SetGlobal) action. For example:
```yaml
id: project_selector
type: Selector
properties:
  options:
    - label: Project 1
      value: project_1
    - label: Project 2
      value: project_2
events:
  onChange:
    - id: set_project
      type: SetGlobal
      params:
        project:
          _state: project_selector
```

You can then use the value in your request using the [`_global`](https://docs.lowdefy.com/_global) operator:
```yaml
id: api_req
type: AxiosHttp
connectionId: api
properties:
  url:
    _nunjucks:
      template: "/{{ project }}/action"
      on:
        project:
          _global: project
``` 

I hope this suits what you are trying to do. Otherwise, please let me know 😀
