### DISCUSSION TITLE
dynamic menu

### DISCUSSION THREAD

**Discussion by AndriiSydorenko1904** [lowdefy/lowdefy#885] [Questions and Help]
Hello))
I want to implement the ability to display services in the menu depending on the config in .env
For example
.env
`
LOWDEFY_SECRET_MY_SERVICE = 1
`

and lowdefy.yaml
```
menus:
  - id: default
    links:
      - id: home
        type: MenuLink
        properties:
          title: Home
        pageId: homepage
      (if MY_SERVICE == '1')
        - id: my_service
          type: MenuLink
          pageId: my_service
          properties:
            title: Translation

pages:
  - _ref: home.yaml
  (if MY_SERVICE == '1')
    - _ref: services/my_service/page1.yaml
    - _ref: services/my_service/page2.yaml
```

Is it possible to do this or is it better to write a parser to build lowdefy.yaml?

**Comment by SamTolmay** [comment]
Hi @AndriiSydorenko1904 

We have had a similar need, and our proposed solution is to create Lowdefy operators that are run at build time. You can have a look at #619 for the Github issue.

You can look at [`_ref`](https://docs.lowdefy.com/_ref) operator `resolver` or `transformer`  functions to solve this.

Resolver functions are JavaScript functions that are called instead of just reading the file from disk. So you could do something like look at the environment variable, and then first check in a folder for the specific file for that service, otherwise use a default file.

Transformer functions are also JavaScript functions, that are run after the reference has been resolved and the `_var` operators evaluated. 

I will post examples using the different functions as separate answers.

**Comment by SamTolmay** [comment]
# Resolver function example

The idea of this example is to have separate files for each different service. The resolver function will first check for the file in the `service_name` directory, and use the file in the `default` directory if it is not found. We can set this as the default resolver, so all `_ref` operators will use this resolver function. 

With directory structure:
```text
|-- my_service
|   |-- pages
|   |   |-- page1.yaml
|   |   `-- page2.yaml
|   |-- menu.yaml
|   `-- pages.yaml
|-- default
|   |-- pages
|   |   `-- home.yaml
|   |-- menu.yaml
|   `-- pages.yaml
|-- resolvers
|   `-- useServiceOrDefaultConfig.js
`--lowdefy.yaml
```

```js
// resolvers/useServiceOrDefaultConfig.js
const fs = require('fs')
const path = require('path')
const { promisify } = require('util');

const readFilePromise = promisify(fs.readFile);

async function useServiceOrDefaultConfig(path, vars, context) {
  const service = process.env.MY_SERVICE
  const serviceFile =  await readFilePromise(path.resolve(service, path), 'utf8');

  if (serviceFile) return serviceFile;

  return readFilePromise(path.resolve('default', path), 'utf8');
}

module.exports = useServiceOrDefaultConfig.js;
```

```yaml
# lowdefy.yaml
lowdefy: 3.22.0

cli:
  refResolver: resolvers/useServiceOrDefaultConfig.js

menus:
  _ref: menus.yaml

pages:
  _ref: pages.yaml
```

```yaml
# default/pages.yaml
- _ref: home.yaml
```

```yaml
# my_service/pages.yaml
- _ref: home.yaml
- _ref: pages/page1.yaml
- _ref: pages/page2.yaml
```


You only need to define the `home` page once, since the resolver will resolve it from the `default` folder if it's not found in the `my_service` folder.

**Comment by SamTolmay** [comment]
# Transformer function example

The resolver function example is probably more scalable in the future, but adding this here for reference.

```js
// addServiceTransformer.js
function addServiceTransformer(obj) {
  const service = process.env.MY_SERVICE // This is equal to "my_service" or "other_service"

  const serviceItems = obj[service] || [];
  return [
    ...obj.default,
    ...serviceItems
  ]
}

module.exports = addServiceTransformer.js;
```

Then you have:
```yaml
# lowdefy.yaml
lowdefy: 3.22.0

pages:
  _ref:
    path: pages.yaml
    transformer: addServiceTransformer.js
```

```yaml
# pages.yaml
default:
  - _ref: home.yaml
my_service:
  - _ref: services/my_service/page1.yaml
  - _ref: services/my_service/page2.yaml
other_service:
  - _ref: services/other_service/page1.yaml
  - _ref: services/other_service/page2.yaml
```
