### DISCUSSION TITLE
mssql connection error

### DISCUSSION THREAD

**Discussion by SysLibreFR** [lowdefy/lowdefy#909] [Questions and Help] [answered]
Hello and thanks for this excellent soft.

I have an error with my mssql connection
```
type: 'Request', error: Error: Request Error: r.Connection is not a constructor at Object.<anonymous> (https://blocks-c…
```

my connections is
```yaml
connections:
  - id: pmi
    type : Knex
    properties:
      client: mssql
      connection:
        host:
          _secret: pmi
        database:
          _secret: pmi
        user:
          _secret: myuser
        password:
          _secret: mypassword
```
and my resquest is
```yaml
requests:
  - id: req_Pret
    type: KnexRaw
    connectionId: pmi
    properties:
      query: SELECT ARKTCODART AS appareil FROM ARTICLE WHERE ARCTTYPART = 'PR' AND ARKTSOC = '100' ORDER BY ARKTCODART;
```
my mssql node module is version 6.14.4 and my node version 10.19.0

**Comment by SamTolmay** [comment, marked as answer]
Hi @SysLibreFR 

I am glad you find Lowdefy useful.

I believe the issue might be because you are using Node at v10. We officially only support node v12 and up.

Is it possible for you to try running the same with a newer version of node?

**Reply by SysLibreFR** [reply]
Thanks,
I have updated my nodejs to 16 and my mssql to 7.2.1.

I now have this message

> Request', error: Error: Request Error: The "config.server" property is required and must be of type string. at O…, index: 0

I can't find the config.server property in the documentation.

Jean-charles

**Reply by SamTolmay** [reply]
Great to hear the first issue has been resolved. 😀

The Knex connections pass the connection data to the underlying driver library, which in this case is [node-mssql](https://github.com/tediousjs/node-mssql).

The example in the Knex documentation which we worked from uses a `host` parameter, but it seems the correct parameter is `server`. So your connection should probably be:
```yaml
connections:
  - id: pmi
    type : Knex
    properties:
      client: mssql
      connection:
        server:
          _secret: pmi
        database:
          _secret: pmi
        user:
          _secret: myuser
        password:
          _secret: mypassword
```

We will correct this in our docs.

You can also use a connection string, which looks like: `'Server=localhost,1433;Database=database;User Id=username;Password=password;Encrypt=true'`

**Reply by SysLibreFR** [reply]
Change from host to server change the error

my problem is now how to add    

 "trustServerCertificate": true

In my connection string. 

I add this to my .mssql.json and try some request with the mssql cli (echo "select * from ALERTE" | mssql .mssql.json) and it sends me the result i want. Without this param I have a connection error.

Thanks,

Jean-Charles

**Reply by SamTolmay** [reply]
It looks like you should be able to set the `trustServerCertificate` option:
```yaml
connections:
  - id: pmi
    type : Knex
    properties:
      client: mssql
      connection:
        server:
          _secret: pmi
        database:
          _secret: pmi
        user:
          _secret: myuser
        password:
          _secret: mypassword
        options:
          trustServerCertificate: true
```

**Reply by SysLibreFR** [reply]
Thanks, it’s working now

I have to remove all the _secret: and add the information next to the param (ie. server: pmi)

Did the password fly unencrypted between the servers?

**Reply by SamTolmay** [reply]
If you don't use the `_secret` parameter, the secret will not be passed to the web client, but the secret will be inside your code, which is still a bad practice.

You can set the secrets by setting an environment variable `LOWDEFY_SECRET_{{NAME}}`. You can then access this secret using `_secret: NAME`.

When running the development server, you can set these environment variables by creating a file called `.env` next to your `Lowdefy.yaml` file:
```
LOWDEFY_SECRET_MSSQL_SERVER = my server
LOWDEFY_SECRET_MSSQL_DB = mydatabase
LOWDEFY_SECRET_MSSQL_USER = myuser
LOWDEFY_SECRET_MSSQL_PASSWORD = mypassword
```

Then your connection is:
```yaml
connections:
  - id: pmi
    type : Knex
    properties:
      client: mssql
      connection:
        server:
          _secret: MSSQL_SERVER
        database:
          _secret: MSSQL_DB
        user:
          _secret: MSSQL_USER
        password:
          _secret: MSSQL_PASSWORD
        options:
          trustServerCertificate: true
```
This also lets you configure different values for development and production.
