### DISCUSSION TITLE
sql file with parameters

### DISCUSSION THREAD

**Discussion by SysLibreFR** [lowdefy/lowdefy#914] [Questions and Help] [answered]
Hello,

I succeed building a small application with Lowdefy. 

My users can now have a list of some data with complex SQL on mssql with a nice layout.

I now want to add some filters to this list, and I want to add some parameters to my SQL. 

Can I add a parameter on a SQL file and _ref it on my YAML?

Jean-Charles

**Comment by SamTolmay** [comment, marked as answer]
Hi @SysLibreFR 

If you are using the `KnexRaw` request, it supports both named and positional parameters.

You can read the Knex docs on it here:
https://knexjs.org/#Raw-Bindings

From their docs:

> Positional bindings ? are interpreted as values and ?? are interpreted as identifiers.

> Named bindings such as :name are interpreted as values and :name: interpreted as identifiers.


So you can do things like:
```yaml
# Named bindings
id: knexRaw
type: KnexRaw
connectionId: knex
properties:
  query: select * from users where name = :name
  parameters:
    name:
      _state: selected_name
```

```yaml
# Named bindings
id: knexRaw
type: KnexRaw
connectionId: knex
properties:
  query: select * from table where :field: = :value
  parameters:
    field:
      _state: filter_field
   value:
      _state: filter_value
```

```yaml
# positional bindings
id: knexRaw
type: KnexRaw
connectionId: knex
properties:
  query: select * from users where name = ?
  parameters:
    - _state: selected_name
```

```yaml
# positional bindings
id: knexRaw
type: KnexRaw
connectionId: knex
properties:
  query: select * from  table where ?? = ?
  parameters:
    - _state: filter_field
    - _state: filter_value
```

I would recommend going with named bindings since it is easier to read and more resistant to bigs if you make changes in the future.

I am using the `_state` operator to get the values of the inputs from state. I am assuming you have something like a selector where the user chooses the filter value.

You could also use the `_ref` operator, which would read the value from another file, which I don't believe is what you want to do. One use case that would make sense is to write the query in a `.sql` file and `_ref` that. The you will have your text editors syntax highlighting and other language features in that file:
```yaml
id: knexRaw
type: KnexRaw
connectionId: knex
properties:
  query:
    _ref: my_query.sql
```

**Reply by SysLibreFR** [reply]
Thanks for the explanation.

My query seems too long for direct integration in YAML, so I use a SQL file and _ref it in my YAML.

How did Lowdefy integrate the value of the _state in the SQL file found in the _ref: ?

How do I add :name in my SQL file for integration of both file (SQL File and YAML file)?

Jean-Charles

**Reply by SamTolmay** [reply]
> My query seems too long for direct integration in YAML, so I use a SQL file and _ref it in my YAML.

This is a good reason to use the `_ref`.

> How did Lowdefy integrate the value of the _state in the SQL file found in the _ref: ?

Lowdefy sends the value of `_state` to the server, so you can use the values in state in requests. So when you use  `_state: name`, that is replaced by the value in state (the value the user selected) when the request is executed.

> How do I add :name in my SQL file for integration of both file (SQL File and YAML file)?

You use `:name` in your SQL file where it should be substituted. You set the value of name as the parameters property of the request. I.e:
```yaml
id: knexRaw
type: KnexRaw
connectionId: knex
properties:
  query:
    _ref: my_file.sql
  parameters:
    name: MY_NAME_VALUE # Could be the result of evaluating the _state or other operators, or just hard coded.
```

Hope this answers the questions 😀
