### DISCUSSION TITLE
Cache Request values

### DISCUSSION THREAD

**Discussion by SysLibreFR** [lowdefy/lowdefy#916] [Questions and Help]
Hello,

My internal app is working now, and I want to make some optimization.

I have a SQL request with params and two selectors to change the values of the request params.

My application launch a new SQL request each time a user change the selection.

Can I launch a global SQL request and then filter the result in the _state without doing again a new SQL request?

Thanks,

Jean-Charles

**Comment by SamTolmay** [comment]
Hi @SysLibreFR 

I have created a demo app that does this. It uses the Postman echo API as a dummy connection. You can run it and play around with it and see if it does what you need.

The idea is to set the value in state after you fetch it, and to use the `skip` property on actions to skip executing the actions if the data already exists.

```yaml
lowdefy: 3.22.0

connections:
  - id: api
    type: AxiosHttp
    properties:
      baseURL: https://postman-echo.com/post
      method: post

pages:
  - id: page
    type: PageHeaderMenu
    events:
      onInit:
        - id: init
          type: SetState
          params:
            selector_1: A
            selector_2: X
    requests:
      # This API call will echo the data we send it
      - id: call_api
        type: AxiosHttp
        connectionId: api
        properties:
          data:
            selector_1:
              _state: selector_1
            selector_2:
              _state: selector_2
    blocks:
      - id: selector_1
        type: Selector
        properties:
          allowClear: false
          options:
            - A
            - B
            - C
        events:
          onChange:
            - id: call_request
              type: Request
              # Skip the request if the data is already in the cache
              skip:
                _ne:
                  - _get:
                      from:
                        _state: cache
                      key:
                        # Concat selector values to find the right cache key
                        _string.concat:
                          - _state: selector_1
                          - ':'
                          - _state: selector_2
                  - null
              # Show messages to show if request is executed or skipped
              messages:
                loading: true
                success: true
              params:
                - call_api
            - id: set_request
              type: SetState
              # Skip same as above
              skip:
                _ne:
                  - _get:
                      from:
                        _state: posts
                      key:
                        - _state: selector_1
                        - ':'
                        - _state: selector_2
                  - null
              params:
                # Create an object with an evaluated key to set to state
                _object.defineProperty:
                  on: {}
                  key:
                    # Create cache key
                    _string.concat:
                      - 'cache.'
                      - _state: selector_1
                      - ':'
                      - _state: selector_2
                  descriptor:
                    value:
                      _request: call_api.data.data
                    enumerable: true
                    writable: true
      # Same as selector_1
      - id: selector_2
        type: Selector
        properties:
          allowClear: false
          options:
            - X
            - Y
            - Z
        events:
          onChange:
            - id: call_request
              type: Request
              skip:
                _ne:
                  - _get:
                      from:
                        _state: cache
                      key:
                        _string.concat:
                          - _state: selector_1
                          - ':'
                          - _state: selector_2
                  - null
              messages:
                loading: true
                success: true
              params:
                - call_api
            - id: set_request
              type: SetState
              skip:
                _ne:
                  - _get:
                      from:
                        _state: posts
                      key:
                        - _state: selector_1
                        - ':'
                        - _state: selector_2
                  - null
              params:
                _object.defineProperty:
                  on: {}
                  key:
                    _string.concat:
                      - 'cache.'
                      - _state: selector_1
                      - ':'
                      - _state: selector_2
                  descriptor:
                    value:
                      _request: call_api.data.data
                    enumerable: true
                    writable: true
      # Markdown to display state value
      - id: state
        type: Markdown
        properties:
          content:
            _nunjucks:
              template: |
                ```
                {{ state | safe }}
                ```
              on:
                state:
                  _yaml.stringify:
                    - _state: true 
```

**Comment by JohannMoller** [comment]
Hi @SysLibreFR,

@SamTolmay's example is an excellent solution for caching past request results. 
I, however, understood your question slightly differently. I understood it as you want to fetch a request once and then filter the result of the request client-side based on some user input. 
To achieve this you can make use of some of our [operators](https://docs.lowdefy.com/operators) to filter your full request result. The following example uses [`_mql.aggregate`](https://docs.lowdefy.com/_mql), which is an implementation of MongoDB's aggregation language.
```yaml
lowdefy: 3.22.0

connections:
  - id: api
    type: AxiosHttp
    properties:
      baseURL: https://postman-echo.com/post
      method: post

pages:
  - id: page
    type: PageHeaderMenu
    events:
      onInit:
        - id: fetch_request
          type: Request
          params: call_api
        - id: set_data
          type: SetState
          params:
            data:
              _request: call_api.data.data.list
    requests:
      # This API call will echo the data we send it
      - id: call_api
        type: AxiosHttp
        connectionId: api
        properties:
          data:
            list:
              - id: 1
                name: Alice
                gender: Female
                country: Angola
              - id: 2
                name: Bob
                gender: Male
                country: China
              - id: 3
                name: Carrie
                gender: Female
                country: China
              - id: 4
                name: Dianna
                gender: Female
                country: Brazil
              - id: 5
                name: Elliot
                gender: Male
                country: Brazil
              - id: 6
                name: Dave
                gender: Male
                country: Angola

    blocks:
      - id: selector_gender
        type: Selector
        properties:
          allowClear: false
          options:
            - Male
            - Female
        events:
          onChange:
            - id: set_request
              type: SetState
              params:
                data:
                  # Use _mql.aggregate to filter the request value
                  _mql.aggregate:
                    on:
                      _request: call_api.data.data.list
                    pipeline:
                      # Filter the request result to match both the select_gender and selector_country values
                      - $match:
                          $and:
                            - gender:
                                _state: selector_gender
                            - country:
                                _state: selector_country
      - id: selector_country
        type: Selector
        properties:
          allowClear: false
          options:
            - Angola
            - Brazil
            - China
        events:
          onChange:
            # Same filter as with selector_gender
            - id: set_request
              type: SetState
              params:
                data:
                  _mql.aggregate:
                    on:
                      _request: call_api.data.data.list
                    pipeline:
                      - $match:
                          $and:
                            - gender:
                                _state: selector_gender
                            - country:
                                _state: selector_country
      # Markdown to display state value
      - id: state
        type: Markdown
        properties:
          content:
            _nunjucks:
              template: |
                ```
                {{ state | safe }}
                ```
              on:
                state:
                  _yaml.stringify:
                    - _state: true
```

You would probably be able to achieve the same with [`_array.filter`](https://docs.lowdefy.com/_array) if you aren't comfortable with MongoDB's query language.
