### DISCUSSION TITLE
ControlledList in ControlledList

### DISCUSSION THREAD

**Discussion by AndriiSydorenko1904** [lowdefy/lowdefy#917] [Questions and Help] [answered]
Hello
I have a structure like

```
items: List[
  title: List[]
]
```

and lowdefy syntax
```
      - id: items
        type: ControlledList
        blocks:
          - id: items.$.type
            type: ButtonSelector
            layout:
              span: 12
            required: true
            properties:
              title: Type
              label:
                span: 10
                align: right
              options:
                _request: get_item_type.data
          - id: title
            type: ControlledList
            layout:
              contentJustify: center
            blocks:
              - id: items.$.title.$.lang
                type: Selector
                layout:
                  span: 12
                required: true
                properties:
                  title: Lang
                  options:
                    _request: get_available_langs.data
              - id: items.$.title.$.val
                type: TextInput
                layout:
                  span: 12
                required: true
                properties:
                  title: Value
```
I send data to the backend and create a record to the database
The question arises when I want to update a record
```
events:
  onEnter:
    - id: set_menu_info
      type: SetState
      params:
        _request: get_menu_id.data
```
the outer ControlledList is filled with data, while the inner is not.
How do I fill the structures of the nested ControlledList?
