### DISCUSSION TITLE
Upload Image

### DISCUSSION THREAD

**Discussion by AndriiSydorenko1904** [lowdefy/lowdefy#921] [Questions and Help] [answered]
How can I upload a picture and send it to the backend using AxiosHttp?

**Comment by AndriiSydorenko1904** [comment]
I use Html type

```
  - id: icon
    type: Html
    layout:
      span: 12
    properties:
      title: Icon
      html: <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
      label:
        span: 10
        align: right
```

But I don't understand how I can send data to backend
In addition, I need to send not only a picture, but also other data together.

**Comment by Gervwyk** [comment, marked as answer]
Hi @AndriiSydorenko1904 

Currently, this will not be possible using a block. We'll be adding an [Upload](https://ant.design/components/upload/) block in version 4 to make this easy. 

For now, you should be able to do this with [JsAction](https://docs.lowdefy.com/JsAction) and a little bit of javascript. I'll have a look tomorrow and try to post an example.

**Reply by AndriiSydorenko1904** [reply]
thanks for your reply
I am grateful for any help
and I'm waiting for your example, since this unresolved task blocks the entire further development process

**Reply by Gervwyk** [reply]
Hi @AndriiSydorenko1904 

See this following hack:
```yaml
lowdefy: 3.22.0
name: Lowdefy Files
app:
  html:
    appendHead: |
      <script>
        const uploadFile = (context, id) => {
          setTimeout(() => {
            const element = document.getElementById(id);
            element.addEventListener('change', (ev2) => {
              if (element.files.length > 0) {
                console.log('uploading state set', element.files );
                // context.actions.SetState({ files: element.files }); Don't do this, state will not handle file over a request because we need to handle files in our request and state serilizer.
                // write custom fetch logic here to post file to backend
              }
            });
          }, 1000);
        }
        window.lowdefy.registerJsAction('uploadFiles', uploadFile);
      </script>
    appendBody: |
      <input type="file" />
pages:
  - id: welcome
    type: PageHeaderMenu
    blocks:
      - id: file_input
        type: Html
        properties:
          html: |
            <input id="input_file" type="file" />
        events:
          onMount:
            - id: upload_file
              type: JsAction
              params:
                name: uploadFiles
                args:
                  - input_file
```
This will get you 50% there.
You need to write some custom javascript in the event method which will post the data to your backend.
Unfortunately in v3, you cannot use Files in state or requests because our serialization logic in Lowdefy does not currently allow this - we will make this work in v4.
