### DISCUSSION TITLE
AxiosHttp handling response

### DISCUSSION THREAD

**Discussion by ghost** [lowdefy/lowdefy#933] [Questions and Help]
Hello
I'm trying to figure out how to use a response from AxiosHttp in another connection. The first connection should get the required data to be able to make another connection for getting data that should be displayed on-page. The example code below is not working :( 
 ```yaml
- id: get_token
    type: AxiosHttp
    connectionId: axios
    properties:
      url: http://link
- id: get_api
    type: AxiosHttp
    connectionId: axios
    properties:
      url: https://link2
      headers: 
        "My Header":
          _request: get_token.data
```

**Comment by Gervwyk** [comment]
Hi @mcflyonthecloud 

Lowdefy currently does not fire requests sequentially on the server, when triggering more the on request in an action, for example:
```yaml
events:
  onClick:
    - id: get_data
       type: Request
       params:
         - get_token
         - get_api
```
Both of these requests will be batched, executed in parallel, and returned to the client. 

To achieve the sequential behavior that you are looking for, currently unfortunately, you need to return the value to the client before triggering the next request. For example:
```yaml
events:
  onClick:
    - id: get_token
       type: Request
       params:
         - get_token
    - id: set_token
       type: SetSate
       params:
         token:
            _request: get_token.data
    - id: get_token
       type: Request
       params:
         - get_api
```

You can then use `_state: token` in your `get_api` request. 

This behavior is not ideal in some cases like here you might not want to send the token to the client. We are working on "API pipelines" for Lowdefy v4 which will enable sequentially server-side actions.
