### DISCUSSION TITLE
Footer

### DISCUSSION THREAD

**Discussion by AndriiSydorenko1904** [lowdefy/lowdefy#958] [Questions and Help]
Hello,
When I run
> npx lowdefy@latest init

I get the following code

```
pages:
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    areas:
      content:
        justify: center
        blocks:
          - id: content_card
            type: Card
            style:
              maxWidth: 800
            blocks:
              - id: content
                type: Result
                properties:
                  title: Welcome to your Lowdefy app
                  subTitle: We are excited to see what you are going to build
                  icon:
                    name: HeartTwoTone
                    color: '#f00'
                areas:
                  extra:
                    blocks:
                      - id: docs_button
                        type: Button
                        properties:
                          size: large
                          title: Let's build something
                          color: '#1890ff'
                        events:
                          onClick:
                            - id: link_to_docs
                              type: Link
                              params:
                                url: https://docs.lowdefy.com
                                newTab: true
      footer:
        blocks:
          - id: footer
            type: Paragraph
            properties:
              type: secondary
              content: |
                Made by a Lowdefy 🤖

```
![Снимок экрана 2021-11-15 в 17 27 04](https://user-images.githubusercontent.com/79863745/141808277-d04884ad-014a-4f45-9fed-51da109a4b72.png)

When I change PageHeaderMenu -> PageSiderMenu
I have
![Снимок экрана 2021-11-15 в 17 28 51](https://user-images.githubusercontent.com/79863745/141808555-44e19253-aa77-4e40-b404-3920aa5d9d66.png)

My footer not in the footer position and not in the center
How I can use Footer with PageSiderMenu?

**Comment by SamTolmay** [comment]
Hi @AndriiSydorenko1904 

It looks like we have a bug in the `PageSiderMenu` block. I have opened issue #959 to track this.

For now, you can do something like:
```yaml
footer:
  justify: center
  blocks:
    - id: footer
      type: Paragraph
      layout:
        flex: 0 1 auto
      properties:
        type: secondary
        content: |
          Made by a Lowdefy 🤖
```

You need the `flex` layout property so that the paragraph doesn't expand to full width.
