### DISCUSSION TITLE
Get localstorage

### DISCUSSION THREAD

**Discussion by xiaoxiji1234** [lowdefy/lowdefy#963] [Questions and Help] [answered]
Hello, what method or operator can get localstorage？

**Comment by SamTolmay** [comment, marked as answer]
Hi @xiaoxiji1234 

Support for local storage is still an open feature request: #697

To do this right now you can use [custom operators and actions](https://docs.lowdefy.com/custom-code).

Something like:
```js
function localStorageGetItem(key) {
  return localStorage.getItem(key);
}

function localStorageSetItem(context, key, value) {
  return localStorage.setItem(key, value);
}

window.lowdefy.registerJsOperator('localStorageGetItem', localStorageGetItem);
window.lowdefy.registerJsAction('localStorageSetItem', localStorageSetItem);
```

Then to use it:
```yaml
id: button
type: Button
events:
  onClick:
    - id: set_local_storage
      type: JsAction
      params:
        name: localStorageSetItem
        args:
          - my_key
          - my_value
```

```yaml
_js.localStorageGetItem:
  - my_key
```
