### DISCUSSION TITLE
how to call external API to fetch data dynamically populate Bar chart?

### DISCUSSION THREAD

**Discussion by mirzaehtishamdanish** [lowdefy/lowdefy#989] [Questions and Help] [answered]
```yaml
id: new-bar-chart
type: PageHeaderMenu
properties:
  title: Kafka Dashboard # The title in the browser tab.
layout:
  contentJustify: center # Center the contents of the page.
blocks:
  - id: content_card
    type: Card
    layout:
      size: 800 # Set the size of the card so it does not fill the full screen.
      contentGutter: 16 # Make a 16px gap between all blocks in this card.
    blocks:
      - id: page_heading
        type: Title
        properties:
          content: Kafka Message Details # Change the title on the page.
          level: 3 # Make the title a little smaller (an html `<h3>`).

      - id: block_id
        type: EChart
        properties:
          option:
            xAxis:
              type: category
              data:
                - Mon
                - Tue
                - Wed
                - Thu
                - Fri
                - Sat
                - Sun
            yAxis:
              type: value
            series:
              - type: bar
              - request:
                data: 
                  - 150
                  - 230
                  - 224
                  - 218
                  - 135
                  - 147
                  - 260
```

**Comment by SamTolmay** [comment, marked as answer]
Hi @mirzaehtishamdanish 

To call an external API you can use the [`AxiosHttp `](https://docs.lowdefy.com/AxiosHttp) request. You can read more about connections and requests [here](https://docs.lowdefy.com/connections-and-requests).


Assuming you have an API that returns the following data:
```yaml
- day: Mon
  count: 150
- day: Mon
  count: 230
# ...
```

We usually use the `encode` property on ECharts to map data to the chart. So the chart would look like:
```yaml
id: block_id
type: EChart
properties:
  option:
    dataset:
      source:
        # Use request operator to read request response
        # This request should probably be fetched in the page onEnterAsync event.
        _request: my_api.data
    xAxis:
      type: category
    yAxis:
      type: value
    series:
      - type: bar
        name: My Series
        encode:
          x: day
          y: count
```

You can also use the `_array.map` operator to transform the request data:
```yaml
id: block_id
type: EChart
properties:
  option:
    xAxis:
      type: category
      data:
        _array.map:
          - _request: my_api.data
          - _function:
              __args: 0.day
    yAxis:
      type: value
    series:
      - type: bar
        name: My Series
        data:
          _array.map:
            - _request: my_api.data
            - _function:
                __args: 0.count
```

**Reply by mirzaehtishamdanish** [reply]
Hi Sam,

could you please tell me where is issue?
___________________________________________________
```yaml
lowdefy: 3.23.1
name: Lowdefy starter

connections:
  - id: axios
    type: AxiosHttp

menus:
  - id: default
    links:
      - id: welcome
        type: MenuLink
        properties:
          icon: HomeOutlined
          title: Home
        pageId: welcome   

pages:
  - id: welcome
    type: PageHeaderMenu
    requests:
      - id: get_posts
        type: AxiosHttp
        connectionId: my_api
        properties:
          url: http://localhost:8080/fruits
    events:
      onEnter:
        - id: fetch_get_posts
          type: Request
          params: get_posts
    blocks:
      - id: content_card
        type: Card
        style:
            maxWidth: 800
        blocks:
        - id: block_id
          type: EChart
          properties:            
              xAxis:
                type: category
              yAxis:
                type: value
              series:
                - type: bar
                  name: My Series
                  encode:
                    x: name
                    y: description  
```
___________________________________________
My API Response:

[{"name":"Apple","description":"Winter fruit"},{"name":"Pineapple","description":"Tropical fruit"}]

**Reply by Gervwyk** [reply]
Hi @mirzaehtishamdanish 

Three things:
1) Your Request connectionId sould map to the particular connection id. So change:
```yaml
...
- id: get_posts
   type: AxiosHttp
   connectionId: axios    # change from my_api
   properties:
      url: http://localhost:8080/fruits
...
```
2) You called your request at `onEnter`, you can then use your request on the page by mapping the data where your want to your it using the `_request: get_posts` operator. Try adding a block on the page which to first simply show your API response. 
```yaml
...
blocks:
  - id: my_api_response
    type: Html
    properties:
      html: 
        _json.stringify:
          _request: get_posts
...
```
3) Finally, you are trying to map your API response to a chart. Looking at your API response it has names and descriptions, but no value axis. Usually, you plot a chart by category and value, in this case I suppose your category would be `name`, but there is no value?

**Reply by SamTolmay** [reply]
Hi @mirzaehtishamdanish

In adddition to what @Gervwyk mentioned, you also have some problems with you EChart block properties. It should look like this:
```yaml
id: block_id
type: EChart
properties:
  # --- This is missing ----
  option:
    dataset:
      source:
        _request: get_posts
  # ----------------------
    xAxis:
      type: category
    yAxis:
      type: value
    series:
      - type: bar
        name: My Series
        encode:
          x: day
          y: count
```

**Reply by mirzaehtishamdanish** [reply]
I would like to thanks for instant support my data is populate on bar chart

**Reply by SamTolmay** [reply]
It's a pleasure 😀

**Reply by mirzaehtishamdanish** [reply]
now i want to populate this  bar chart on - _ref: chart.yaml tab, but my chart is display on main yaml configuration page

**Reply by mirzaehtishamdanish** [reply]
how to display this graph on reference page?


lowdefy.ymal file
```yaml
lowdefy: 3.23.1
name: Lowdefy starter
connections:
  - id: my_api
    type: AxiosHttp
    properties:
      baseURL: http://127.0.0.1:8080

menus:
  - id: default
    links:
      - id: new-ticket
        type: MenuLink
        properties:
          icon: AlertOutlined
          title: New ticket
        pageId: new-ticket

      - id: welcome
        type: MenuLink
        properties:
          icon: HomeOutlined
          title: Home
        pageId: welcome

      - id: new-bar-chart
        type: MenuLink
        properties:
          icon: AlertOutlined
          title: Chart
        pageId: new-bar-chart    

pages:
  - _ref: new-ticket.yaml  
  - _ref: chart.yaml
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    requests:
          - id: get_posts
            type: AxiosHttp
            connectionId: my_api
            properties:
              url: /fruits
    events:
      onEnterAsync:
        - id: fetch_get_posts
          type: Request
          params: get_posts
    areas:
      content:
        justify: center
    blocks:
    
      - id: block_id
        type: EChart
        properties:
              option:
                dataset:
                  source:
                    # Use request operator to read request response
                    # This request should probably be fetched in the page onEnterAsync event.
                    _request: get_posts.data
                xAxis:
                  type: category
                yAxis:
                  type: value
                series:
                  - type: bar
                    name: My Series
                    encode:
                      x: day
                      y: count
```
chart.yaml file
```yaml
id: new-bar-chart
type: PageHeaderMenu
properties:
  title: New ticket # The title in the browser tab.
layout:
  contentJustify: center # Center the contents of the page.
blocks:
  - id: content_card
    type: Card
    layout:
      size: 800 # Set the size of the card so it does not fill the full screen.
      contentGutter: 16 # Make a 16px gap between all blocks in this card.
    blocks:
      - id: page_heading
        type: Title
        properties:
          content: Kafka Message Details # Change the title on the page.
          level: 3 # Make the title a little smaller (an html `<h3>`).

        blocks:            
          - id: block_id
            type: EChart
            properties:
              option:
                dataset:
                  source:
                    # Use request operator to read request response
                    # This request should probably be fetched in the page onEnterAsync event.
                    _request: get_posts.data
                xAxis:
                  type: category
                yAxis:
                  type: value
                series:
                  - type: bar
                    name: My Series
                    encode:
                      x: day
                      y: count
```

**Reply by JohannMoller** [reply]
Hi @mirzaehtishamdanish,

It looks like you only need to add the `requests` and `events` from your `id: welcome` page to your `id: new-bar-chart` page for the chart to work.

chart.yaml file
```yaml
id: new-bar-chart
type: PageHeaderMenu
properties:
  title: New ticket # The title in the browser tab.
layout:
  contentJustify: center # Center the contents of the page.

requests:
  - id: get_posts
     type: AxiosHttp
    connectionId: my_api
    properties:
      url: /fruits

events:
  onEnterAsync:
    - id: fetch_get_posts
      type: Request
      params: get_posts
blocks:
  - id: content_card
    type: Card
    layout:
      size: 800 # Set the size of the card so it does not fill the full screen.
      contentGutter: 16 # Make a 16px gap between all blocks in this card.
    blocks:
      - id: page_heading
        type: Title
        properties:
          content: Kafka Message Details # Change the title on the page.
          level: 3 # Make the title a little smaller (an html `<h3>`).
        blocks:            
          - id: block_id
            type: EChart
            properties:
              option:
                dataset:
                  source:
                    # Use request operator to read request response
                    # This request should probably be fetched in the page onEnterAsync event.
                    _request: get_posts.data
                xAxis:
                  type: category
                yAxis:
                  type: value
                series:
                  - type: bar
                    name: My Series
                    encode:
                      x: day
                      y: count
```
