### ISSUE TITLE
Import default icons used by blocks.

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#1005]
- [x] Move block styles into meta.
- [x] Convert default to react-icon names.
- [x] Add default icons used by blocks to as block metadata. 
- [x] Convert block types file to use styles from meta meta.
- [x] Add Label icons as default icons (like `AiOutlineLoading3Quarters`, `AiOutlineExclamationCircle`) 
- [x] Add import of block default icons during build. (buildIcons in build package).
- [x] Change plugin import to import from each package only once

```js
import {
  AiOutlineLoading3Quarters,
  AiOutlineExclamationCircle,
  AiOutlineFire,
} from 'react-icons/ai';

export default {
  AiOutlineLoading3Quarters,
  AiOutlineExclamationCircle,
  AiOutlineFire,
};

```

**Comment by SamTolmay** [comment]
```Object.keys(blocks).forEach((block) => {
  styles[block] = blocks[block].meta.styles || [];
});```

**Comment by SamTolmay** [comment]
`components.icons` structure in build:
```
- package: react-icons/ai
  icons:
    - AiOutlineExclamationCircle
    - AiOutlineLoading3Quarters
- package: react-icons/fa
  icons:
    - FaOutlineExclamationCircle
```
