### ISSUE TITLE
Notification block issue

### ISSUE THREAD

**Issue by jRom42** [lowdefy/lowdefy#1028]
#### Describe the bug

Hi. I have started using lowdefy a few days ago. Everything is fine except for  the "Notication" block type which renders the following exception in the browser console. I have tried the "Message" block which does pretty much the same and it works as expected. I have copy/pasted the "Notification" example from the docs so I really don't see what's wrong.

```
            events:
              onClick:
                - id: info
                  type: Notification
                  params:
                    message: Something happened
                    status: info
                    description: This is a longer description of the thing that happened, so that you know why it happened.
                    duration: 10
                    placement: topRight
 
```

#### To Reproduce

Example configuration reproducing the issue, or steps to reproduce the behavior.

#### Screenshots
![image](https://user-images.githubusercontent.com/6676284/146271896-95c6e39e-d997-401f-8610-c297fea3c02e.png)

#### Lowdefy Version

3.23.2

**Comment by Gervwyk** [comment]
Hi @jRom42 

The `Notification` is a block type and you are using it as an action on an event here, which is wrong. 
To use the `Notification` block, try:

```yaml
...
- id: foo_notification_id
   type: Notification
   properties:
     message: Something happened
     status: info
     description: This is a longer description of the thing that happened, so that you know why it happened.
     duration: 10
     placement: topRight
...
# some other blocks
...
- id: foo_button
  type: Button
  events:
    onClick:
      - id: open_foo
         type: CallMethod
         params:
           blockId: foo_notification_id
            method: open
```

See the `Notification` docs here: https://docs.lowdefy.com/Notification
