### ISSUE TITLE
Add a _dayjs or _moment operator for more convenient date logic.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#1051]
### Motivation

Doing date logic can be hard, for example:

```yaml
           _if:
              test:
                _mql.expr:
                  expr:
                    $and:
                      - $eq:
                          - $year:
                              _date: now
                          - $year:
                              $ifNull:
                                - _state: is_today
                                - _date: now
                      - $eq:
                          - $subtract:
                              - $dayOfYear:
                                  _date: now
                              - 1
                          - $dayOfYear:
                              $ifNull:
                                - _state: is_today
                                - _date: now
                      - $ne:
                          - _state: is_today
                          - null
                  on: {}
              then: Today
              else: Not Today
```
or 
```yaml
_if:
   test: 
      _eq:
        - _number.parseInt:
          - _format.momentFormat:
               on:
                 _date: now
               params:
                 format: 'YYYYMMDD'
          - _state: datum11
  then: datum11 is today
```
To test if the selected date is today. This could be dome much simpler by implementing `_dayjs.isSame` or `_moment.isSame`.

We'll likely switch to dayjs instead of moment due to moment project status not being maintained anymore.
