### ISSUE TITLE
Visible change removes value in list from state

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#1120]
#### Describe the bug

If a list is placed inside a box, and the box visiblity is set to false and the true, the list value is removed from state and not restored

#### To Reproduce

```yaml
lowdefy: 3.23.2

pages:
  - id: test
    type: Context
    events:
      onInit:
        - id: init_state
          type: SetState
          params:
            visible: true
            object:
              list:
                - value: a
                - value: b
                - value: c
    blocks:
      - id: visible
        type: Switch
      - id: box
        type: Box
        visible:
          _state: visible
        blocks:
          - id: object.list
            type: List
            blocks:
              - id: object.list.$.value
                type: Paragraph
                properties:
                  content:
                    _state: object.list.$.value
```
