### ISSUE TITLE
A modal reopens when placed in a block with request loading.

### ISSUE THREAD

**Issue by sah-memela** [lowdefy/lowdefy#1188]
#### Describe the bug

A modal reopens after being closed when placed in a block with request loading.

#### To Reproduce

```yaml
  - id: component
    type: Box
    events:
      onClick:
        - id: box_modal_data
          type: Request
          messages:
            loading: true # this seems to be the problem when the modal is in the box
          params: box_modal_data_table
        - id: open_modal
          type: CallMethod
          params:
            blockId: box_modal
            method: toggleOpen
    blocks:
      - _ref:
          path: box_modal.yaml.njk
          vars:
            id:
              _var: level
            box_modal_title:
              _var: modal_title
            box_modal_content:
              _var: modal_content
```

#### Lowdefy Version

Version on which you experienced this issue: 3.23.3.
