### ISSUE TITLE
Error: Invalid action type "Notification"

### ISSUE THREAD

**Issue by Narretz** [lowdefy/lowdefy#1328]
#### Describe the bug

I checked out the quick start demo, and replaced the link action with a "Notification" action:

```
  events:
    onClick:
      # - id: link_to_docs
      #   type: Link
      #   params:
      #     url: https://docs.lowdefy.com
      #     newTab: true
      - id: warning
        type: Notification
        params:
          message: Something bad might happen.
          status: warning
          description: This is a longer description of the thing that happened, so that you know why it happened.
          duration: 0
          placement: topRight
```

The app compiles but when I click the button I get and error:

`Error: Invalid action type "Notification"`

The action is defined in the docs:

https://docs.lowdefy.com/NotificationAction

#### Lowdefy Version

lowdefy: 3.23.3
