### ISSUE TITLE
Fix _object.defineProperty and  _yaml.stringify example typo

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#1339]
### Discussed in https://github.com/lowdefy/lowdefy/discussions/1337

<div type='discussions-op-text'>

<sup>Originally posted by **13316090972** August 20, 2022</sup>
There is an error in [_object](https://docs.lowdefy.com/_object) demos:

```
_object.defineProperty:
  - firstName: Rachel
    series: Friends
  - lastName
  - descriptor:
      value: Green
```
should be
```
_object.defineProperty:
  on: firstName: Rachel
      series: Friends
  key: lastName
  descriptor:
      value: Green
```

Similar errors appear in [_yaml.stringify ](https://docs.lowdefy.com/_yaml).</div>
