### ISSUE TITLE
required: false with operators fails validation.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#1465]
### Discussed in https://github.com/lowdefy/lowdefy/discussions/1462

<div type='discussions-op-text'>

<sup>Originally posted by **vrilcode** January  9, 2023</sup>
I want to have an input block required (or not required) depending on another value. My current solution shows the required indicator dynamically (red asterisk), but when Validate action is called, it behaves like `required: true`.

```yaml
  - id: my_selector
    type: ButtonSelector
    properties:
      label:
        disabled: true
      options:
        - Value1
        - Value2
  - id: my_text_input
    type: TextInput
    required:
      _if:
        test:
          _eq:
            - _state: my_selector
            - Value1
        then: Custom required message
        else: false
  - id: my_save_button
    type: Button
    events:
      onClick:
        - id: validate
          type: Validate
```

If Value1 is selected, behavior is as intended:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/31141078/211340611-234c2fb8-80a6-4ac6-8de1-6ffb40a52ece.png">

If Value2 is selected, my_text_input is still required, but should not be:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/31141078/211340697-f3d3117b-6dab-4d7f-a326-7183491ff548.png">

Any help appreciated.
</div>
