### ISSUE TITLE
Build operators are not evaluated on refDefinition in buildRefs

### ISSUE THREAD

**Issue by JohannMoller** [lowdefy/lowdefy#1488]
#### Describe the bug

Build operators are not evaluated on refDefinition in buildRefs. This means build operators can't be used to get a ref key from your env, for example.

#### To Reproduce
The below config returns `field: null` where one would expect `field: Value`

```yaml
field:
  _ref:
    path: target.yaml
    key:
      _build.env: FIELDNAME_FROM_ENV
```

`.env`
```
FIELDNAME_FROM_ENV=fieldName
```

`target.yaml`
```yaml
fieldName: Value
```
#### Lowdefy Version

4.0.0-rc.0
