### ISSUE TITLE
MSSQL custom port

### ISSUE THREAD

**Issue by vidz1979** [lowdefy/lowdefy#1513]
#### Describe the bug

Trying to connect to MSSQL using a custom port got error: `Request Error: The "config.options.port" property must be of type number.`

#### To Reproduce

.env:
```
LOWDEFY_SECRET_MSSQL_CONNECTION_STRING = mssql://<user>:<password>@<server_name>:45678/<database>
```

lowdefy.yaml
```yaml
connections:
  - id: mssql
    type: Knex
    properties:
      client: mssql
      connection:
        _secret: MSSQL_CONNECTION_STRING
```

Example configuration reproducing the issue, or steps to reproduce the behavior.

#### Screenshots

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/5623041/222318092-d55afecd-681d-4242-bb76-a0ef15371852.png">

#### Lowdefy Version

3.23.2

**Comment by vidz1979** [comment]
If I configure mssql like this works:

```
connections:
  - id: mssql
    type: Knex
    properties:
      client: mssql
      connection:
        host:
          _secret: MSSQL_SERVER
        port: 45678
        database:
          _secret: MSSQL_DB
        user:
          _secret: MSSQL_USER
        password:
          _secret: MSSQL_PASSWORD
```

But if I use `_secret: MSSQL_PORT` in port config, I got a new `Request Error: The "config.options.port" property must be of type number.`
