### ISSUE TITLE
Visibility toggle of display blocks removes value from state.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#1521]
#### Describe the bug

Visibility toggle of display blocks removes value from state.

#### To Reproduce

```
id: page
type: Box
events:
  onMount: 
   - id: set_state
     type: SetState
     params:
       status: Active
blocks:
  - id: status
     type: Button
     visible: false
```
If this does not reproduce, try when toggling the visibility field.
`status` value does not show up in state.

#### Lowdefy Version

Version 4.0.0-rc.0
