### ISSUE TITLE
SQLite connection doesn't seem to work

### ISSUE THREAD

**Issue by Banbury** [lowdefy/lowdefy#1525]
#### Describe the bug
A simple KnexRaw SELECT request on a SQLite connection returns null.

#### To Reproduce

Connection in `lowdefy.yaml`:
```
connections:
  - id: db
    type: Knex
    properties:
      client: sqlite
      connection:
        filename: ./freezer.sqlite
```

Request in a separate file:
```
requests:
  - id: get-containers
    type: KnexRaw
    connectionId: db
    properties:
      query: select * from containers;
```

And a grid to display the data in the same page as the request:
```
      - id: container-table
        type: AgGridAlpine
        properties:
          rowData:
            _log:
              _request: get-containers
          defaultColDef:
            sortable: true
            resizable: true
            filter: true
          columnDefs:
            - headerName: Id
              field: id
              width: 100
            - headerName: Location
              field: location
              width: 300
            - headerName: Contents
              field: contents
              width: 300
```
The SQLite table has the columns id, location and contents.
The result is always `null` in the browser console and no data in the grid. No error message.

#### Lowdefy Version

3.23.3

**Comment by JohannMoller** [comment]
Hi @Banbury,

Do you fetch your request somewhere on the page? Do you have an `onEnter` or `onInit` page event or a button of something that fetches the data?

**Comment by Banbury** [comment]
No. My understanding was, that AG Grid would load the data via the request in `rowData`. Since the `_log` command prints `null` to the console, I think the `_request` was executed.
I'll try calling the request in `onInit`, but even if that works, I consider the behaviour of AG Grid a bug.

**Comment by JohannMoller** [comment]
I understand. Yes, that does make sense. At the moment, you do, however, have to fetch the request using the `Request` action before you can use its response.
Something like this:
```yaml
id: page
type: PageHeaderMenu
requests:
  - id: get_posts
    type: AxiosHttp
    connectionId: my_connection
    properties:
      url: https://jsonplaceholder.typicode.com/posts
events:
  onInit:
    - id: fetch_data
      type: Request
      params: my_request
blocks:
  - id: my_table
    type: AgGridAlpine
    properties:
      rowData:
        _request: get_posts
      columnDefs:
        - headerName: ID
          field: id
        - headerName: User ID
          field: userId
        - headerName: Title
          field: title
```
