### ISSUE TITLE
Ag-Grid event onFilterChanged does not work

### ISSUE THREAD

**Issue by kemeris2000** [lowdefy/lowdefy#1559]
#### Describe the bug

Ag-Grid event onFilterChanged does not set value in state.

#### To Reproduce

```
    blocks:
      - id: markd
        type: Markdown
        properties:
          content:
            _json.stringify:
              - _log:
                  _state: FilteredRows  
      - id: table
        type: AgGridAlpine
        properties:
          columnDefs:
            - headerName: Domain
              field: domainname
              width: 200
            - headerName: Registration date
              field: regdate
              width: 170
          defaultColDef:
            sortable: true
            resizable: true
            filter: true
          rowData:
            _state: GetClientsDomains
        events:
          onFilterChanged:
            - id: set_filtered
              type: SetState
              params:
                FilteredRows:
                  _event: rows
```

#### Lowdefy Version

v3.23.3
