### ISSUE TITLE
Lowdefy4.0DocsError

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#1562]
### Discussed in https://github.com/lowdefy/lowdefy/discussions/1558

<div type='discussions-op-text'>

<sup>Originally posted by **xiaoxiji1234** April 14, 2023</sup>
Hi, I found that there is an issue with the configuration of Next Auth Providers in the Lowdefy4.0 document currently being written, as shown in the document example:
```yaml
lowdefy: 4.0.0-rc.7
providers:
  - id: github
    type: GitHubProvider
    properties:
      clientId:
        _secret: GITHUB_CLIENT_ID
      clientSecret:
        _secret: GITHUB_CLIENT_SECRET
```
I followed the example to write my app and logged in with an error, and then I modified the code to successfully log in.
My code
```yaml
lowdefy: 4.0.0-rc.7
auth:
  providers:
    - id: github
      type: GitHubProvider
      properties:
        clientId:
          _secret: GITHUB_CLIENT_ID
        clientSecret:
          _secret: GITHUB_CLIENT_SECRET
```

</div>
