### ISSUE TITLE
Can't access _global in  4.0.0-rc.7

### ISSUE THREAD

**Issue by kemeris2000** [lowdefy/lowdefy#1576]
#### Describe the bug

I have migrated my v3.23.3 app to v4.0.0-rc.7 according to [migration guide](https://docs-git-develop-lowdefy.vercel.app/v3-to-v4).
I set global value in page 'page_login' and can confirm value is set, but this global value is null on page 'page_home'. Am I missing something obvious? There is no errors in log.

#### To Reproduce

```
pages:
  - id: page_home
    type: PageHeaderMenu
    properties:
      title: page_home
    blocks:
      - id: card_display
        type: Card
        layout:
          size: 1000 # Set the size of the card so it does not fill the full screen.
          contentGutter: 16 # Make a 16px gap between all blocks in this card.
        blocks:
          - id: mark2
            type: Markdown
            properties:
              content:
                _json.stringify:
                  - _log:
                      _global: global1
  - id: page_login
    type: PageHeaderMenu
    properties:
      title: page_login
    blocks:
      - id: mark1
        type: Markdown
        properties:
          content:
            _json.stringify:
              - _log:
                  _global: global1
      - id: block_login
        type: Button
        properties:
          title: Prisijungti
        events:
          onClick:
          - id: event1
            type: SetGlobal
            params:
              global1: globalvalue1
```

#### Lowdefy Version

v4.0.0-rc.7

**Comment by Gervwyk** [comment]
Hi @kemeris2000 
Thanks for bringing this to our attention. You are right, this is a bug. It will be in our next sprint to fix.

**Comment by kemeris2000** [comment]
You are welcome.

**Comment by kemeris2000** [comment]
When next release is planned?

**Comment by Gervwyk** [comment]
Hi @kemeris2000 
Just merged the fix for this. We'll do a release today.

**Comment by kemeris2000** [comment]
Great, thank you.

**Comment by kemeris2000** [comment]
I have tested v4.0.0-rc.8 with same pages from first port and problem persist - fix does not work.

**Comment by Gervwyk** [comment]
@kemeris2000 I have tested with the code you provided and it works on v4.0.0-rc.8 as expected.
Are you running the app using `pnpx`/`npx` or did you install lowdefy using `npm`?
I'm running:
```yaml
lowdefy: 4.0.0-rc.8
name: Lowdefy starter
pages:
  - id: page_home
    type: PageHeaderMenu
    properties:
      title: page_home
    blocks:
      - id: card_display
        type: Card
        layout:
          size: 1000 # Set the size of the card so it does not fill the full screen.
          contentGutter: 16 # Make a 16px gap between all blocks in this card.
        blocks:
          - id: mark2
            type: Markdown
            properties:
              content:
                _json.stringify:
                  - _log:
                      _global: global1
  - id: page_login
    type: PageHeaderMenu
    properties:
      title: page_login
    blocks:
      - id: mark1
        type: Markdown
        properties:
          content:
            _json.stringify:
              - _log:
                  _global: global1
      - id: block_login
        type: Button
        properties:
          title: Prisijungti
        events:
          onClick:
            - id: event1
              type: SetGlobal
              params:
                global1:
                  _sum:
                    - 1
                    - _global: global1
```
And the counter works as expected when transitioning between pages.
