### ISSUE TITLE
Menu link style property not working.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#1609]
### Discussed in https://github.com/lowdefy/lowdefy/discussions/1604

<div type='discussions-op-text'>

<sup>Originally posted by **kemeris2000** June 22, 2023</sup>
Can't find how to decrease default menu height, I would appreciate any help. My failed attempt:

```
menus:
  - id: default
    style:
      '#home_menu':
        line-height: '40px !important;'
      .ant-layout-header:
        line-height: '40px !important;'
      ant-layout-header:
        line-height: '40px !important;'
    links:
      - id: b4a1d739-3595-412e-859f-215246cc32ab1
        type: MenuLink
        pageId: home
        properties:
          title: Home
          icon: HomeOutlined
```

![image](https://github.com/lowdefy/lowdefy/assets/48207709/702ce582-aa94-4675-b19c-aee6d0355698)

</div>
