### ISSUE TITLE
Lowdefy + Traefik

### ISSUE THREAD

**Issue by alphaxr6** [lowdefy/lowdefy#1616]
#### Describe the bug

Lowdefy display a blank page when behind a reverse proxy traefik

##### Docker compose

```
version: "3.8"
services:
  lowdefy:
    build: .
    ports:
      - "3000:3000"
    labels:
      traefik.enable: "true"
      traefik.http.routers.lowdefy-http.entrypoints: "web"
      traefik.http.routers.lowdefy-http.rule: "Host(`xxx`)"
      traefik.http.routers.lowdefy-http.middlewares: "SslHeader@file"
      traefik.http.routers.lowdefy-https.middlewares: "SslHeader@file"
      traefik.http.routers.lowdefy-https.entrypoints: "websecure"
      traefik.http.routers.lowdefy-https.rule: "Host(`xxx`)"
      traefik.http.routers.lowdefy-https.tls: "true"
      traefik.http.routers.lowdefy-https.tls.certresolver: "letsencrypt"
      traefik.http.services.lowdefy.loadbalancer.server.port: "3000"

  traefik:
    image: traefik:2.6
    restart: always
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./conf/:/etc/traefik/conf
      - ./shared/:/shared
```

##### Dockerfile

```
FROM node:14-buster AS build

# Set working directory and node user
WORKDIR /home/node/lowdefy

RUN chown node:node /home/node/lowdefy

USER node

# Copy app config, and change ownership of files to "node" user
COPY  --chown=node:node  . .

# Build the Lowdefy config using the Lowdefy CLI
RUN npx lowdefy@latest build

# Use the correct Lowdefy base image
FROM lowdefy/lowdefy:3.21.2

# Copy build output from build stage
COPY --from=build --chown=node:node /home/node/lowdefy/.lowdefy/build ./build

# Copy contents of public #directory into image
COPY --chown=node:node ./public ./public

# Run the server on start
CMD ["node", "./dist/server.js"]
```

##### Lowdefy.yaml

```
lowdefy: 3.23.3
name: Lowdefy starter
pages:
  - _ref: new-ticket.yaml
  - _ref: vm-deployment.yaml
  - id: welcome
    type: PageHeaderMenu
    properties:
      title: Welcome
    areas:
      content:
        justify: center
        blocks:
          - id: content_card
            type: Card
            style:
              maxWidth: 800
            blocks:
              - id: content
                type: Result
                properties:
                  title: Welcome to your Lowdefy app
                  subTitle: We are excited to see what you are going to build
                  icon:
                    name: HeartTwoTone
                    color: '#f00'
                areas:
                  extra:
                    blocks:
                      - id: docs_button
                        type: Button
                        properties:
                          size: large
                          title: Let's build something
                          color: '#1890ff'
                        events:
                          onClick:
                            - id: link_to_docs
                              type: Link
                              params:
                                url: https://docs.lowdefy.com
                                newWindow: true
      footer:
        blocks:
          - id: footer
            type: Paragraph
            properties:
              type: secondary
              content: |
                Made by a Lowdefy 🤖
```

##### Traefik.yaml

```
global:
  sendAnonymousUsage: false
log:
  level: INFO
  format: common
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    exposedByDefault: true
    swarmMode: false
  file:
    directory: /etc/traefik/conf/
    watch: true
api:
  dashboard: true
  debug: false
  insecure: true
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ':443'
certificatesResolvers:
  letsencrypt:
    acme:
      email: xxx
      storage: /shared/acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      httpChallenge:
        entryPoint: web
      tlsChallenge: {}
```

##### headers.yaml

```
http:
  middlewares:
    SslHeader:
      headers:
        FrameDeny: true
        AccessControlAllowMethods: 'GET,OPTIONS,PUT,DELETE,PATCH,OPTIONS'
        AccessControlAllowOriginList:
          - origin-list-or-null
        AccessControlMaxAge: 100
        AddVaryHeader: true
        BrowserXssFilter: true
        ContentTypeNosniff: true
        ForceSTSHeader: true
        STSIncludeSubdomains: true
        STSPreload: true
        ContentSecurityPolicy: default-src 'self' 'unsafe-inline'
        CustomFrameOptionsValue: SAMEORIGIN
        ReferrerPolicy: same-origin
        PermissionsPolicy: vibrate 'self'
        STSSeconds: 315360000
```

##### tls.yaml

```
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - CurveP521
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
```

#### Screenshots

![image](https://github.com/lowdefy/lowdefy/assets/110522034/1d2e19ec-7752-4644-bb54-c3c75ee43afa)

#### Lowdefy Version

lowdefy/lowdefy:3.21.2
