### ISSUE TITLE
Docker image does not work as expected

### ISSUE THREAD

**Issue by Heartnett** [lowdefy/lowdefy#1646]
#### Describe the bug

The Docker image does not work properly.
After setting up a docker compose file, running it, and navigating to http://localhost:3000 I am met with a 404 page.

#### To Reproduce

- Create an empty folder somewhere.
- Create a docker-compose.yml file.
```yml
version: '3.8'
services:
  lowdefy:
    image: lowdefy/lowdefy
    container_name: lowdefy
    ports:
      - 3000:3000
```
- Run it in the terminal/command-line with `docker compose up`
- Navigate to http://localhost:3000

#### Screenshots
![image](https://github.com/lowdefy/lowdefy/assets/11403655/b86a7704-8923-4183-9964-91c10753d101)

![image](https://github.com/lowdefy/lowdefy/assets/11403655/4819abc1-5ad1-4e08-8a3f-f14a97d6d184)

#### Lowdefy Version

Latest version and version 3.
