### ISSUE TITLE
Icon React Display bug + image bug display 

### ISSUE THREAD

**Issue by Yenzago** [lowdefy/lowdefy#1775]
#### Describe the bug

Hello i try to input an logo and icon but i don't know why it doesn't display it. I put my logo in the root of my app.
For the logo i use:
- id: logo
            type: Html
            properties:
              html: '<div style="background: #fff; text-align: center; padding: 10px"> <img src="/home/eyang/serviceguard/sigle-fivenines (1).jpg" height="80px" width="80px"/></div>'
            style:
              marginLeft: "10px"
            layout: 
              flex: 0 1 auto

and for the icon i use button type with no title :
- id: first_button
            type: Button
            properties:
              hideTitle: true
              variant: "contained"
              type: "primary"
              size: "large"
              icon: "AiFillAppstore"
            layout: 
              flex: 0 1 auto
             
Do you have a solution ? thanks for help

#### Screenshots

![Capture d'écran 2024-01-22 113934](https://github.com/lowdefy/lowdefy/assets/104826833/066e4402-cdc6-4233-bdd6-15698f08ad33)

#### Lowdefy Version

i use lowdefy version: 4.0.0-alpha.37

**Comment by Gervwyk** [comment]
Hi
You can put it in the `./public` folder and then change.
```
id: logo
type: Html
properties:
  html: '<div style="background: #fff; text-align: center; padding: 10px"> <img src="/sigle-fivenines (1).jpg" height="80px" width="80px"/></div>'
style:
  marginLeft: "10px"
layout: 
  flex: 0 1 auto
``` 
All files in the public folder are served under the url root, and you can nest files using folders. See https://docs.lowdefy.com/hosting-files
