### ISSUE TITLE
Error: "Connection type Knex can not be found" (Tutorial/6. Saving data to SQL)

### ISSUE THREAD

**Issue by nicolatournay** [lowdefy/lowdefy#1895]
### Discussed in https://github.com/lowdefy/lowdefy/discussions/1862

<div type='discussions-op-text'>

<sup>Originally posted by **nicolatournay** October 31, 2024</sup>
I'm currently encountering an issue in the sixth chapter of the tutorial on "Saving Data to SQL."

When I click the "Submit" button on the "Log a Ticket" form, I receive an error message stating: **"Connection type Knex cannot be found."**

**Please note that I've verified I am using an absolute path** (I'm on Windows) in my `.env` file:

```plaintext
LOWDEFY_SECRET_KNEX_CLIENT = sqlite
LOWDEFY_SECRET_KNEX_CONNECTION = {"filename": "D:\\lowdefy\\tuto_three\\tuto_three.sqlite"}
```

Below is the rest of my configuration:

1. **lowdefy.yaml**

    ```yaml
    connections:
      - id: knex
        type: Knex
        properties:
          client:
            _secret: KNEX_CLIENT
          connection:
            _json.parse:
              _secret: KNEX_CONNECTION
    ```

2. **new-ticket.yaml (requests)**

    ```yaml
    requests:
      - id: save_new_ticket
        type: KnexRaw
        connectionId: knex
        payload:
          _state: true
        properties:
          query: |
            INSERT INTO tickets (
              ticket_title,
              ticket_type,
              ticket_description,
              product,
              purchase_in_last_month,
              created_date)
            VALUES (
              :ticket_title,
              :ticket_type,
              :ticket_description,
              :product,
              :purchase_in_last_month,
              :created_date)
          parameters:
            ticket_title:
              _payload: ticket_title
            ticket_type:
              _payload: ticket_type
            ticket_description:
              _payload: ticket_description
            product:
              _payload: product
            purchase_in_last_month:
              _payload: purchase_in_last_month
            created_date:
              _date: now
    ```

3. **new-ticket.yaml (event)**

    ```yaml
    - id: submit_button
      type: Button
      layout:
        span: 12
      properties:
        title: Submit
        block: true
        type: primary # Sets the button as a primary button with color
        icon: AiOutlineSave
      events:
        onClick:
          - id: validate
            type: Validate
          - id: save_new_ticket
            type: Request
            params: save_new_ticket
          - id: reset
            type: Reset
    ```

Could you help me resolve this issue?</div>
