### ISSUE TITLE
Blocks retain value if value in state is set to undefined

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#345]
Configuration
```
blocks:
  - id: object.input1
    ...
  - id: object.input2
    ...
```

```
actions:
  onClick:
     - id: set
       type: SetState
       params:
         object: {}
```

It is expected that block inputs become null, but their values are not set to null.
