### ISSUE TITLE
Block loading prop does not update or change.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#347]
**Describe the bug**
If a block fires `callAction`, the block `loading` prop does not change to `true`, however, `actions.onClick.loading` but since this is a nested prop, React does not update the block for this nested prop change.

**To Reproduce**
This code does not put the button into a loading state.
```
     - id: test
        type: Button
        actions:
          onClick:
            - id: fetch
              type: Request
              params: request_id
```
This code does put the button into a loading state because the SetState actions causes the button to rerender.
```
     - id: test
        type: Button
        actions:
          onClick:
           - id: set_state
              type: SetState
              params:
                ts:
                  _date: 0
            - id: fetch
              type: Request
              params: request_id
```

**Expected behavior**
The `loading` prop for blocks must update, if any `_request` on a block goes into loading or any action chain busy executing.

**Lowdefy Version**
v3.4.0
