### ISSUE TITLE
Use _var as input for _ref path.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#397]
Use _var as input for _ref path.

Currently throws:
```
15:39:39 ✖ TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
15:39:39 ✖ The "path" argument must be of type string. Received an instance of Object
```

**Use Case**
file.yaml
```yml
_ref:
  path: template.yaml
  vars:
    schema: ../def.json
```
template.yaml
```yml
   field:
     _ref:
       path: 
          _schema
       transformer: change.js
```

**Lowdefy Version**
3.6.0
