### ISSUE TITLE
Cannot set visible on a context block

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#415]
**Describe the bug**
If visible is set to false on a context block, the page fails to load, even if the block is not the root context, or if visible is set to true in the onInit event.

**To Reproduce**
```yaml
 id: test
type: PageHeaderMenu
events:
  onInit:
    - id: setState
      type: SetState
      params:
        visible: true
blocks:
  - id: visible
    type: Switch
  - id: con
    type: PageHeaderMenu
    visible:
      _state: visible
```
