### ISSUE TITLE
 Add Object.defineProperty operator

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#426]
Currently, there is no way to app properties to an object with a dynamic key.
 
Config (if using Object.defineProperty):
```
_object.defineProperty:
  on:
    a: 1
  key: b
  descriptor:
    value: 2
```

A better config might be needed.
