### ISSUE TITLE
Race condition for displayMessage federation delay throws error.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#470]
**Describe the bug**
When a request is returned before displayMessage has completed loading to follow error occurs:
```
TypeError: this.context.window.displayMessage is not a function
```

**To Reproduce**
```
events:
      onInit:
        - id: fetch
          type: Request
          params: get_usersxxxxx # try to get a request which does not exisit.
```

**Expected behavior**
Hold of calling displayMessage until federation loading is done.

**Lowdefy Version**
3.10.2
