### ISSUE TITLE
Button gets stuck in loading

### ISSUE THREAD

**Issue by JohannMoller** [lowdefy/lowdefy#499]
**Describe the bug**
When using a button to call a popup container, the button gets stuck in loading state after the popup is closed.

**To Reproduce**
```yaml
- id: button
  type: Button
  events:
    onClick:
      - id: open_modal
        type: CallMethod
        params:
          blockId: modal
          method: toggleOpen
          
- id: modal
  type: Modal
```

**Expected behavior**
Button should come out of loading when I close the modal.

**Lowdefy Version**
3.11.3
