### ISSUE TITLE
Shortcut keys to fire events.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#517]
Trigger a block event when a shortcut key is pressed. For example, `cmd+enter` to trigger button `onClick` event.

An idea of how this could work:
```yaml
pages:
  - id: new
    type: Context
    events:
       onKeyPress:
          - id: fire_click
            type: TriggerEvent
            params:
              blockId: the_button
              shortcut: 'cmd+enter'
              event: onClick
    blocks:
      - id: the_button
        type: Button
        events:
          onClick:
            - id: enter
              type: SetState
              params:
                key_pressed:
                  _sum:
                    - _if_none:
                        - _state:  key_pressed
                        - 0
                    - 1
```
