### ISSUE TITLE
Renderer updates before eval is executed for the first time on lists, race contidion.

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#520]
**Describe the bug**
Renderer updates before eval is executed for the first time on lists.
Throws:
```
Uncaught TypeError: Cannot read property 'visible' of undefined
    at CategorySwitch
```

**To Reproduce**
```yaml
lowdefy: 3.12.2
name: test
connections:
  - id: brands
    type: MongoDBCollection
    properties:
      databaseName: example-crud
      collection: brands
      databaseUri:
        _secret: EXAMPLES_MDB
      write: true
pages:
  - id: new
    type: Context
    requests:
      - id: get_brands
        type: MongoDBAggregation
        connectionId: brands
        properties:
          pipeline:
            - $match: {}
    events:
      onEnter:
        - id: new
          type: SetState
          params:
            lst: ['a', 'b']
    blocks:
      - id: btn
        type: Button
        events:
          onClick:
            # only throws if this request is present, so maybe a renderer / engine race condition.
            - id: resi
              type: Request
              params: get_brands
            - id: new
              type: SetState
              params:
                lst: ['a', 'b', 'a', 'b']
      - id: lst
        type: List
        blocks:
          - id: lst.$
            type: Title
            properties:
              content:
                _state: lst.$
```

**Lowdefy Version**
3.12.2
