### ISSUE TITLE
Input required not validating correctly. 

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#554]
**Describe the bug**
When required is applied to an input field, `Validate` does not pass, or it passes incorrectly for empty fields.

**To Reproduce**
```yaml
     - id: first_name
        type: TextInput
        required: true
     - id: last_name
        type: TextInput
        required: true
     - id: submit_button
        type: Button
        events:
          onClick:
            - id: validate
              type: Validate
```

**Lowdefy Version**
Introduced in version v3.13.0
Does not exist in v3.12.6
