### ISSUE TITLE
Restore pristine / initial state after insert

### ISSUE THREAD

**Issue by ahmedrshdy** [lowdefy/lowdefy#560]
**Describe the bug**
```
    events:
      onClick:
        - id: validate
          type: Validate
        - id: add_professional
          type: Request
          params: insert_professional
        - id: pristine
          type: SetState
          params: 
            new_professional:
              first-name: ""
              last-name: ""
        - id: close_drawer
          type: CallMethod
          params:
            blockId: add_professional_drawer
            method: toggleOpen
```
Using the above events works as expected except that after clearing values of the dot state, the validation still passes for a empty dot state

**To Reproduce**
Using drawer, enter some values into the required inputs to pass validation then click submit
Now, re-open drawer and click submit without modifying the required inputs
Validation still passing the request and an empty record entry is tried but blocked by database constraints

**Expected behavior**

**Screenshots**
![Screenshot](https://prnt.sc/127xcx0)                            

**Lowdefy Version**
3.14.1

**Comment by Gervwyk** [comment]
Hi @ahmedrshdy 
To reset `state` you can simply use the [Reset](https://docs.lowdefy.com/Reset) action. Alternatively setting the input values to `null` will have the same effect. So consider:

```yaml
events:
      onClick:
        - id: validate
          type: Validate
        - id: add_professional
          type: Request
          params: insert_professional
        - id: pristine
          type: Reset
        - id: close_drawer
          type: CallMethod
          params:
            blockId: add_professional_drawer
            method: toggleOpen
```

In Lowdefy we are a little more strict about types in `state` than vanilla js to make the behavior of `state` more predictable. The [enforceType](https://github.com/lowdefy/lowdefy/blob/c6417746069471b0b10e4771ba7996f10e2fdef3/packages/helpers/src/type.js#L240) method is used to initialize all input variables, and once `state` is initialized and the `onInit` event is completed, we store the state value to be reloaded when `Reset` is triggered.
