### ISSUE TITLE
Input label shows an error message when it is supposed to show a warning message

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#562]
**Describe the bug**
When an input block has both a validation error (or required not met) and warning, and the page has not yet been evaluated, the input label highlights the input in orange, but the message displayed is the error message and not the warning message.

**To Reproduce**
```yaml
id: text
type: TextInput
required: true
validate:
  - message: Warning message
    status: warning
    pass: false
```

**Expected behaviour**
The validation message should say "Warning message".

**Lowdefy Version**
Version 3.14.1
