### ISSUE TITLE
Fix typo on AxiosHttp

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#607]
**Fix typo in docs**
See #606 

```
  - id: app_api
    type: AxiosHttp
    properties:
 <------ TYPO HERE ----->
      baseUrl: app.com/api
 <------ TYPO HERE ----->
      auth:
        username: api_user
        password:
          _secret: API_PASSWORD
```
Also fix error message:  
```
This causes the Axios to skip the base url part and fail with rather cryptic message "connect ECONNREFUSED 127.0.0.1:80".
```

**Lowdefy Version**
v3.16.5
