### ISSUE TITLE
Replace data objects on requests with a `payload` data object

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#641]
Currently, requests get sent the `event`, `input`, `global`, `state`, and `urlQuery` data objects. This means that you can use any of these operators in a request.

However, this means a lot of unnecessary data gets sent with each request, and if these data objects are to large, requests fail with a payload to large error.

Requests should only get a `payload` data object, with corresponding `_payload` data object. The request action schema should also change so that the payload can be specified.

Request action schema:
```yaml
id: request
type: Request
params:
  request: requestId
  payload:
    x:
      _state: x
```
