### ISSUE TITLE
ButtonSelector block id being rendered

### ISSUE THREAD

**Issue by APTy** [lowdefy/lowdefy#658]
**Describe the bug**
It seems the `id` field in a `ButtonSelector` block gets rendered to the page. I'm not sure whether this is intentional.

**To Reproduce**
Use a `ButtonSelector` block with an `id` set. See https://docs.lowdefy.com/ButtonSelector (and screenshot below)

**Expected behavior**
The `id` field shouldn't be rendered to the page. It seems to me that only the multi-select buttons should be rendered.

**Screenshots**
<img width="710" alt="Screen Shot 2021-06-23 at 4 03 38 PM" src="https://user-images.githubusercontent.com/9010671/123160929-c9945580-d43c-11eb-8cab-bb6fecfa2aa9.png">

**Lowdefy Version**
```
3.18.0
```

**Comment by Gervwyk** [comment]
Hi @APTy 

This is so by design. We try to implement "useful defaults", so you only have to modify the minimum properties in yaml.

You can easily disable the label:
```yaml
id: block_id
type: ButtonSelector
properties:
  options:
    - label: First
      value: 1
      disabled: false
    - label: Second
      value: 2
      disabled: false
  label:
    disabled: true
```
