### ISSUE TITLE
Errors in action operator are an empty object.

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#664]
**Describe the bug**
When an action fails, the error object is turned into an empty object (Because of JSON.stringify used in operators). This should be an object with `name`, `message` fields.

**To Reproduce**
```yaml
events:
  onClick:
    try:
      - id: will_error
        type: Request
        params: error
    catch:
      - id: catch
        type: SetState
        params:
          actions:
            _log:
              _actions: will_error
```
