### ISSUE TITLE
Document responsive layouts

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#685]
```yaml
layout:
  span: 12
  # ...
  xl:
    span: 20
    # ...
  lg:
    span: 18
    # ...
  md:
    span: 18
    # ...
  sm:
    span: 16
    # ...
  xs:
    span: 14
    # ...
```
