### ISSUE TITLE
AxiosHttp POST example wrong

### ISSUE THREAD

**Issue by zanderson-aim** [lowdefy/lowdefy#686]
#### Describe the bug

The example on this page https://docs.lowdefy.com/AxiosHttp at the bottom for POST lists "body" under the properties but the docs say it should be "data"

#### To Reproduce

Based on example that does not work
```
  - id: push_hrdata
    type: AxiosHttp
    connectionId: echo
    properties:
      url: /hrdata
      method: post 
      body: 
        _state: true
```
should be
```
  - id: push_hrdata
    type: AxiosHttp
    connectionId: echo
    properties:
      url: /hrdata
      method: post 
      data: 
        _state: true
```        

#### Lowdefy Version

v3.18.1
