### ISSUE TITLE
Switch statement operator.

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#689]
An operator that executes a switch statement.

We can take inspiration from the MongoDB [$switch](https://docs.mongodb.com/manual/reference/operator/aggregation/switch/) operator.

Possible notation:
```yaml
_switch:
  branches:
    - if:
        _eq:
          - x
          - y
      then: A
    - if:
        _eq:
          - x
          - z
      then: B
  default: C
```
