### ISSUE TITLE
Html in Button made padding with icon disappear

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#775]
#### Describe the bug

There used to be padding between icon and text. With Html in buttons introduced, the padding is now gone.

#### Screenshots

<img width="204" alt="Screenshot 2021-08-22 at 14 58 14" src="https://user-images.githubusercontent.com/7165064/130356161-2dcc1f93-bf89-424d-b7ec-fe3519874084.png">

#### Lowdefy Version

Version 3.20.4

**Comment by Radiergummi** [comment]
This can be fixed by setting the padding on the icon manually:
```yaml
- id: button
  type: Button
  properties:
    title: Save
    icon:
      style:
        marginRight: 8
```

But still, it would be nice to have padding back :)
