### ISSUE TITLE
List visible toggle does not retain subBlocks

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#787]
#### Describe the bug

When setting a List block invisible, the subBlocks are removed. As a result, the list items are lost when setting the List block to visible.

For both cases:
- SetState is called - subBlocks are removed entirely.
- visible value is changed - Blocks lose their value but subBlocks remain.

#### To Reproduce

SetState is called
```yaml
         - id: list
            type: List
            visible:
              _not:
                _state: show_title
            blocks:
              - id: list.$.title
                type: Title
                properties:
                  content:
                    _state: list.$
          - id: open_one
            type: Button
            events:
              onClick:
                - id: show
                  type: SetState
                  params:
                    show_title:
                      _not:
                        _state: show_title
```

visible value is changed
```yaml
          - id: list_two
            type: List
            visible:
              _not:
                _state: show_switch
            blocks:
              - id: list_two.$.title
                type: Title
                properties:
                  content:
                    _state: list_two.$

          - id: show_switch
            type: Switch
```

#### Screenshots

https://www.loom.com/share/9b273a652cc942d5889b997cdb3f72a8

#### Lowdefy Version

Version 3
