### ISSUE TITLE
Inline label alignment doesn't work

### ISSUE THREAD

**Issue by Radiergummi** [lowdefy/lowdefy#811]
#### Describe the bug
Setting the label alignment to `right` doesn't have any effect. This affects all input blocks and is visible in the documentation, too.

#### To Reproduce
1. Create an input block:
   ```yaml
   id: block_id
   type: TextInput
   properties:
     label:
       title: test
       align: right
       inline: true
   ```
2. Create a second input block for comparison:
   ```yaml
   id: block_id
   type: TextInput
   properties:
     label:
       title: test
       align: left
       inline: true
   ```
The label will be left-aligned in both cases.

#### Screenshots
<img width="763" alt="Bildschirmfoto 2021-08-27 um 12 51 03" src="https://user-images.githubusercontent.com/6115429/131116344-f705a2e2-a874-4341-9cee-4bdd7b08afef.png">

#### Lowdefy Version
3.21.1
