### ISSUE TITLE
Tooltip shows empty tooltip when `title` is undefined

### ISSUE THREAD

**Issue by JohannMoller** [lowdefy/lowdefy#812]
#### Describe the bug

The Tooltip block shows an empty tooltip when`properties.title` is not defined. In v3.19.0 the tooltip used to not be visible when the title is not defined.
I expect this is due to the RenderHtml changes were introduced in v3.20.0 (where most ant design block titles can be defined as HTML)

#### To Reproduce
 I would expect the following to show  "Some info"
```yaml
    - id: tooltip
      type: Tooltip
      properties:
        title: Some info
      blocks:
        - id: button
          type: Button
```
Where the following should not show the tooltip
```yaml
    - id: tooltip
      type: Tooltip
      blocks:
        - id: button
          type: Button
```
#### Screenshots

The empty tooltip:
![image](https://user-images.githubusercontent.com/35911443/131241736-b1f2e3e8-0be1-41eb-8a0d-24eac75ed061.png)

#### Lowdefy Version

Version v3.21.1
