### ISSUE TITLE
0 displays as empty string in Descriptions

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#820]
#### Describe the bug

If the value of an item passed to the `Descriptions` block is `0`, nothing is rendered for that item

#### To Reproduce

```
id: test
type: Descriptions
properties:
  items:
    zero: 0
    ten: 10
```

#### Lowdefy Version

v3.21.1
