### ISSUE TITLE
No results using KnexRaw request

### ISSUE THREAD

**Issue by stefaschmi** [lowdefy/lowdefy#868]
#### Describe the bug

I started playing around with lowdefy to list entries from a Postgres database. If I use KnexRaw to fetch the data I can see in the Postgres stats that the SQL query reaches the database, but the list remains empty. If I change KnexRaw to KnexBuilder everything works fine. Therefore I know that at least the connection settings are correct.

#### To Reproduce
This is the request which doesn't show any data in the list, though the SQL query is shown in the Postgres stats. To be sure that the SQL is correct I tried different versions of the query (with and without ";" and quotation marks). Since KnexBuilder works I made sure that the exact same query is shown in the Postgres stats.
```yaml
- id: user_list
  type: KnexRaw
  connectionId: mydb
  properties:
    query: select name from "users"
```

This KnexBuilder request works.
```yaml
- id: user_list
  type: KnexBuilder
  connectionId: mydb
  properties:
    query:
      - select:
        - name
      - from:
        - users
```
#### Lowdefy Version

v3.22.0
