### ISSUE TITLE
Cannot set all panels collapsed on `Collapse` block.

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#886]
#### Describe the bug

We set:
```
defaultActiveKey={properties.defaultActiveKey || panels[0].key}
```

Maybe we should set another property, or collapse all by default?

This means you cannot set all panels as collapsed. As a hack, you could do:
```yaml
id: col
type: Collapse
properties:
  defaultActiveKey: hack_to_collapse_all_panels
  accordion: true
  panels:
    - key: panel_1
      title: Panel 1
    - key: panel_2
      title: Panel 2
areas:
  panel_1:
    blocks:
      - id: b1
        type: Button
  panel_2:
    blocks:
      - id: b2
        type: Button
```

#### Lowdefy Version

v3.22.0
