### ISSUE TITLE
Cannot use _date in mongo aggregation

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#901]
#### Describe the bug

Cannot use _date in MongoDB aggregation.

#### To Reproduce
The following match will not pass data.
```
$match
    $expr:
        $and:
          - $lte:
              - $incident_date
              - _if_none:
                  - _state: filter_from_month
                  - _date: '2100-01-01'
```
#### Lowdefy Version

3.22.0
