### ISSUE TITLE
Support $ index notation in Validation matcher

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#927]
#### Describe the bug

We currently do not support `$` index notation in the Validate action matching rules. So this does not work as expected:

```yaml
id: validate
type: Validate
params: items_list.$.name

#### Workaround

```yaml
id: validate
type: Validate
params:
_nunjucks:
  template: items_list.{{ index }}.name
  on:
    index:
      _index: 0
```

#### Lowdefy Version

v3.22.0
