### ISSUE TITLE
Custom plugins

### ISSUE THREAD

**Issue by SamTolmay** [lowdefy/lowdefy#945]

**Comment by correiarmjoao** [comment]
I have been making some tests for custom plugins and I have some questions that you guys might have given some thought already or have some opinions.

Right now I am defining the custom plugins to use in the Lowdefy file under a plugins key.
```yaml
  plugins:
    - id: test-plugin
      path: portal:/some/absolute/path/tests/lowdefy-custom-plugin/test-plugin
      exports:
        operators:
          client:
            - _test
            - _testSpecial
```

For some reason the file protocol in yarn 3 is working fine on the install but when importing the dependency it does not find it even though it is installed, I think it's a problem with the workspaces because it works fine outside of them. Portal protocol works fine so I am using it for tests.

I am using the above definition but it's just for tests but I think I final version should be more like the following.

```yaml
plugins:
  - name: test-plugin
    path: lowdefy-custom-plugins/test-plugin (relative to the config folder)
      or
    url: git+ssh://git@github.com/visionmedia/express.git
    exports:
      operators:
        client:
          - _test
          - _testSpecial
```

In the ideal version we wouldn't need to define the exports in the plugin definition, it should use the types file exported by the plugin itself, just like default types.

So here are some of my questions:

Do you guys think the definition should be done in the Lowdefy file?

This makes sense to me since it is consistent with all other definitions but it will not allow us to create the custom types when creating the context. We would need the resolved structure before being able to create the custom types.

What is your opinions on needing to define the exports of a plugin?

I think it makes it a lot more verbose and error prone if a user has to manually define it, also for reusability of plugins developed by the community if the docs are not clear on what is being exported it would require the user to dig through the files to find it.

If we use the export from the plugin it would be more consistent with the way types are being handled in the build already but I am struggling with this because we would either need to
  - have the plugin as build dependency which doesn't make sense
  - for a local plugin we could read the types by getting the file from the plugin path but it would not work for non local plugins unless we download them

Maybe I'm missing something here I'm not sure.
